### ISSUE TITLE
Bug: Cannot rename Content-Type in DNN 9.4

### ISSUE THREAD

**Issue by a-git-hub** [2sic/2sxc#1846] opened 2019-10-21 18:43 UTC
**I'm submitting a ...**  
[x] bug report 

**...about**   
[x] admin experience UI

**Current behavior**
In the Administration mask if you change "metadata" of some of the old Content-Types, it gets impossible to rename the Content-Type itself. 

**Expected behavior**
We need to rename one of the Content-Types. But after we changed its "metadata" it is not possible.

**Minimal reproduction of the problem with instructions**
-- Go into the Administration mask 
-- Change something in "metadata" of Content-Type "BLA", especially in the first or second input fields. 
-- Now go out and go to the heart-symbol of  the Content-Type "BLA" and try rename this Content-Type --> not working and produces a strange mix of old name and of new Metadata.

**What is the motivation / use case for changing the behavior?**
We cannot rename some Content-Types anymore.

**Please tell us about your environment:**
DNN, 2sxc

* **2sxc version(s):** 9.42.3 
* **Browser:** [all ]
* **DNN:** [ 9.X.X ] 
* **Language:** [English | German]

**Anything you would like to add**

**Comment by iJungleboy** [comment] 2019-10-21 20:36
I tried to reproduce but I can't. Just fyi, here's how it works:

1. The name is important for programming - like when you want to get all items of the type "bla" you'll use `App.Data["bla"]`
1. The metadata is for your users and yourself - a nicer name. It doesn't change the technical name, but appears in dialogs

The list shows both names, so you know what you have. 

Therefor I believe this is not an issue. I'll close, please re-open and add more infos / screenshots if you think it's still relevant.

**Comment by a-git-hub** [comment] 2019-10-22 12:11
**-- Go into the Administration mask**

**-- Click onto "metadata" (a pencil-icon)** 
![2sxc-ContentType-Umbenennen-sc01](https://user-images.githubusercontent.com/20930019/67283903-d842a080-f4d4-11e9-8ff8-a178338666d2.png)

**of Content-Type "BLA", especially in the first or second input fields:**
![2sxc-ContentType-Umbenennen-sc02](https://user-images.githubusercontent.com/20930019/67283919-ded11800-f4d4-11e9-9bf2-6a32b7844cc8.png)

**-- Now go out and click onto the heart-icon of the same Content-Type "BLA"** 
![2sxc-ContentType-Umbenennen-sc03](https://user-images.githubusercontent.com/20930019/67283960-f27c7e80-f4d4-11e9-8719-c4024a09d1ae.png)
 
**and try rename this Content-Type:** 
![2sxc-ContentType-Umbenennen-sc04](https://user-images.githubusercontent.com/20930019/67283969-f9a38c80-f4d4-11e9-94af-d0d769acc6f6.png)

**--> not working and produces a strange mixed name as a new Content-Type Name. Which we cannot ajust anymore as renaming is not possible - see the steps above.**

**Comment by a-git-hub** [comment] 2019-10-22 12:14
P.S. I don't have a button for a reopening of this isue.

**Comment by iJungleboy** [comment] 2019-10-22 12:31
just fyi: your "name" isn't valid as it has spaces. the UI doesn't show errors but that's probably why your experiment doesn't work. can you verify?

Only we can re-open issues :)

**Comment by a-git-hub** [comment] 2019-10-22 12:55
No, spaces in the name of a Content-Type are not the problem. 
We renamed "Bild im Text" into "Media im Text".

**Comment by iJungleboy** [comment] 2019-10-22 14:11
I just tried it myself and it works. Could you see what happens on the network (F12) and post your findings?

**Comment by iJungleboy** [comment] 2019-10-22 14:12
BTW: I believe the + character could be the problem in the description (not metadata). If it's sent through the url (http GET), that could get surprising results. Never thought about it...

**Comment by a-git-hub** [comment] 2019-10-22 14:35
![2sxc-ContentType-Umbenennen-sc05](https://user-images.githubusercontent.com/20930019/67297208-e0f1a180-f4e9-11e9-8ec7-9f3d8c6edd3d.png)

**Comment by iJungleboy** [comment] 2019-10-22 14:43
You should check a hit on desktopmodules/2sxc/api/eav/contenttype/save/?...

With something like this:
![image](https://user-images.githubusercontent.com/5321186/67298040-016e2b80-f4eb-11e9-890f-7bf8c90211ec.png)

and specifically 

![image](https://user-images.githubusercontent.com/5321186/67298073-09c66680-f4eb-11e9-940a-964365265990.png)

and a response like

![image](https://user-images.githubusercontent.com/5321186/67298096-134fce80-f4eb-11e9-8312-8c815bfd6a6e.png)

**Comment by iJungleboy** [comment] 2019-11-15 13:12
We can reproduce it - seems to be something that only happens in DNN 9.4. It looks like an issue with the automatic web-api json to api-parameter conversion.

**Comment by iJungleboy** [comment] 2019-11-15 13:28
Fixed in 10.20.03 (next release)

**Closed by iJungleboy** 2019-11-15 13:28 UTC
