### ISSUE TITLE
Compatibility with Plant an App version 1.23+

### ISSUE THREAD

**Issue by schotman** [2sic/2sxc#2979] opened 2023-01-04 14:00 UTC
When installing both Plant an App and 2sxc we end up having .dll version issues. 

This crashes the DNN installation.

We would like to propose the following changes to the bindings 2sxc is currently adding:

```
change the binding redirect from: 
<bindingRedirect oldVersion="0.0.0.0-32767.32767.32767.32767" newVersion="2.1.1.0" />
to: <bindingRedirect oldVersion="0.0.0.0-2.1.1.0" newVersion="2.1.1.0" />
```

It concerns the following DLLs:
```

<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
	<assemblyIdentity name="Microsoft.EntityFrameworkCore.Abstractions" publicKeyToken="adb9793829ddae60" />
	<bindingRedirect oldVersion="0.0.0.0-2.1.1.0" newVersion="2.1.1.0" />
</dependentAssembly>

<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
	<assemblyIdentity name="Microsoft.EntityFrameworkCore" publicKeyToken="adb9793829ddae60" />
	<bindingRedirect oldVersion="0.0.0.0-2.1.1.0" newVersion="2.1.1.0" />
</dependentAssembly>

<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
	<assemblyIdentity name="Microsoft.EntityFrameworkCore.Relational" publicKeyToken="adb9793829ddae60" />
	<bindingRedirect oldVersion="0.0.0.0-2.1.1.0" newVersion="2.1.1.0" />
</dependentAssembly>

<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
	<assemblyIdentity name="Microsoft.EntityFrameworkCore.SqlServer" publicKeyToken="adb9793829ddae60" />
	<bindingRedirect oldVersion="0.0.0.0-2.1.1.0" newVersion="2.1.1.0" />
</dependentAssembly>

<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
	<assemblyIdentity name="Microsoft.Extensions.Caching.Abstractions" publicKeyToken="adb9793829ddae60" />
	<bindingRedirect oldVersion="0.0.0.0-2.1.1.0" newVersion="2.1.1.0" />
</dependentAssembly>

<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
	<assemblyIdentity name="Microsoft.Extensions.Caching.Memory" publicKeyToken="adb9793829ddae60" />
	<bindingRedirect oldVersion="0.0.0.0-2.1.1.0" newVersion="2.1.1.0" />
</dependentAssembly>

<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
	<assemblyIdentity name="Microsoft.Extensions.Configuration.Binder" publicKeyToken="adb9793829ddae60" />
	<bindingRedirect oldVersion="0.0.0.0-2.1.1.0" newVersion="2.1.1.0" />
</dependentAssembly>

<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
	<assemblyIdentity name="Microsoft.Extensions.Configuration" publicKeyToken="adb9793829ddae60" />
	<bindingRedirect oldVersion="0.0.0.0-2.1.1.0" newVersion="2.1.1.0" />
</dependentAssembly>

<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
	<assemblyIdentity name="Microsoft.Extensions.Logging" publicKeyToken="adb9793829ddae60" />
	<bindingRedirect oldVersion="0.0.0.0-2.1.1.0" newVersion="2.1.1.0" />
</dependentAssembly>

<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
	<assemblyIdentity name="Microsoft.Extensions.Options" publicKeyToken="adb9793829ddae60" />
	<bindingRedirect oldVersion="0.0.0.0-2.1.1.0" newVersion="2.1.1.0" />
</dependentAssembly>
```

**Comment by iJungleboy** [comment] 2023-01-09 14:37
@tvatavuk I believe you had already looked into this a while ago, and there were some reasons why this wasn't feasible - but I'm not sure about the details. Could you add your findings here?

**Comment by schotman** [comment] 2023-02-28 09:00
Any news on this issue? An update would be appreciated ;)

**Comment by iJungleboy** [comment] 2023-05-31 14:01
Brief summary

It concerns changes to the `web.config` which a pro can apply himself. 
The problem is that doing this automatically requires a major change how 2sxc is installed, because the standard DNN installation cannot apply the changes reliably in all scenarios (new-install, upgrade, etc.)

So to do this automatically would require a lot of work and testing - 3-5 days, which is not on our priorities unless someone sponsors it.

**Comment by iJungleboy** [comment] 2024-04-30 14:11
This is a very old task, and I believe it's not relevant any more, so I'll close it.

**Closed by iJungleboy** 2024-04-30 14:11 UTC

**Comment by bogdan-litescu** [comment] 2025-01-09 14:47
This is still an issue for most of our customers. 
It would be great if we can find a solution to respect each other's dependencies so our shared customer has a good experience. 
I can allocate technical expertise to work with you if you are open to address this.
