### ISSUE TITLE
Open the toolbar, 500 - Server error (escalate, paid)

### ISSUE THREAD

**Issue by S-Staab** [2sic/2sxc#437] opened 2015-11-12 15:07 UTC
2sxc V. 8.0.2 / Dnn V. 07.04.02 
When i open the toolbar, I receive this error. 

(This bug comes only by the first start) 

(like the picture)

![bug](https://cloud.githubusercontent.com/assets/14276625/11121576/f98d550c-8956-11e5-97f9-701c57dc1895.png)

**Comment by iJungleboy** [comment] 2015-11-13 05:20
Is this only on an app or also on content?
Do you have special folders in your system - like are you running dnn in a subfolder of your IIS?
Could you check the http response in fiddler or chrome-debug (F12) and post it here?

**Comment by S-Staab** [comment] 2015-11-13 09:42
-The mistake appears by all applikations independent the content.
-No i use a "normal" folder.


Yes i have checked this, 

the result:

in Fiddler: 
Result: 500  
URL: /en-us/desktopmodules/2sxc/api/eav/entities/getmanyforediting?appId=7

in the next step, i have checked the funktion "getmanyforediting"

in 2sxc\SexyContent\ContentGroup.cs the funktion returns the exeption 

(if (contentGroupEntity == null)
throw new Exception("ContentGroup entity is null");) 

only by the first call.

**Comment by iJungleboy** [comment] 2015-11-21 15:22
I still cannot reproduce this. Let me repeat what I understand
1. you add an app - (i'm using the timeline app). It appears, everything is ok
2. you then hit the pencil (edit) on any item (I used the one in the first slide of the timeline) - and starts to open the dialog, then throws a 500 server error
3. you refresh the page and hit edit again - now everything works

If this is what you're doing - then I tried it too and can't create the error. Any hints what I could do differently?

**Comment by S-Staab** [comment] 2015-11-23 10:42
1. yes 
2. in the next step i open the toolbar (@toolbar), at the first time i see this error. 
3. when i open the toolbar again, everything is ok

"Any hints what I could do differently?" good question... 

My way is:
1. install (2sxc V. 8.0.2) / Dnn V. 07.04.02 
2. import an app (any App which use the "toolbar") 
3. add the app 
4. put the "action button"  edit 

Show my video.

**Comment by iJungleboy** [comment] 2015-11-24 15:11
I agree that it's a problem, but cannot reproduce it. Could you check fiddler to tell me what requests you're running against the server when the error occurs? I'm guessing there are multiple requests, and that actually one is failing which I'm not expecting...

**Comment by iJungleboy** [comment] 2015-11-24 16:54
The reason I'm asking is that we had the issue a long time back and fixed something like this - but we can't reproduce it any more. So if we know what requests you're seeing, we can better guess where to look.

**Comment by S-Staab** [comment] 2015-11-25 09:41
I understand,

Header:

POST http://dnn2sxc.jwdev/desktopmodules/2sxc/api/eav/entities/getmanyforediting?appId=4 HTTP/1.1
ModuleId: 520
Accept: application/json, text/plain, */*
TabId: 89
RequestVerificationToken: abcdefgihjklmnop
Content-Type: application/json;charset=utf-8
Referer: http://dnn2sxc.jwdev/desktopmodules/tosic_sexycontent/dist/dnn/ui.html
Accept-Language: de-DE
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
Host: dnn2sxc.jwdev
Content-Length: 249
DNT: 1
Connection: Keep-Alive
Pragma: no-cache
Cookie: dnn_IsMobile=False; language=de-DE; .ASPXANONYMOUS=aO3x5fJd0QEkAAAAZjIyNGFhMjktMTgwMi00ODg1LTkzYzQtNGVjOGU5ZTJiZjZl0; __RequestVerificationToken=ggLYyT6JLqpmqvDj6Z6G8GU8-_YnxtWKMacSWSat3VrWY-MJcK3OVETucOf898KBPGBSXFh5wxjisYPj0HuuyDlc3BbmQf_bP3dYclJFK-lKsPlk_LL51hG1XHQ1; USERNAME_CHANGED=; authentication=DNN; .DOTNETNUKE=40D60009915D1FA2B18A5A0794A2BB2DD0353C28A42BE87CD53326C54A676935645780B0A904A74905E14A31A1938D8141470AC687D03EC630174E9E381111BF6E0AB88DD76A9D9C21170A8FB1864E319AEAAA51BF9104A48162D87CB76D6EC7FD4C1FD4BD73E81597EC6B78; LastPageId=0:89; StayInEditMode=NO


HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
Set-Cookie: dnn_IsMobile=False; path=/; HttpOnly
Date: Wed, 25 Nov 2015 09:10:51 GMT
Content-Length: 721

Request:

POST http://dnn2sxc.jwdev/desktopmodules/2sxc/api/eav/entities/getmanyforediting?appId=4 HTTP/1.1
ModuleId: 520
Accept: application/json, text/plain, */*
TabId: 89
RequestVerificationToken: abcdefgihjklmnop
Content-Type: application/json;charset=utf-8
Referer: http://dnn2sxc.jwdev/desktopmodules/tosic_sexycontent/dist/dnn/ui.html
Accept-Language: de-DE
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
Host: dnn2sxc.jwdev
Content-Length: 249
DNT: 1
Connection: Keep-Alive
Pragma: no-cache
Cookie: dnn_IsMobile=False; language=de-DE; .ASPXANONYMOUS=aO3x5fJd0QEkAAAAZjIyNGFhMjktMTgwMi00ODg1LTkzYzQtNGVjOGU5ZTJiZjZl0; __RequestVerificationToken=ggLYyT6JLqpmqvDj6Z6G8GU8-_YnxtWKMacSWSat3VrWY-MJcK3OVETucOf898KBPGBSXFh5wxjisYPj0HuuyDlc3BbmQf_bP3dYclJFK-lKsPlk_LL51hG1XHQ1; USERNAME_CHANGED=; authentication=DNN; .DOTNETNUKE=40D60009915D1FA2B18A5A0794A2BB2DD0353C28A42BE87CD53326C54A676935645780B0A904A74905E14A31A1938D8141470AC687D03EC630174E9E381111BF6E0AB88DD76A9D9C21170A8FB1864E319AEAAA51BF9104A48162D87CB76D6EC7FD4C1FD4BD73E81597EC6B78; LastPageId=0:89; StayInEditMode=NO

[{"Group":{"Guid":"\"688aa01f-0592-4130-b9e3-ed2fb3b8244c\"","Index":0,"Part":"content","Add":false},"Title":"Content"},{"Group":{"Guid":"\"688aa01f-0592-4130-b9e3-ed2fb3b8244c\"","Index":0,"Part":"presentation","Add":false},"Title":"Presentation"}]

Session:

POST http://dnn2sxc.jwdev/desktopmodules/2sxc/api/eav/entities/getmanyforediting?appId=4 HTTP/1.1
ModuleId: 520
Accept: application/json, text/plain, */*
TabId: 89
RequestVerificationToken: abcdefgihjklmnop
Content-Type: application/json;charset=utf-8
Referer: http://dnn2sxc.jwdev/desktopmodules/tosic_sexycontent/dist/dnn/ui.html
Accept-Language: de-DE
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
Host: dnn2sxc.jwdev
Content-Length: 249
DNT: 1
Connection: Keep-Alive
Pragma: no-cache
Cookie: dnn_IsMobile=False; language=de-DE; .ASPXANONYMOUS=aO3x5fJd0QEkAAAAZjIyNGFhMjktMTgwMi00ODg1LTkzYzQtNGVjOGU5ZTJiZjZl0; __RequestVerificationToken=ggLYyT6JLqpmqvDj6Z6G8GU8-_YnxtWKMacSWSat3VrWY-MJcK3OVETucOf898KBPGBSXFh5wxjisYPj0HuuyDlc3BbmQf_bP3dYclJFK-lKsPlk_LL51hG1XHQ1; USERNAME_CHANGED=; authentication=DNN; .DOTNETNUKE=40D60009915D1FA2B18A5A0794A2BB2DD0353C28A42BE87CD53326C54A676935645780B0A904A74905E14A31A1938D8141470AC687D03EC630174E9E381111BF6E0AB88DD76A9D9C21170A8FB1864E319AEAAA51BF9104A48162D87CB76D6EC7FD4C1FD4BD73E81597EC6B78; LastPageId=0:89; StayInEditMode=NO

[{"Group":{"Guid":"\"688aa01f-0592-4130-b9e3-ed2fb3b8244c\"","Index":0,"Part":"content","Add":false},"Title":"Content"},{"Group":{"Guid":"\"688aa01f-0592-4130-b9e3-ed2fb3b8244c\"","Index":0,"Part":"presentation","Add":false},"Title":"Presentation"}]
HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
Set-Cookie: dnn_IsMobile=False; path=/; HttpOnly
Date: Wed, 25 Nov 2015 09:24:31 GMT
Content-Length: 721

{"Message":"An error has occurred.","ExceptionMessage":"ContentGroup entity is null","ExceptionType":"System.Exception","StackTrace":"   bei ToSic.SexyContent.ContentGroup..ctor(IEntity contentGroupEntity, Int32 zoneId, Int32 appId)\r\n   bei ToSic.SexyContent.ContentGroups.GetContentGroup(Guid contentGroupGuid)\r\n   bei ToSic.SexyContent.EAVExtensions.EavApiProxies.EntitiesController.GetManyForEditing(List`1 items, Int32 appId)\r\n   bei System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass13.<GetExecutor>b__c(Object instance, Object[] methodParameters)\r\n   bei System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken)"}



i hope this informations are helpful

**Comment by iJungleboy** [comment] 2015-11-26 08:09
Thanks - I believe this will help, will check.

**Comment by raphael-m** [comment] 2015-12-02 09:00
I tested the same with different browsers, DNN installations, apps but I still can't reproduce it.

**Comment by iJungleboy** [comment] 2015-12-08 11:10
Based on other feedback it seems to be an Internet-Explorer AJAX-caching issue - http://stackoverflow.com/questions/16098430/angular-ie-caching-issue-for-http

**Comment by iJungleboy** [comment] 2015-12-08 12:26
Probably have it fixed, sent to customer to verify...

**Comment by iJungleboy** [comment] 2015-12-08 22:12
@S-Staab we may have fixed it, but we're not sure. Could you try 08.00.09 which will be released in a few hours?

**Closed** 2015-12-08 22:25 UTC
Labels: affects-editor
