### ISSUE TITLE
DNN9 - drag-drop seems to fail

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#1137] opened 2017-03-21 15:34 UTC
Probably the same issue as we had with 8.x - #963 just with a modified regex...

**Comment by marcingarbarczyk** [comment] 2017-03-21 20:46
Unfortunately I have this problem still on 8.0.4. I have newest version of your module (with fix for this problem, I did read about this issue). Something works when I paste your fix to this problem in my script file, but not always (can't see when not working). 

Video before use your code in my scrirpt file https://www.screencast.com/t/xPWcDeHOqD (can't change anything)
Video after use our code in my script file https://www.screencast.com/t/32JFfmVvtg (some change order change not)

**Comment by ajplopez** [comment] 2017-04-12 22:16
I'm seeing this problem on a brand new install of DNN 9.0.2 and 2SXC 8.11.0.

**Comment by iJungleboy** [comment] 2017-05-30 11:24
Just found out that this also affects adding modules in dnn 9.1, as a drag is used to place it. 

@christophbuehler seems to think it's a minor slash-escaping issue in the regex, we'll check.

**Comment by christophbuehler** [comment] 2017-06-07 11:06
Atm, I cannot reproduce this issue in neither DNN8 nor DNN9.
The regex seems to be working just fine as well:
![snip](https://user-images.githubusercontent.com/4547315/26875325-9baec58a-4b81-11e7-90a6-51ed22e6e2bd.png)

**Comment by christophbuehler** [comment] 2017-06-08 12:51
We had a timing issue with our current fix. This approach works on DNN8 as well:
```
(function () {
    var fn = $.fn.attr;
    $.fn.attr = function () {
        var val = fn.apply(this, arguments);
        if (arguments[0] !== 'class'
            || typeof val !== 'string'
            || val.search('DnnModule-2sxc ') === -1) return val;
        return val.replace('DnnModule-2sxc ', '') + ' DnnModule-2sxc';
    };
})();
```

**Closed** 2017-06-08 12:57 UTC
