### ISSUE TITLE
Error adding Item

### ISSUE THREAD

**Issue by ArankaBond** [2sic/2sxc#1178] opened 2017-05-10 10:10 UTC
Since 3 days we get an error when adding an item in 2sxc. 
We did not change anything in the module and we can't find the source.

In the image below you see the error that we get.

![image](https://cloud.githubusercontent.com/assets/28566983/25893796/92684cb2-3579-11e7-87c0-e4fed70ac6a9.png)

Can you explain what goed wrong here?

**Comment by ArankaBond** [comment] 2017-05-10 10:15
The item does get  added to the list.

**Comment by iJungleboy** [comment] 2017-05-10 13:49
This could be a duplicate of #1158 - could you tell me what versions of 2sxc you are using and if it's a new install or an upgraded install?

**Comment by ArankaBond** [comment] 2017-05-10 13:55
I use 2sxc version 8.4.7  and its a new install.

**Comment by iJungleboy** [comment] 2017-05-10 14:02
Ok. So basically the reason is explained in #1158, but we don't know the exact cause yet. It's a bit difficult to fix - if you're versed with DBs you could fix it yourself, otherwise We'll try to provide a fix in a near future release - just note that the newest 2sxc will require dnn 7.4.2 or higher. Do you have that?

**Comment by ArankaBond** [comment] 2017-05-10 14:25
No atm its version 7.3 so I will make sure to upgrade the dnn.

**Comment by iJungleboy** [comment] 2017-05-10 20:50
Note: I tried a fix but can't really test it. You'll have to test 2sxc 09.00.02 (released tomorrow) to confirm.

**Closed** 2017-05-10 20:58 UTC
