### ISSUE TITLE
v8.4.0: Error on save - don't know why

### ISSUE THREAD

**Issue by reaxx999** [2sic/2sxc#789] opened 2016-04-19 09:48 UTC
I received an error after saving a new content module entity. 
I don't know why, but maybe it is important.

Here are my 2sxc-debugging infos
---
isValid: true
isWorking: 0 

[
  {
    "Header": {
      "EntityId": 0,
      "Guid": "a7bb99d9-51ce-42bc-b0b5-a7b9ee9f3bc1",
      "ContentTypeName": "36ab91f9-8388-4728-9bee-62ac898300a3",
      "Metadata": null,
      "Group": {
        "Guid": "9797957d-5500-4632-8dd8-a71126e5cb9d",
        "Part": "content",
        "Index": 2,
        "Add": false,
        "SlotCanBeEmpty": false,
        "SlotIsEmpty": false,
        "ContentBlockAppId": 0
      },
      "Prefill": null,
      "Title": "Content",
      "DuplicateEntity": null
    },
    "Entity": {
      "Id": null,
      "Guid": "a7bb99d9-51ce-42bc-b0b5-a7b9ee9f3bc1",
      "Type": {
        "StaticName": "36ab91f9-8388-4728-9bee-62ac898300a3"
      },
      "Attributes": {
        "Title": {
          "Values": [
            {
              "Value": "Allgemeines Feedback",
              "Dimensions": {
                "de-de": false
              }
            }
          ],
          "_currentValue": {
            "Value": "Allgemeines Feedback",
            "Dimensions": {
              "de-de": false
            }
          }
        },
        "Description": {
          "Values": [
            {
              "Value": "",
              "Dimensions": {
                "de-de": false
              }
            }
          ],
          "_currentValue": {
            "Value": "",
            "Dimensions": {
              "de-de": false
            }
          }
        },
        "IconOrImage": {
          "Values": [
            {
              "Value": "Icon",
              "Dimensions": {
                "de-de": false
              }
            }
          ],
          "_currentValue": {
            "Value": "Icon",
            "Dimensions": {
              "de-de": false
            }
          }
        },
        "LinkText": {
          "Values": [
            {
              "Value": "weiter",
              "Dimensions": {
                "de-de": false
              }
            }
          ],
          "_currentValue": {
            "Value": "weiter",
            "Dimensions": {
              "de-de": false
            }
          }
        },
        "Image": {
          "Values": [
            {
              "Value": "",
              "Dimensions": {
                "de-de": false
              }
            }
          ],
          "_currentValue": {
            "Value": "",
            "Dimensions": {
              "de-de": false
            }
          }
        },
        "Icon": {
          "Values": [
            {
              "Value": "fa-mail-reply",
              "Dimensions": {
                "de-de": false
              }
            }
          ],
          "_currentValue": {
            "Value": "fa-mail-reply",
            "Dimensions": {
              "de-de": false
            }
          }
        },
        "Link": {
          "Values": [
            {
              "Value": "#",
              "Dimensions": {
                "de-de": false
              }
            }
          ],
          "_currentValue": {
            "Value": "#",
            "Dimensions": {
              "de-de": false
            }
          }
        },
        "localizationMenus": [
          {
            "all": {}
          },
          {
            "all": {}
          },
          {
            "all": {}
          },
          {
            "all": {}
          },
          {
            "all": {}
          },
          {
            "all": {}
          },
          {
            "all": {}
          }
        ]
      },
      "IsPublished": true
    },
    "slotIsUsed": true
  },
  {
    "Header": {
      "EntityId": 0,
      "Guid": "392be817-2ea1-45ee-8032-99ad2e88b49d",
      "ContentTypeName": "7e42ad1b-cd6e-48dd-bc7e-11bbd057b096",
      "Metadata": null,
      "Group": {
        "Guid": "9797957d-5500-4632-8dd8-a71126e5cb9d",
        "Part": "presentation",
        "Index": 2,
        "Add": false,
        "SlotCanBeEmpty": true,
        "SlotIsEmpty": true,
        "ContentBlockAppId": 0
      },
      "Prefill": null,
      "Title": "Presentation Settings",
      "DuplicateEntity": 1024
    },
    "Entity": {
      "Id": 0,
      "Type": {
        "Name": "Presentation for Linkblock",
        "StaticName": "7e42ad1b-cd6e-48dd-bc7e-11bbd057b096"
      },
      "IsPublished": true,
      "TitleAttributeName": "IconColor",
      "Attributes": {
        "IconColor": {
          "Values": [
            {
              "Value": "co-color-white",
              "Dimensions": {
                "de-de": false
              }
            }
          ],
          "_currentValue": {
            "Value": "co-color-white",
            "Dimensions": {
              "de-de": false
            }
          }
        },
        "IconBackgroundColor": {
          "Values": [
            {
              "Value": "co-backgroundcolor-prim",
              "Dimensions": {
                "de-de": false
              }
            }
          ],
          "_currentValue": {
            "Value": "co-backgroundcolor-prim",
            "Dimensions": {
              "de-de": false
            }
          }
        },
        "IconSize": {
          "Values": [
            {
              "Value": "co-size-medium",
              "Dimensions": {
                "de-de": false
              }
            }
          ],
          "_currentValue": {
            "Value": "co-size-medium",
            "Dimensions": {
              "de-de": false
            }
          }
        },
        "localizationMenus": [
          {
            "all": {}
          },
          {
            "all": {}
          },
          {
            "all": {}
          }
        ]
      },
      "AppId": 2
    },
    "slotIsUsed": false
  }
]

**Comment by iJungleboy** [comment] 2016-04-19 15:54
I don't have a guess. what does the error say? I can't see any error message in your post

**Comment by reaxx999** [comment] 2016-04-19 16:25
sorry, thought it would be clear with the debug infos

after pressing save:
**1st error message**
> Had an error talking to the server (status 500).
> Message: An error has occurred.
> 
> if you are an advanced user you can learn more about what went wrong - discover how on 2sxc.org/help?tag=debug
![error-gf](https://cloud.githubusercontent.com/assets/12188254/14646961/e0796c18-065b-11e6-9cdd-264ff11d6699.jpg)

**2nd error message**
> Da lief was falsch - vielleicht funktioniert ein Teil, vielleicht auch nicht. Entschuldigung :(

![error-gf-2](https://cloud.githubusercontent.com/assets/12188254/14646967/e6eec336-065b-11e6-9380-30824cac0e7b.jpg)

**Comment by reaxx999** [comment] 2016-04-19 16:30
I just realised that the content gets saved. In my scenario, I want to create a new entity, and each time i press save and get the error, a new entity is created.

(Important background info: this content type works on some pages, and on some I get the error message.)

**Comment by iJungleboy** [comment] 2016-04-20 06:26
Ok. This means something is most likely different with the "new" button on these various pages. Please try to corner the issue some more, as it's not clear that it's a 2sxc issue. 

I'll close this for now, but please re-open if you find the cause and it's on our side.

**Closed** 2016-04-20 06:43 UTC
