### ISSUE TITLE
Evoq Content Workflow Glitch with 2sxc

### ISSUE THREAD

**Issue by wchaspuri** [2sic/2sxc#1573] opened 2018-05-24 15:46 UTC
**I'm submitting a ...**
[x]bug report

**...about**  
[x] admin experience UI
[x] DNN parts
[x] other / unknown

**Current behavior**
Evoq workflow is not working.  
When updating demo content, changes is reflected on the current view.  
On reload, prompt to publish/discard appears on the bottom.  
Clicking publish reverts content back to the demo content.  
Clicking discard keeps the content, however the content is not actually published for all user.  The updated content is only visible to Superuser/administrator/editor.  Anonymous user will still see the demo content

**Expected behavior**
On content change, publish/discard prompt appears without need to reload manually.  Clicking publish will confirm the change and publish change for all user.  Clicking discard will revert content back to demo/previous content.

**Minimal reproduction of the problem with instructions**
1. Install 2sxc on fresh DNN 9.02 install on Azure Webapps
2. Add any content to the page. 
3. Update the content's content item
4. Reload the page
5. Click publish to see that the content is reverted back to demo content
6. Click discard to see that content stays changed for admin, but change is not reflected to anonymous user.

**Please tell us about your environment:**
DNN installed as azure webapps

* **2sxc version(s):** 9.32 
* **Browser:** all
* **DNN:** 9.0.2
* **Language:** all

**Comment by wchaspuri** [comment] 2018-05-24 18:35
Possibly related to #1568.

**Comment by iJungleboy** [comment] 2018-05-24 18:59
I'm pretty sure this is not related to #1568. 

Workflow support is limited to a few scenarios, as it was sponsored by someone who needed only basic support - basically creating a draft-page in the background till released by a superior. For example, discard is not supported - it shouldn't break anything, but simply not do much. 

Also, data changed in admin-mode doesn't go into draft, as the change is not clearly assigned to a specific page. 

Last but not least: data edited on a page has certain restrictions as to getting published, again because the detection if it's part of a page or not can be difficult in data-scenarios. 

Now in your case, I don't know if this is a scenario that should work out of the box (content-mode) or a more advanced scenario (like sub-item data or query data) which would need additional configuration to behave as if it were content. Could you maybe create a short video and moderate what you're doing - from adding the module to editing / publishing changes?

**Comment by wchaspuri** [comment] 2018-05-24 19:53
https://www.screencast.com/t/ryemkrvAvG

Video starts after installing 9.32 and the default bootstrap3/4 templates.  Thanks for looking into this.

**Comment by imhobie** [comment] 2018-05-28 05:34
@wchaspuri could you try installing 2sxc 9.14 LTS release from here https://github.com/2sic/2sxc/releases and confirm whether you still experience the same issue?

@iJungleboy 
With 2sxc 9.30 the issue seem to occur with 2sxc Content mode (2sxc App mode works fine). Where after publishing the page, the content reverts to demo content or no content (if demo content is not available).

**Comment by imhobie** [comment] 2018-05-28 08:40
A bit more testing, so when you are using 2sxc 9.14 LTS everything works fine. Adding or Editing new 2sxc module (app-mode or content-mode) works as expected.

Upgrade to the latest 2sxc 9.32 LTS release, now when ADDING any new 2sxc module whether app-mode or content-mode, published changes don't show. It reverts to demo content or no content (if demo content is not available).

However, editing any pre-existing 2sxc module  (app-mode or content-mode) things work fine.

**Comment by ufoloko** [comment] 2018-05-28 16:05
FYI, is the same issue related to #1568, posted by me, the issue remains with version 9.31 and publish flow.

**Comment by wchaspuri** [comment] 2018-05-29 15:02
@imhobie I remember having2sxc working with 9.14 LTS few months ago, but when I tried it just now I'm having similar but different issue.  This is the recording for my 9.14 issue https://www.screencast.com/t/HYypSNuj

@ufoloko I thought it was the same issue as well, wasn't sure if it was fixed or not for 9.32 so I posted this issue.

**Comment by iJungleboy** [comment] 2018-05-30 07:17
Hi guys - just a heads up: I'm in Ireland right now for DNN Connect, so I won't be able to look into this for a week or so.

**Comment by wchaspuri** [comment] 2018-06-07 00:13
We finally rolled back to 9.01.01 version of DNN Evoq and workflow is working again with both 9.14 and 9.32.  Whatever DNN did with 9.02 release seems to be breaking 2sxc workflow process.

**Comment by imhobie** [comment] 2018-06-07 06:00
I agree, even with the latest 2sxc 9.32 LTS Release Candidate posted minutes ago the problem persists.

Evoq 9.0.1 - Upgrade 2sxc to latest RC release and when publishing without any workflow attached (only direct publish). The content is not published, it reverts back to demo item.

I don't think the issue is related to Evoq 9.2 or workflow. 2sxc is just not displaying the published changes even though its saving them in the back-end.

**Comment by iJungleboy** [comment] 2018-06-07 06:04
I'm glad to hear that! My guess is something is broken in Evoq - DNN 9.2 is also very, very buggy. Could you post an issue on Evoq first? My guess is 2sxc doesn't need changes at all. So I'll close this for now, but re-open it if Evoq reports that they believe it's not their issue.

**Comment by iJungleboy** [comment] 2018-06-07 06:07
So I'm confused now, because the previous comment was edited. Does 2sxc 9.32 now do it right with the previous Evoq, or not?

**Comment by imhobie** [comment] 2018-06-07 06:27
@iJungleboy Sure, will send you the details through Contact form.

**Comment by imhobie** [comment] 2018-06-07 08:33
@iJungleboy ok i've setup the sandbox environment and sent you the details via contact form.

I've only added content-mode module on the homepage with no workflow, which when you edit page, edit content and publish. The changes will not publish and will revert to demo content.

**Comment by iJungleboy** [comment] 2018-06-09 06:18
Thanks for the sandbox. I tried it and can see this as you described. I'm working on it right now, hope to find the cause soon...

**Comment by iJungleboy** [comment] 2018-06-09 08:30
I believe I found the issue and fixed it. Will release an RC2 today. Please install & test.

**Comment by imhobie** [comment] 2018-06-10 05:44
There seems to be a bug, if you can test in sandbox again you'll experience the following with content-mode:

Editing the item, and hitting publish will show an error popup "An Error Has Occured", although the 2sxc changes are published the DNN page state remains in draft mode.

Problem seem to be associated with content-mode item only, as i installed the blog app and add/edit items seem to be working fine.

**Comment by imhobie** [comment] 2018-06-11 07:04
UPDATE:
Problem appears with **BOTH** content-mode and app-mode. The difference with app-mode is that after publish you don't get a error popup. You get a page published message, however the content is still in draft mode even and is not released. The DNN page is in published stated.

This means edits are only seen by administrator and not the public.

Hopefully you can test it in the sandbox i provided.

**Comment by iJungleboy** [comment] 2018-06-12 06:06
Just fyi: I will probably not get to work on this till Saturday.

**Comment by iJungleboy** [comment] 2018-06-17 12:49
Found it - reason was that sometimes parts were actually not draft (because some parts didn't change), but the code asked for publishing it anyhow. This caused a lookup to be null (because there was no draft), and then the rest of the code failed. Will be in the next RC.

**Closed by iJungleboy** 2018-06-17 12:49 UTC
Labels: wip
