### ISSUE TITLE
2sxc 18.2 not being indexed by DNN searchengine (and searchboost)

### ISSUE THREAD

**Issue by trouble2** [2sic/2sxc#3489] opened 2024-10-28 08:32 UTC
### I'm submitting a
[x] bug report 

### ...about
[x] Content Types or data management
[x] DNN parts

### Current Behavior / Expected Behavior
Just installed 2sxc 18.2 on 2 dnn instances (9.13.4) and it looks like the apps are not being indexed anymore by the DNN indexer and/or searchboost.

### Instructions to Reproduce the Problem
Upgraded dnn to 9.13.4 and upgraded 2sxc to 18
Indexed the site => no search results.

### Your environment
dnn 9.13.4.
2sxc 18.2.0 

This is searchboost before the upgrade:
![image](https://github.com/user-attachments/assets/60fd6408-f03c-4127-a077-239246e25b71)

This is searchboost after the upgrade:
![image](https://github.com/user-attachments/assets/c05d8c4c-cc51-4582-8d93-e11a09fe5200)

I've seen this on 2 seperate site. And also checked the DNN searchmodule with the same result.

**Comment by BondForWebSolutions** [comment] 2024-10-31 10:20
Just tried again on another installation.
Upgraded to 2sxc 18.0.0, but also 18.1.0 and 18.2.0. The result is the same.
Before the upgrade 2sxc was indexed just fine (content apps, etc.)
After the upgrade 2sxc apps will not be found, only other modules.
I'm seeing these kinds of errors:

Message:Search: Error #9 of 10 in 'DnnBusinessController' while indexing module 2685 on tab 808, portal 3

StackTrace:

InnerMessage:De objectverwijzing is niet op een exemplaar van een object ingesteld.

InnerStackTrace:

   bij ToSic.Sxc.Dnn.Context.DnnUser.get_IsSiteAdmin() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\Context\DnnUser.cs:regel 32
   bij ToSic.Eav.Context.Internal.ContextOfSite.<get_UserMayAdmin>b__11_0() in C:\Projects\2sxc\eav-server\ToSic.Eav.Apps\Eav.Context\Internal\ContextOfSite.cs:regel 51
   bij ToSic.Lib.Logging.ILog_Properties.Getter[TProperty](ILog log, Func`1 getter, Boolean timer, Boolean enabled, String message, String parameters, String cPath, String cName, Int32 cLine) in C:\Projects\2sxc\eav-server\ToSic.Lib.Core\Logging\Log\ILog_Properties.cs:regel 38
   bij ToSic.Eav.Context.Internal.ContextOfSite.get_UserMayAdmin() in C:\Projects\2sxc\eav-server\ToSic.Eav.Apps\Eav.Context\Internal\ContextOfSite.cs:regel 47
   bij ToSic.Eav.Context.Internal.ContextOfApp.ToSic.Eav.Context.IContextOfUserPermissions.get_Permissions() in C:\Projects\2sxc\eav-server\ToSic.Eav.Apps\Eav.Context\Internal\ContextOfApp.cs:regel 80
   bij ToSic.Sxc.LookUp.LookUpCmsBlock..ctor(String name, IBlock block) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\LookUp\LookUpCmsBlock.cs:regel 16
   bij ToSic.Sxc.LookUp.Internal.SxcAppDataConfigProvider.GetLookupEngineForContext(IContextOfSite context, IApp appForLookup, IBlock blockForLookupOrNull) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\LookUp\Internal\SxcAppDataConfigProvider.cs:regel 54
   bij ToSic.Sxc.LookUp.Internal.SxcAppDataConfigProvider.GetDataConfiguration(EavApp app, AppDataConfigSpecs specs) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\LookUp\Internal\SxcAppDataConfigProvider.cs:regel 21
   bij ToSic.Eav.Apps.Internal.EavApp.<get_AppDataConfig>b__21_0() in C:\Projects\2sxc\eav-server\ToSic.Eav.Apps\Eav.Apps.Internal\App\EavApp_Data.cs:regel 17
   bij ToSic.Lib.Helpers.GetOnce`1.Get(Func`1 generator) in C:\Projects\2sxc\eav-server\ToSic.Lib.Core\Helpers\GetOnce.cs:regel 38
   bij ToSic.Eav.Apps.Internal.EavApp.<get_ConfigurationProvider>b__18_0() in C:\Projects\2sxc\eav-server\ToSic.Eav.Apps\Eav.Apps.Internal\App\EavApp_Data.cs:regel 11
   bij ToSic.Lib.Helpers.GetOnce`1.Get(Func`1 generator) in C:\Projects\2sxc\eav-server\ToSic.Lib.Core\Helpers\GetOnce.cs:regel 38
   bij ToSic.Sxc.Blocks.Internal.BlockBase.<get_Data>b__46_0(ILog l) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Blocks\Internal\BlockOfBase.cs:regel 150
   bij ToSic.Lib.Logging.ILog_Properties.GetterL[TProperty](ILog log, Func`2 getter, Boolean timer, Boolean enabled, String parameters, String message, String cPath, String cName, Int32 cLine) in C:\Projects\2sxc\eav-server\ToSic.Lib.Core\Logging\Log\ILog_Properties.cs:regel 56
   bij ToSic.Sxc.Blocks.Internal.BlockBase.get_Data() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Blocks\Internal\BlockOfBase.cs:regel 147
   bij ToSic.Sxc.Dnn.Search.SearchController.InitAllAndVerifyIfOk(IModule module) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\Search\SearchController.cs:regel 90
   bij ToSic.Sxc.Dnn.Search.SearchController.GetModifiedSearchDocuments(IModule module, DateTime beginDate) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\Search\SearchController.cs:regel 136
   bij ToSic.Sxc.Dnn.DnnBusinessController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\DnnBusinessController.cs:regel 111

**Comment by iJungleboy** [comment] 2024-10-31 10:34
@tvatavuk could you look into this?
Probably some unexpected user-is-null during search indexing or something?

**Comment by tvatavuk** [comment] 2024-11-07 18:03
It appears that the exceptions mentioned earlier are fixed starting from **2sxc version 18.02**. I performed four clean installations of DNN and 2sxc to test this:

1. **DNN 9.13.5 + 2sxc 18.03**
   - Tested various configuration options for search indexing in the Blog app.
   - Experimented with different DNN search indexing settings.
   - Performed multiple reindexings.
   - **Result:** Could not reproduce the issue; search indexing works as expected.

2. **DNN 9.13.5 + 2sxc 18.02**
   - Again tested multiple configuration options in both the Blog app and DNN.
   - Performed several reindexings.
   - **Result:** Could not reproduce the issue; search indexing functions correctly.

3. **DNN 9.13.5 + 2sxc 18.02 (Default Settings)**
   - Installed all components and added the Blog app without changing any options.
   - Allowed DNN to execute the initial indexing.
   - **Result:** Search indexing operates as expected.

4. **DNN 9.13.5 + 2sxc 18.01**
   - Encountered issues related to search indexing.

Based on these tests, the search indexing issue seems to be resolved in **2sxc version 18.02 and later**. 

Hope this helps! Please let me know if you need any further information.

**Closed** 2024-11-07 18:23 UTC
