### ISSUE TITLE
No content type available when opening app-management without app being selected

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/2sxc#1886] opened 2019-11-08 13:34 UTC
**I'm submitting a ...** 
[x] bug report => search github for a similar issue before submitting 
[x] not sure

[x] admin experience UI

**Current behavior**
1. I created an app
2. created a content type
3. added data fields
4. when I try to create a view, I:
- set app to token, create a new HTML file but then I con not select the content type I just created...

If I add the app to the page and go back to the view, I can select the content type

**Expected behavior**
When creating a view, I'd like to select the content type right away.

* **2sxc version(s):** 10.9.1 
* **DNN:** 8.0.4

**Comment by iJungleboy** [comment] 2019-11-09 15:26
this is strange. see any errors in F12?

**Comment by renderfarmer** [comment] 2019-11-12 12:08
Having the same problem here. First installed Version 10.09.01 on a clean DNN install and the problem appeared. Then updated to 10.20.00 and problem still persists.

DNN: 9.4.1

@Tychodewaard : Thanks for the hint on setting up the module first.

**Comment by iJungleboy** [comment] 2019-11-12 12:53
I think this is related to #1861 - it won't be fixed for another while, till we have the new management UI out.

**Comment by iJungleboy** [comment] 2020-01-09 07:38
Close because it's duplicate of #1861

**Closed by iJungleboy** 2020-01-09 07:38 UTC
Labels: wait4ng8ui
