### ISSUE TITLE
Bug: Error while trying to manage apps

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2352] opened 2021-02-18 18:21 UTC
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] admin experience UI

**Current behavior**
When I go to Manage Apps, and click on an app, I get an error. See screenshots.

![Screen Shot 2021-02-18 at 9 30 16 AM](https://user-images.githubusercontent.com/8751936/108402598-9c0b7700-71d2-11eb-853c-e72a87532117.png)
![Screen Shot 2021-02-18 at 9 25 36 AM](https://user-images.githubusercontent.com/8751936/108402613-a0379480-71d2-11eb-95ec-5b89bd50f3b1.png)
![Screen Shot 2021-02-18 at 9 27 02 AM](https://user-images.githubusercontent.com/8751936/108402645-a88fcf80-71d2-11eb-93c0-90d66480ce81.png)
![Screen Shot 2021-02-18 at 9 26 00 AM](https://user-images.githubusercontent.com/8751936/108402661-ac235680-71d2-11eb-9712-2a5c945e26f4.png)

**Expected behavior**
I should be able to manage apps.

**Minimal reproduction of the problem with instructions**
1. On a DNN 9.2.0 or 9.3.2 instance, drop the App module on a page.
2. Install the default packages of apps
3. Go to Apps Management
4. Click on an app (or create your own app and click on it to manage it)
5. A pop up will appear and there are errors.

**What is the motivation / use case for changing the behavior?**
Bug

**Please tell us about your environment:**
Both instances are about 3 years old. DNN 9.2 and 9.3.2. Both have 2sxc 11.11.4 installed. Everything else seems to work otherwise.

* **2sxc version(s):** 11.11.4  
* **Browser:** [all ]
* **DNN:** [all | 9.2.0 | 9.3.2] 
* **Language:** [any/all | English]

**Anything you would like to add**

**Comment by iJungleboy** [comment] 2021-02-18 20:39
I believe this is caused by the same thing as #2351 in which case it's already fixed in the next release.

**Closed by iJungleboy** 2021-02-18 20:39 UTC
