### ISSUE TITLE
List items with default (demo) values still appearing when hidden

### ISSUE THREAD

**Issue by mick-bsi** [2sic/2sxc#1330] opened 2017-10-11 06:48 UTC
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] Razor templating

**Current behavior**

When you hide an item from a list (Content module), default values are shown instead of hiding the item.
This "bug" seams to occur only during an objects listing, no problem on "normal" contents.

**Expected behavior**
Item hiding.

* **2sxc version(s):** 9.6.1  
* **Browser:** [all
* **DNN:** [7.4.2 ] 
* **Language:** [any/all]

**Comment by iJungleboy** [comment] 2017-10-11 06:55
Thanks. This is a duplicate of #1248

**Closed by iJungleboy** 2017-10-11 06:55 UTC
