### ISSUE TITLE
System Error when trying to Export app (or Save state) in App Settings

### ISSUE THREAD

**Issue by rodrigoratan** [2sic/2sxc#2631] opened 2021-12-26 18:34 UTC
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] admin experience UI

**Current behavior**   
"Export this entire app" or "App-state versioning" won't work on App settings

**Expected behavior**   
Export the app or save state of the app

**Instructions to Reproduce the Problem**
On 2sxc v13 if you try to Export an app or Save the state of the app it will return an error:
"ExceptionMessage":"Tried to find metadata-target name but failed for '2SexyContent-Template'\r\nNome do parâmetro: targetTypeName","ExceptionType":"System.ArgumentException"

![image](https://user-images.githubusercontent.com/964066/147417062-c7843b57-efb4-4d08-9798-85d00a9847ed.png)

![image](https://user-images.githubusercontent.com/964066/147417063-c42576c6-edc6-4480-95b4-efcb950e9494.png)

**Why change the behavior?**  
It's a bug

**Your environment**  

* **2sxc version(s):** 13.0.0

**Comment by iJungleboy** [comment] 2021-12-27 14:51
Just to verify - does this app have any views? The message basically says it couldn't find views-metadata. Could be a bug in v13, but it could also be that your app doesn't have views.

**Comment by rodrigoratan** [comment] 2021-12-27 15:20
Yes, there are views and in use

Happens even if a try to export an 'included APP'  like news v5

Didnt happen in the previous version 

I think it's a new bug in v13

**Comment by rodrigoratan** [comment] 2021-12-27 15:30
![image](https://user-images.githubusercontent.com/964066/147485804-b047d117-7263-45ae-8301-bb23719d71a2.png)
(trying to export the news v5 app)

**Comment by iJungleboy** [comment] 2021-12-29 09:30
I believe I know the cause. Still on vacation though, I'll try to tackle it early next week.

It's related to our Metadata IDs. Will prioritize.

**Comment by rodrigoratan** [comment] 2021-12-29 15:51
Don't worry! Be happy!!

Enjoy your vacations!!!

**Comment by iJungleboy** [comment] 2022-01-04 18:57
Will be fixed in 13.01

**Closed by iJungleboy** 2022-01-04 18:57 UTC
Labels: 1st priority for rapid release
