### ISSUE TITLE
2sxc - Content/Apps is not being imported

### ISSUE THREAD

**Issue by cristel77** [2sic/2sxc#2826] opened 2022-08-02 16:21 UTC
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   

[x] Content Types or data management
[x] DNN parts

**Current behavior**   
I was trying to migrate specific 2sxc pages to different environment. I use the export/import pages feature in DNN. The pages has been imported, but the data is missing.

**Expected behavior**   
The imported page should display the same output from the exported page.

**Instructions to Reproduce the Problem**

1. Created test page in test environment.
2. Exported the newly created page and included the Content.
3. Imported the new page from test to Staging environment.
4. The page has been imported, but the data is missing. See the the output below
![image](https://user-images.githubusercontent.com/106718937/182423905-f2d69f53-c061-465b-8366-752cc464800e.png)

**Why change the behavior?**  
Would like to migrate specific 2sxc pages to different environments.

**Your environment**  

* **2sxc version(s):** 12.18.0 
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** 08.04.02
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

**Comment by tvatavuk** [comment] 2022-08-03 11:54
Exporting 2sxc content and apps from one dnn to other usualy requires more than just using default dnn export/import features. 
For more info please check following:
- https://github.com/2sic/2sxc/issues/2114#issuecomment-648953638
- [Copy / Duplicate an entire Site with all Contents](https://2sxc.org/en/learn/copy-duplicate-an-entire-site)
- [Download Manual to Copy or Migrate a Site with 2sxc 7.0](https://2sxc.org/Portals/0/Content/Learn/Copy%20Entire%20Site/2sxc%20Manual%20-%20Copy%20or%20Migrate%20Sites%20with%202sxc%207.pdf)

**Comment by cristel77** [comment] 2022-08-04 06:45
> Exporting 2sxc content and apps from one dnn to other usualy requires more than just using default dnn export/import features. For more info please check following:
> 
> * [Problem with App Export/Import #2114 (comment)](https://github.com/2sic/2sxc/issues/2114#issuecomment-648953638)
> * [Copy / Duplicate an entire Site with all Contents](https://2sxc.org/en/learn/copy-duplicate-an-entire-site)
> * [Download Manual to Copy or Migrate a Site with 2sxc 7.0](https://2sxc.org/Portals/0/Content/Learn/Copy%20Entire%20Site/2sxc%20Manual%20-%20Copy%20or%20Migrate%20Sites%20with%202sxc%207.pdf)
> * https://2sxc.org/en/help?tag=export-import

I was just trying to import specific 2sxc pages not the entire site.

**Comment by tvatavuk** [comment] 2022-08-04 12:51
From what I see, You are probably missing exporting (and importing) of your content from 2sxc Content modules that are on pages you exported/imported.

In simple, common scenario You probably can export whole 2sxc **Content** app from your source DNN site, and than import it on your destination DNN site.

In latest 2sxc 14.07.04 LTS it looks like this:

STEP 1 - 2sxc export Content app from your source DNN site.
![image](https://user-images.githubusercontent.com/2724850/182845937-047c8744-9234-441e-ba23-3449eba46a01.png)

STEP 2 - 2sxc import Content app to your destination DNN site.
![image](https://user-images.githubusercontent.com/2724850/182846476-15e51a6e-0ae0-4874-a388-5dee4753d27f.png)

Notes:
- Still I do not know if this is also working the same way in your older 2sxc 2.18.0.
- Before any import, take a care, to create a backup of destination DNN database and file system in case you got results you did not expected (so you have a simple way to go back to stable version of your site before import).
- This is possible solution for one scenario, when destination is just a copy of source, and you would like to update all content in destination from source.
- It could be more complicated eg if you have different version of 2sxc module, Content app, etc... here is one example [Update Content-App from V9 to V10](https://azing.org/2sxc/r/DhXVD6Ws?activity=876a08ba-6532-494c-a5d2-bc83ca9ffa9a)
- 2sxc has dozen of import and export options to cover a wide palette of possible scenarios that hardly can fit in common dnn import/export so a better understanding and experience of 2sxc tools are required to use it in the best way. 
- If you prefer, you can also [contact the 2sxc Team or get Support](https://2sxc.org/en/contact).

**Comment by cristel77** [comment] 2022-08-08 07:16
> From what I see, You are probably missing exporting (and importing) of your content from 2sxc Content modules that are on pages you exported/imported.
> 
> In simple, common scenario You probably can export whole 2sxc **Content** app from your source DNN site, and than import it on your destination DNN site.
> 
> In latest 2sxc 14.07.04 LTS it looks like this:
> 
> STEP 1 - 2sxc export Content app from your source DNN site. ![image](https://user-images.githubusercontent.com/2724850/182845937-047c8744-9234-441e-ba23-3449eba46a01.png)
> 
> STEP 2 - 2sxc import Content app to your destination DNN site. ![image](https://user-images.githubusercontent.com/2724850/182846476-15e51a6e-0ae0-4874-a388-5dee4753d27f.png)
> 
> Notes:
> 
> * Still I do not know if this is also working the same way in your older 2sxc 2.18.0.
> * Before any import, take a care, to create a backup of destination DNN database and file system in case you got results you did not expected (so you have a simple way to go back to stable version of your site before import).
> * This is possible solution for one scenario, when destination is just a copy of source, and you would like to update all content in destination from source.
> * It could be more complicated eg if you have different version of 2sxc module, Content app, etc... here is one example [Update Content-App from V9 to V10](https://azing.org/2sxc/r/DhXVD6Ws?activity=876a08ba-6532-494c-a5d2-bc83ca9ffa9a)
> * 2sxc has dozen of import and export options to cover a wide palette of possible scenarios that hardly can fit in common dnn import/export so a better understanding and experience of 2sxc tools are required to use it in the best way.
> * If you prefer, you can also [contact the 2sxc Team or get Support](https://2sxc.org/en/contact).

I have tried the exporting of the entire app and also export parts of the App feature but still the content/apps are still missing. Could it be possible because of my DNN version?

**Comment by tvatavuk** [comment] 2022-08-08 09:07
Hi @cristel77,
I tested [export/import site procedure](https://2sxc.org/Portals/0/Content/Learn/Copy%20Entire%20Site/2sxc%20Manual%20-%20Copy%20or%20Migrate%20Sites%20with%202sxc%207.pdf) with latest DNN 9.10.2 and 2sxc 14.07.04 LTS.
It is working as expected and I did not find any issues 🤷‍♂️.

I will close this issue because I could not reproduce this it in latest 2sxc.

Fill free to open it again to provide with more info that could help us to track issue in 2sxc latest version and fix it in 2sxc code for future 2sxc versions.

**Closed by tvatavuk** 2022-08-08 09:07 UTC
