### ISSUE TITLE
Export entity only exports published data

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1466] opened 2018-02-09 11:42 UTC
**I'm submitting a ...** 
[x] not sure

**...about**
[x] Content Types or data management

**Current behavior**
Not sure if this is an intended behavior, but I'm still gonna report it.
When exporting an entity, it only exports the published data. If there are unpublished items, they will not get exported.

**Expected behavior**
Unsure.

**Minimal reproduction of the problem with instructions**
Go to admin panel, entities panel, click export.

**What is the motivation / use case for changing the behavior?**
I use the publish/unpublished feature of 2sxc to quickly hide/show the data that is ready for users to see. In a big list of something, I hide the items that are still being written/developed, and show then when they are ready.
I also use the export entity feature to quick backup the data that I need for safety.

It would be very useful to have the ability to export unpublished data as an export option.

* **2sxc version(s):** 9.14 
* **DNN:** [9.1.1 ] 
* **Language:** [English]

**Comment by iJungleboy** [comment] 2018-02-12 10:54
At the moment this is by design. Reason is, that when re-importing data there is currently no method to import drafts (which stay drafts). So exporting drafts would cause a lot of confusion (a entity could be in 2 states at the same time), and re-importing it would result in a different state than expected. 

Since we won't address this soon I'll close this for now. We see the reason it would be good, but it won't be on the roadmap for the next few months.

**Closed by iJungleboy** 2018-02-12 10:54 UTC
Labels: needs contribution or sponsoring
