### ISSUE TITLE
Data is missing error

### ISSUE THREAD

**Issue by vandersonpessoa** [2sic/2sxc#3440] opened 2024-07-05 13:43 UTC
### I'm submitting a

[x] bug report

### ...about
[x] Content Types or data management
[x] DNN parts

### Current Behavior / Expected Behavior

The 2sxc modules once in a while throw the following error: 

_Error: System.Exception: Data is missing. This is common when a site is copied but the content / apps have not been imported yet - check http://2sxc.org/help?tag=export-import_

Clearing the site cache, recycling the app pool and restarting the site do not typically resolve this issue, but usually it is resolved by the next day.

### Instructions to Reproduce the Problem

![Sem título](https://github.com/2sic/2sxc/assets/51916596/041b4e4d-c524-496a-91f2-06c80b846956)

### Your environment

* **2sxc version(s):** 16.7.0
* **Browser:** all
* **DNN:** 9.11.00
* **Hosting platform:** IIS 
* **Language:** any/all

**Comment by iJungleboy** [comment] 2024-07-11 08:32
This is hard to guess. I suggest you upgrade to the latest LTS for now (17.09).

I'll close this now, if after the upgrade you still experience something similar, we'll reopen the issue.

**Comment by vandersonpessoa** [comment] 2024-07-18 16:18
Upgrading to 17.09 didn't fix the issue

**Comment by vandersonpessoa** [comment] 2024-08-01 21:06
@iJungleboy Could you please reopen the issue?

**Comment by vandersonpessoa** [comment] 2024-08-14 19:33
We migrated our database to Azure, and it seems this issue is occurring more frequently since then. Could the migration be causing this? What other details can we provide you to help investigate this error?

**Comment by iJungleboy** [comment] 2024-08-15 11:34
Something is obviously wrong when loading the data, but I can't actually debug it without seeing it.

Basically I suggest you check the insights next time this happens. There is a lot of information about loading the data being logged, so if it fails to load there is probably a message that a folder wasn't accessible or something.

**Comment by iJungleboy** [comment] 2024-08-26 16:36
@vandersonpessoa The problem is not in the page which loads, but earlier.

Something must break loading the initial data. There are other sections in the log showing global data being loaded etc. Please go through that to find out more. 

You can see on a working system that there is one section in the logs which is huge. That's the one loading all the default schemas etc. and almost certainly the part which seems to fail randomly on your system.

**Comment by iJungleboy** [comment] 2024-08-26 16:40
Check out these sections 
![image](https://github.com/user-attachments/assets/91f759b7-5aa9-4fb7-95bf-b26f1f01e716)

There should be a very big log here, which is probably much smaller because something couldn't be accessed:

![image](https://github.com/user-attachments/assets/88f7fa41-48ab-4d35-a67f-cb10c89ce57f)

**Comment by vandersonpessoa** [comment] 2024-09-06 17:21
The boot-log section doesn't exist here:

![all-logs](https://github.com/user-attachments/assets/937fde3a-5179-4aa7-ac74-e3b51ddd1856)

I've looked into the global-start-up, but the file isn't much smaller than the one you mentioned:

![global-start-up](https://github.com/user-attachments/assets/de375c0a-b6d3-4c78-b681-9f99153a1bf1)

Also, at first sight I couldn't see much difference comparing it to a log from a site that is working properly. Please see attached and let me know your thoughts.

[global-start-up.txt](https://github.com/user-attachments/files/16911020/global-start-up.txt)

**Comment by 6TELOIV** [comment] 2024-09-09 21:56
We've noticed this issue occur sometimes if you make a change to web.config. Once IIS "reloads", 2sxc data gets out of sync. Restarting the server has always fixed the issue for us.

Based on the nature of the issue, it seems to be a race condition, making it hard to reproduce.

**Comment by vandersonpessoa** [comment] 2024-09-11 13:29
@6TELOIV Thank you for your input, but a web.config update doesn't seem to be the thing that is causing the issue in our environment. It occurs even without recent changes in web.config. Also, restarting the server or IIS doesn't fix the site here.

**Comment by 6TELOIV** [comment] 2024-09-11 13:41
At the bottom of your log, I see that it says "Found 0 Licenses"; did you have your installation verified on [patrons.2sxc](https://patrons.2sxc.org/)? I think this log indicates that somehow the connection isn't present. Other than that, I didn't find anything significantly different between your log and mine for an operational 2sxc installation.

Also not sure how a license presence would cause this error, especially at the random rate you describe. Just throwing out ideas!

**Comment by vandersonpessoa** [comment] 2024-09-12 14:48
We've noticed that this issue is only occurring with the Content App. Could the number of items be causing this?

![image](https://github.com/user-attachments/assets/32f2661f-f7e1-4f03-ae7d-d35f17c84f86)

**Comment by iJungleboy** [comment] 2024-09-17 05:06
@vandersonpessoa this is special.

Can you confirm that when this happens, it only happens on this app, and the others work? This could give us a clue as to where to look, but I must be very sure that this is the case?

**Comment by vandersonpessoa** [comment] 2024-09-17 13:36
Yes, the other apps keep working

**Comment by iJungleboy** [comment] 2024-09-18 10:32
This is helpful, but still strange.

Internally large data amounts are loaded batchwise, to prevent SQL problems - usually batches of 5000 items. But what would be strange is that it sometimes works, and sometimes fails.

If your description is correct, then the logs showing loading of that specific app should give more info (in your case Zone 2 App 2). I believe it logs the clustering and loading, and so it should also show SQL problems or something.

**Comment by iJungleboy** [comment] 2024-09-30 15:20
Note that we just released 18.01 last week, and it should show more debugging when loading the chunks. 

Any chance you could test that?

**Comment by vandersonpessoa** [comment] 2024-10-09 18:45
Sure, we've just installed the 18.01 version in one of our environments. Please see attached the boot-log and global-start-up log files.

[global-start-up.txt](https://github.com/user-attachments/files/17312722/global-start-up.txt)
[boot-log.txt](https://github.com/user-attachments/files/17312730/boot-log.txt)

**Comment by marcelom2s** [comment] 2024-10-23 16:25
is there any type of paid support that you guys can help us to understand what is going on and fix it? We are willing to do it if that's an option to resolve this issue. Thanks!

**Comment by iJungleboy** [comment] 2024-10-24 04:50
Sure. I think we'll need about 2h to evaluate this, and depending on the root cause it's anywhere from 0 - 4h or so to resolve. Head over to https://2sxc.org/en/contact to submit your request and to https://2sxc.org/en/contact/paypal to pay for 2h, then we'll setup a telco.

**Comment by marcelom2s** [comment] 2024-10-24 20:16
OK, thanks! We will check how to consistently reproduce the issue and we will be getting back to you.

**Comment by BondForWebSolutions** [comment] 2024-11-12 12:48
Had this too. Also on Azure.
The result was we had to restore a backup.

Upgrades also did not work:
https://stackoverflow.com/questions/78401994/error-with-2sxc-apps-on-site-since-this-morning

**Comment by iJungleboy** [comment] 2024-12-04 12:36
So @marcelom2s issue is not related to @BondForWebSolutions which is probably the DNN issue that 9.13.5 and 9.13.6 do something wrong with DLLs, which should be fixed in the next DNN.

Since I haven't heard from @marcelom2s since October, I'll assume this is closed.

**Closed by iJungleboy** 2024-12-04 12:36 UTC
Labels: help wanted

**Comment by vandersonpessoa** [comment] 2025-10-16 10:15
@miguelvaz78 We've managed to reproduce this issue while trying to import large batches of data a couple of months ago, so yeah, everything points to this issue being related to database performance.

**Comment by miguelvaz78** [comment] 2025-10-16 11:11
@vandersonpessoa thanks for the fast feedback. Is there any way of configuring the system so it does not depend on full data load for large content types when starting up?
What would be the workaround or your best practices for this scenarios?

**Comment by iJungleboy** [comment] 2025-10-20 03:56
@miguelvaz78 please open a new issue, with info as to the version you're using etc. since your problem may be different from the similar problem a year ago.
