### ISSUE TITLE
Editing view files with 2sxc editor causes host DB backups to corrupt and lock conection

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1344] opened 2017-10-22 10:59 UTC
**I'm submitting a ...**  
[x] not sure

**...about**   
[x] edit experience / UI
[x] other / unknown

**Current behavior**
According to my host service providers, the server where my account is located makes hourly DB backups through transaction log. 

In the last month or so, I got some 500 errors on my DNN install with reports of unable to connect to the database. This *mostly* happens when I am editing a view file with 2sxc editor. But I believe it also happened when changing settings in DNN admin.

They tell me that some query might be corrupting the db backup process. Also that this problem does not happen in any other account. I also can't find any useful info on this problem associated with DNN though.

**Please tell us about your environment:**
(will post when I have access again)

* **2sxc version(s):** 9.6.1 
* **Browser:** [all]
* **DNN:** [9.1.1] 
* **Language:** [English]

**Comment by iJungleboy** [comment] 2017-10-23 08:56
Just a short heads-up: we've never heard of this before, so ATM I don't think it's a 2sxc thing. Also, editing a view source-code doesn't even touch the DB (it just changes the file on the file system), so it's almost impossible that this interaction would be the cause. 

Because of this, I'll close this for now. If you have further info which really suggests 2sxc is involved, I'll reopen it.

**Closed by iJungleboy** 2017-10-23 08:56 UTC
