### ISSUE TITLE
Entitypicker shows Ids instead of String/Title

### ISSUE THREAD

**Issue by ropalko** [2sic/2sxc#2515] opened 2021-09-10 07:44 UTC
**I'm submitting a ...**   
[x] bug report

**...about**   
[x] edit experience / UI
[x] Content Types or data management

**Current behavior**   
In the entity picker, items are displayed with the title. When you select an element, the value under which the entry was saved is displayed in the upper list. 
![image](https://user-images.githubusercontent.com/921493/132817763-52f4a4ea-923b-4509-89c6-50dd5fb15b19.png)
The overview also shows only the IDs instead of the title. It is not visible which entries have been selected.
![image](https://user-images.githubusercontent.com/921493/132818302-a9318b53-112d-4b0e-ab5f-008a1b7c4bae.png)
The entity picker is configured as follows
![image](https://user-images.githubusercontent.com/921493/132817889-5c93bcc6-e8a0-498a-8496-24236c71512a.png)

**Expected behavior**   
After selecting, the same content should be displayed as in the dropdown.

**Your environment**  

* **2sxc version(s):** 11.22.1
* **Browser:** all
* **DNN:** 9.2.2 
* **Language:** all

**Comment by PagnoDunadan** [comment] 2021-09-10 07:51
You have configured field to save ids, not label:

![image](https://user-images.githubusercontent.com/7113033/132819261-111633fd-dbd6-4648-aea2-e9f9605fd7bf.png)

This is how String Dropdown From Query works. Behavior that you want is how Entity Query works.

**Comment by iJungleboy** [comment] 2021-09-10 07:56
My 2Cents for now

Issues is that the value which is stored should be the ID, but the user previously saw the name because the edit-form aggressively loaded the values. 

We changed this a few months ago to pre-load values in entity-dropdown, but we can't do that (in the load-api call) for string-dropdowns, so I guess the form should have some mechanism to get this (at least the selected IDs) from the query in the case that there is no cached data. 

Note also that in the above example, the dropdown itself has the correct labels, but the list of chosen items doesn't seem to know about these. So it may also just be some other bug. 

Could you look into it @PagnoDunadan

**Comment by ropalko** [comment] 2021-09-10 07:57
Its an SQL Query where the ID is necessary to find the correct entry. After switching the Value Filed the query dont work anymore.

**Comment by PagnoDunadan** [comment] 2021-09-10 08:00
Your field type if **String Dropdown From Query**. This field type stores strings. It doesn't know about entities. You should switch field to **Entity Query**

**Comment by PagnoDunadan** [comment] 2021-09-10 08:08
What you have is **string-dropdown-query** (https://docs.2sxc.org/basics/data/fields/string-dropdown-query.html):

![image](https://user-images.githubusercontent.com/7113033/132821588-f301d1ae-8ade-4179-9109-343b23916f45.png)

What you want is **entity-query** (https://docs.2sxc.org/basics/data/fields/entity-query.html)

**Comment by PagnoDunadan** [comment] 2021-09-10 08:13
Also, you say your data source is SQL Data Source? AFAIK Entity-Query only works with 2sxc entities and there is no field which works with SQL Data Source

**Comment by iJungleboy** [comment] 2021-09-10 09:03
The query delivers data which are not entities - but external data (in this case SQL). It stores the ID only. 

Previously the form always ran the query even if the field was not used, so it had the labels to show in previously selected values. 

We changed the system a few months ago so that entity-pickers get more data in the /load api call, but not for strings since it's the backend doesn't reliably know how to get those labels. 

I think the front-end should detect that it's missing labels and run the query with the IDs of the selected values to just retrieve those. We'll probably have to discuss this later.

**Comment by PagnoDunadan** [comment] 2021-09-10 09:29
I went back to check how this works and to my surprise, StringDropdownQuery does resolve ids and guids. Sorry Roman.

I only have an example with a query that doesn't use SQL Data Source and field fetches data when form is loaded, outside of what Daniel explained where backend provides cached entities.

![image](https://user-images.githubusercontent.com/7113033/132832541-017a4d2f-8a10-430b-a9f7-443001fdfd82.png)

There could indeed be a bug if your ids are not resolved when using SQL Data Source. I will try to reproduce this

**Comment by PagnoDunadan** [comment] 2021-09-23 15:18
Should be fixed. Please test

**Comment by iJungleboy** [comment] 2021-09-24 16:48
seems to work, thx!

**Closed by iJungleboy** 2021-09-24 16:48 UTC
