### ISSUE TITLE
Issue when creating a new blog article on 18.3

### ISSUE THREAD

**Issue by BondForWebSolutions** [2sic/2sxc#3504] opened 2024-11-12 09:30 UTC
### I'm submitting a
[x] bug report => search github for a similar issue before submitting

### ...about
[x] edit experience / UI

### Current Behavior / Expected Behavior
I just upgrade 2sxc to version 18.3 and tried to add a new blog article (blog 6.17.0).
And I saw these guids in the dropdowns:
![image](https://github.com/user-attachments/assets/7611ed2e-f3fd-4817-bfcd-9e99ce33b48f)

When I click on save the blog renders in de list with an error:
![image](https://github.com/user-attachments/assets/4128887a-3d65-4a57-b712-7182a0a9ec40)

The text of the error is:
"
Error: System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij ToSic.Eav.Data.EntityWrapper.FindPropertyInternal(PropReqSpecs specs, PropertyLookupPath path) in C:\Projects\2sxc\eav-server\ToSic.Eav.Core\Data\Entities\EntityWrapper.cs:regel 161
   bij ToSic.Sxc.Data.Internal.PropLookupWithPathEntity.FindPropertyInternal(PropReqSpecs specs, PropertyLookupPath path) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Data\Internal\PropertyLookup\PropLookupWithPathEntity.cs:regel 24
   bij ToSic.Sxc.Data.Internal.Dynamic.GetAndConvertHelper.GetInternal(String field, String language, Boolean lookupLink) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Data\Internal\Dynamic\GetAndConvertHelper.cs:regel 94
   bij ToSic.Sxc.Data.Internal.Dynamic.CodeItemHelper.G4T[TValue](String name, NoParamOrder noParamOrder, TValue fallback, Nullable`1 required, String cName) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Data\Internal\Dynamic\CodeItemHelper.cs:regel 45
   bij ToSic.Sxc.Data.Internal.Dynamic.CodeItemHelper.String(String name, NoParamOrder noParamOrder, String fallback, Nullable`1 required, Object scrubHtml) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Data\Internal\Dynamic\CodeItemHelper.cs:regel 71
   bij AppCode.Data.AutoGenerated.ZagAuthor.get_FullName()
   bij RazorHost.RazorViewauthordateandcategories.Execute() in [PATH TO:]\2sxc\blog6\bs5\parts\authordateandcategories.cshtml🎯:regel 10
   bij System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   bij System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   bij ToSic.Sxc.Dnn.Razor.Internal.DnnRazorCompiler.Render(RazorComponentBase page, TextWriter writer, Object data) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Dnn\Razor\Internal\DnnRazorCompiler.cs:regel 77
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij ToSic.Sxc.Dnn.Razor.Internal.DnnRazorCompiler.Render(RazorComponentBase page, TextWriter writer, Object data) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Dnn\Razor\Internal\DnnRazorCompiler.cs:regel 84
   bij ToSic.Sxc.Dnn.Razor.Internal.DnnRazorCompiler.RenderImplementation(RazorComponentBase webpage, RenderSpecs specs) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Dnn\Razor\Internal\DnnRazorCompiler.cs:regel 93
   bij ToSic.Sxc.Dnn.Razor.Internal.DnnRazorCompiler.RenderSubPage(RazorComponentBase parent, String templatePath, Object data) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Dnn\Razor\Internal\DnnRazorCompiler.cs:regel 212
   bij ToSic.Sxc.Dnn.Razor.HtmlHelper.RenderWithRoslynOrClassic(String path, Object data) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Dnn\Razor\HtmlHelper.cs:regel 109
   bij ToSic.Sxc.Dnn.Razor.HtmlHelper.Partial(String path, Object data) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Dnn\Razor\HtmlHelper.cs:regel 57
"

### Instructions to Reproduce the Problem
Upgrade to 2sxc 18.3 and add a new blog entry

### Your environment
DNN 09.13.04
2sxc 18.03.00
Blog 6.17.0

**Comment by BondForWebSolutions** [comment] 2024-11-12 10:33
I also tried to modify the generated code from:
public string FullName => _item.String("FullName", fallback: "");

To somthing like:
public string FullName => _item != null && _item.ContainsKey("FullName") ? _item.String("FullName") : "";

But that didn't really help...

**Comment by iJungleboy** [comment] 2024-11-12 13:47
I have a feeling that this is a bug in the form prefill.

Could you verify that

1. previous blogs still work
2. only new posts fail
3. new posts - when saving and re-opening - probably have an empty field in those two dropdowns?

**Comment by trouble2** [comment] 2024-11-18 11:41
That is correct.
I've seen this behaviour more on other installs (18.1, 18.2 and 18.3) 
Looks to me like it shows the values instead of the text for the dropdowns, but I don't know if that is true.
Since you're working on the pickers in the last couple of versions I suspect it has something to do with those modifications.

**Comment by iJungleboy** [comment] 2024-12-04 09:27
@trouble2 @BondForWebSolutions I can't reproduce the problem. I did this:

1. Fresh install of DNN 9.13.06
2. Install 2sxc
3. Install Blog using the auto-install-apps feature
4. added blog to a page
5. Create new - no problem
6. Edit view - no problem

Could it be that you deleted the demo-item / default category, so that the preset GUID doesn't work any more?

Or do you have other clues? The network should show that the UI is retrieving the items, and it should of course find it:

![image](https://github.com/user-attachments/assets/5085783a-4816-4011-927d-ad33fd6ad940)

**Comment by iJungleboy** [comment] 2024-12-04 12:24
...so according to my research it is 99% that you deleted the demo-data and didn't change the prefill for these fields.

As such, I'll close this.

In the next 2sxc it will show more warnings for such a scenario.

**Closed by iJungleboy** 2024-12-04 12:24 UTC
