### ISSUE TITLE
Bug in item picker (v17.06.00)

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#3339] opened 2024-04-01 16:19 UTC
### I'm submitting a

[x] bug report => search github for a similar issue before submitting

### ...about

[x] edit experience / UI
[x] admin experience UI

### Current Behavior / Expected Behavior

For content types that include entities as fields, the Entity/Item picker is empty. If for the picker, I reference a Query-based entity/item picker, everything works as expected.

In a previous version (v17.04.00 or 17.05.00? - I can't remember which), the Entity/Item Picker or the Query-based picker worked as I expected.

This is not a deal breaker. Since I can use a query, I can always make things work but I want to make sure that this is intended behaviour.

### Instructions to Reproduce the Problem

I created two simple apps:

- TestData - has a entity/item-based picker
- TestQuery - has a query-based picker

For both apps, there is a content type called "EyeColour".
<img width="732" alt="Screenshot 2024-04-01 120125" src="https://github.com/2sic/2sxc/assets/3846223/ef958aa8-3058-4d06-a953-9467a247de72">

Both apps, also have a content type called "Person" with the fields "Name" (a string) and "Eyes" (an entity). 
<img width="731" alt="Screenshot 2024-04-01 120559" src="https://github.com/2sic/2sxc/assets/3846223/aa76f287-d270-46b8-a2a4-364da6b11d01">

For the TestData app, I used an Entity/Item picker and pointed it to the EyeColour data:
<img width="729" alt="Screenshot 2024-04-01 120738" src="https://github.com/2sic/2sxc/assets/3846223/109461cb-b630-44a0-9f40-61b9cc3a3431">

For the TestQuery app, I created a query of the eye colours and pointed the picker to that query:
<img width="733" alt="Screenshot 2024-04-01 121109" src="https://github.com/2sic/2sxc/assets/3846223/dc54d14b-6b07-4fa1-a6e8-7228fe46968f">

When I go to add data, that's when I run into trouble with the TestData app - the dropdown for eye colours is empty:
<img width="601" alt="Screenshot 2024-04-01 121221" src="https://github.com/2sic/2sxc/assets/3846223/f5a64a51-d325-47ab-8294-86eca249a313">

On the other hand, the TestQuery app works as I expected:
<img width="667" alt="Screenshot 2024-04-01 121430" src="https://github.com/2sic/2sxc/assets/3846223/fbc517d2-2227-4e60-8b0f-5115d09b1976">

I believe that both approaches should work (entity/item picker vs. query picker) but I may be misunderstanding something.

### Your environment

* **2sxc version(s):** 17.06.00
* **Browser:** all 
* **DNN:** 9.13.03
* **Hosting platform:** IIS
* **Language:** English (I have not tested other languages)

**Comment by iJungleboy** [comment] 2024-04-02 20:44
Found the root cause, it was app-opened-through-other app.

Fixed in 17.06.01

**Closed by iJungleboy** 2024-04-02 20:44 UTC
Labels: affects:LTS
