### ISSUE TITLE
Multi language not working in versioning

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/2sxc#1229] opened 2017-07-08 09:28 UTC
Using 9.3, installed on DNN 8.0.4
Chrome, Surface pro3

Using the content (basis content - image + text) app, I activated US language. Dutch was already activated.
Then tried to translate the titel, content and image.
This resulted in the error attached

![schermopname_ 99](https://user-images.githubusercontent.com/9091997/27984235-9463d02e-63d0-11e7-9702-56276e4eac4c.png)

I also tried editing just the titel. Same result. After closing the dialogue, you'll see that nothing has been translated

I tried this with default DNN settings and also with 'content localization turned on'

**Comment by iJungleboy** [comment] 2017-07-08 09:44
thanks! this seems to be a real issue

**Comment by iJungleboy** [comment] 2017-07-08 10:18
My guess (not confirmed) is that the original record has "no language" assigned to the data, and that something goes wrong when the second language is added - which requires that the original data has the "primary language" assigned. i'll look into it right after my vacation.

**Comment by iJungleboy** [comment] 2017-08-09 13:01
I tried reproducing your scenario and cannot. It might be fixed automatically through other changes we applied to the latest edition. I'll release 2sxc 9.3 now but please re-test this. If it still fails, contact me at info 2sxc org so I can do some remote support. thx!

**Closed by iJungleboy** 2017-08-09 13:01 UTC
