### ISSUE TITLE
I'm getting a Content Decoding Error when using the image manager for 2sxc module

### ISSUE THREAD

**Issue by SamuelHadsall** [2sic/2sxc#1722] opened 2019-04-23 15:46 UTC
**I'm submitting a ...** 
[x] bug report

**...about**
[x] admin experience UI

**Current behavior**
Images in the image manager when editing an item are showing as broken images. It looks to be an issue with the **ImageResizer** on my install. If I remove the `[w h mode="crop"]`, the image will display. If I look in the dev console when pulling up the image manager I get `Failed to load resource: net::ERR_CONTENT_DECODING_FAILED`.

I upgraded to the latest version of 2sxc on client staging site and I am able to reproduce same issue.

**Expected behavior**
Images in the image manager should display with no issues when using **ImageResizer**

**Minimal reproduction of the problem with instructions**
Screencast link:
https://www.dropbox.com/s/wj2hb9yh5xxf548/ASCC-Broken-Images-2019-04-23_10-25-24.MP4?dl=0

**Please tell us about your environment:**
Windows Server 2012 R2
IIS 8

* **2sxc version(s):** 9.4.1 Production
* **2sxc version(s):** 9.42.0 Staging (Reproduced with latest install version)
* **Browser:** [all]
* **DNN:** [7.4.2] 
* **Language:** [any/all ]

**Comment by iJungleboy** [comment] 2019-04-23 16:05
This is a support question, so best kept on StackOverflow until proven to be a 2sxc issue. I've answered what I believe it to be the cause, let's continue the discussion there. Will close this for now.

**Closed by iJungleboy** 2019-04-23 16:05 UTC
