### ISSUE TITLE
App.Data["EntityType"].List doesn't return any data after delete operation within the same request.

### ISSUE THREAD

**Issue by NetLS-LLC** [2sic/2sxc#2865] opened 2022-10-05 09:05 UTC
**I'm submitting a ...**   
[x] bug report

**...about**   
[x] Razor templating
[x] Content Types or data management

**Current behavior**   
If you delete entity programmatically you can't get the rest of entities that were not deleted till the end of the request.

**Expected behavior**   
I should be able to get entities that were not deleted.

**Instructions to Reproduce the Problem**
1. Create few entity objects (for instance 4 instances of entity of type "DebugEntity")
2. Add this code to your page:
    <p>@App.Data["DebugEntity"].List.Count()</p>
    App.Data.Delete(1234); // add here one of entityIds from those you've created previously
    <p>@App.Data["DebugEntity"].List.Count()</p>
4. Open your page and you'll get this output:
    4
    0

Note: timeout between 2-nd and 3-rd lines of the code doesn't change anything. No data till the end of current request.
5. Go to app settings (don't reload page second time) and check your entities in the Data tab - you'll see that there are 3 of them.

**Why change the behavior?**  
I want to sync app data with external source. At first I'm deleting data that was saved in 2sxc app previously but doesn't exist remotely any more. Then I'm creating missing data. Then I'm updating data that exists but was changed at remote source.
Because of current bug if anything is deleted there are duplicates created for everything.
I'm currently moving delete method in the end of this methods sequence (will test it after), so I think it should work for now, but this behaviour is still not good and is going to cause some problems.

**Your environment**  

* **2sxc version(s):** 14.7.3 (currently latest LTS version)
* **Browser:** [Chrome Version 106.0.5249.91 (Official Build) (64-bit)]
* **DNN:** [9.10.02 ] 
* **Language:** [English]

**Anything you would like to add**

**Comment by iJungleboy** [comment] 2022-10-05 09:58
thanks for this, we'll look into it. 

I assume it's some caching at some level. AFAIK adding an item works - and it's already in the list, but delete just seems to skip something which would provide the correct list again...

**Comment by iJungleboy** [comment] 2022-10-25 10:48
This takes a while just to setup the test. 

Can you share a sample app so we can reproduce it quickly and fix? Otherwise we cannot prioritize this, because it takes too much of our (freely given) resources. thx ;)

**Comment by iJungleboy** [comment] 2022-11-04 08:01
Have not received a sample for 10 days, will close for now. If a sample is added, we'll reopen.

**Comment by Constantine-Ketskalo** [comment] 2022-11-04 11:26
> Have not received a sample for 10 days, will close for now. If a sample is added, we'll reopen.

[2sxcApp_DebugApp_0.0.13_withPageContent_2022-11-04T1324.zip](https://github.com/2sic/2sxc/files/9937728/2sxcApp_DebugApp_0.0.13_withPageContent_2022-11-04T1324.zip)

**Comment by iJungleboy** [comment] 2022-11-04 11:30
thx :)

**Comment by iJungleboy** [comment] 2023-03-22 16:21
We were able to reproduce this and have a solution. We're just checking some alternatives as well...

**Comment by iJungleboy** [comment] 2023-03-27 11:19
Is fixed in 15.05/15.06

**Closed by iJungleboy** 2023-03-27 11:19 UTC
