### ISSUE TITLE
Re-Add the X-button to edit-template and catch close-click outside of dialog

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#586] opened 2016-01-19 07:49 UTC
I would expect a save button which saves content and closes editor. 
Instead there are two "save and continue" buttons.
I am also missing a cancel (x) button in the upper right corner.

**Comment by iJungleboy** [comment] 2016-01-19 17:19
Since the editor opens in a new window, this is by design. We believe that most users want to try something - and they want to undo it if it fails / errors. This is only possible, if the window is still open, that's why we try to help them not close it. 

Do you have a better implementatio idea?

**Comment by iJungleboy** [comment] 2016-01-20 06:47
In beta 4 I now 

1. Added Ctrl+S support
2. Removed the second (not working) save button

**Comment by SCullman** [comment] 2016-01-20 07:37
I understand that you can undo only if the editor is still open. However, for serious changes you should use a serious editor anyway, either by opening the file directly from file system or by  copy/paste from browser window.
For me, this implementation looks strange. It is even not a new browser window, it is a  modal dialog, not different from a content editor.

So if I want to try something, I still need to open a second browser window to refresh the content.

Otherwise it just let me feel stupid, as now I need to click outside the window to close it and to review my changes.

I suggest to move the editor to a real browser popup instead of a dialog. otherwise please bring back the buttons and simply make  "Save and continue" primary.

**Comment by iJungleboy** [comment] 2016-01-20 07:43
This is a caching problem because we're not increasing the js version in the beta. do a ctrl+f5 on the initial page - now the code editor opens in a new window. 

We introduced it exactly because it's for quick changes - there is a very high risk of something breaking, and undo is very important then. But do the Ctrl+f5 (in the DNN page) and the experience will improve dramatically :)

**Comment by SCullman** [comment] 2016-01-20 08:11
Crt+F5, or deleting cache didn#t work in FF, Chrome or IE. No changes here :-(

**Comment by iJungleboy** [comment] 2016-01-20 08:13
you're using Beta 4

and you did the ctrl+f5 on the DNN-page (with the the green code-button), NOT the editor-page?

**Comment by SCullman** [comment] 2016-01-20 08:24
Sorry, I opened it with module actions, it is one click less.
If I open it with the green button, the dialog opens in a new blank tab over an empty page.

Why it is is still an dialog then? I can even click beside the editor and it will ask me whether I will really close it. If I do, I will have a white empty page.

**Comment by iJungleboy** [comment] 2016-01-20 08:26
This is simply not perfected yet. I guess that click should ask, and if you click ok, it would have to close the window; or it should ignore it...

**Comment by SCullman** [comment] 2016-01-20 11:27
Yes, that's how it works, similar to all other dialogs in 2sxc.

**Closed** 2016-01-21 06:35 UTC
