### ISSUE TITLE
Fresh install of 14.03 doesn't allow install of Content or Apps

### ISSUE THREAD

**Issue by gfrater** [2sic/2sxc#2802] opened 2022-06-29 11:36 UTC
**I'm submitting a ...** 
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**  
Adding a 2SXC Content module to a page on a new site and the icon shows but there's no dialogue to install the starter content blocks. There is an empty iFrame at the bottom of the page:

<iframe src="/desktopmodules/tosic_sexycontent/dist/quickDialog/?pageId=21&amp;sxcver=14.3.0.1656500480#zoneId=2&amp;appId=2&amp;mid=384&amp;cbid=384&amp;partOfPage=true&amp;publishing=DraftOptional&amp;dialog=layout&amp;items=%5B%5D" style="min-height: 225px; height: 0px;"></iframe>

Clicking on the Manage Apps button also produces and empty iframe:

<iframe allowtransparency="true" style="top: 0;left: 0;width: 100%;height: 100%;" src="/desktopmodules/tosic_sexycontent/dist/ng-edit/?pageId=21&amp;sxcver=14.3.0.1656502234#zoneId=2&amp;appId=2&amp;mid=384&amp;cbid=384&amp;partOfPage=false&amp;dialog=zone&amp;items=%5B%5D"></iframe>

**Expected behavior**   
On adding a 2SXC Content module to a page for the first time (on a brand new install) the install content types window should show. Clicking on the Manage Apps button should also bring up the manage apps dialogue.

**Instructions to Reproduce the Problem**
Install DNN 9.10.2, install 2SXC 14.03, add 2SXC Content or 2SXC App module to a page.

**Why change the behavior?** 
Appears to be a bug

**Your environment**  
Windows Server 2012R2, .Net 4.8, SQL, SQL 2012 (Web)

* **2sxc version(s):** 14.03.00
* **Browser:** all
* **DNN:** 9.10.2 
* **Language:** English

**Anything you would like to add**

**Comment by iJungleboy** [comment] 2022-06-29 11:40
let me check...

**Comment by iJungleboy** [comment] 2022-06-29 11:50
hi @gfrater I cannot reproduce the issue. 

It seems that your quick-dialog is stuck, it's located in the folder `/desktopmodules/tosic_sexycontent/dist/quickDialog/`

Could you check
1. That the folder exists
2. That it has a default.aspx in it
3. that it has an index-raw.html
4. Do you get a 404 or just a white page?

**Comment by gfrater** [comment] 2022-06-29 11:54
This folders and files are all in place (and have correct permissions for the app-pool), if I go to http://sictest.unitedlearningcms.org.uk/desktopmodules/tosic_sexycontent/dist/quickDialog/?pageId=21&sxcver=14.3.0.1656502234#zoneId=2&appId=2&mid=384&cbid=384&partOfPage=true&publishing=DraftOptional&dialog=layout&items=%5B%5D I get an empty page (no source)

**Comment by iJungleboy** [comment] 2022-06-29 13:29
I can't explain what the reason is, and nobody else reported this. 

I'll close this issue as it's probably not relevant for others. Feel free to continue posting your findings and I'll try to answer them. 

Can you check the event log on DNN to see if any error appears?

Could you manually modify the default.aspx and put some test-tags there to see if they come through?

**Comment by gfrater** [comment] 2022-06-29 16:07
Thanks, after a bit of experimentation the iFrame URL works if I add default.aspx to the URL:

http://sictest.unitedlearningcms.org.uk/desktopmodules/tosic_sexycontent/dist/quickDialog/default.aspx?pageId=21&sxcver=14.3.0.1656518519#zoneId=2&appId=2&mid=384&cbid=384&partOfPage=true&publishing=DraftOptional&dialog=layout&items=%5B%5D

so it's a server setup issue which I can look into.

Thank you for your time.

**Closed** 2022-06-30 13:52 UTC
