### ISSUE TITLE
Preview pictures for templates are missing 

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#1928] opened 2019-12-12 10:33 UTC
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] admin experience UI

**Current behavior**

![image](https://user-images.githubusercontent.com/5693190/70704606-9c58da00-1cd2-11ea-91c3-d305a9762cb9.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/5693190/70704656-c01c2000-1cd2-11ea-85e0-3454b3458777.png)

**Minimal reproduction of the problem with instructions**

templates and pictures are in host folder (Portals/_default )

The path to the image still has a tilde. If it is removed, pictures appear.
![image](https://user-images.githubusercontent.com/5693190/70704843-1d17d600-1cd3-11ea-966c-548feb43646f.png)

* **2sxc version(s):** 10.20.05
* **DNN: 8.X.X

**Comment by iJungleboy** [comment] 2019-12-12 11:07
This is odd, I cannot reproduce it. maybe it's fixed in newer versions. Please check, we'll release 10.22 today or tomorrow. I'll close for now, but if it still appears in later versions please ping again.

**Comment by SCullman** [comment] 2019-12-12 12:06
I can reproduce also in DNN 9.4.4 and 2sxc 10.21.0
@daniel, did you test with templates located in **_host file system_**? 

## Steps to reproduce

1. Starting point: dnn + 2sxc + default content package.
1. add template "Person", "without picture
2. copy ~/portals/0/2sxc to ~/portals/_default/2sxc
3. Change all locations for the person templates to the host file system.
4. Switch to a differnt template
![image](https://user-images.githubusercontent.com/5693190/70710657-f4e2a400-1cdf-11ea-8dcd-ecab660799e5.png)

**Comment by iJungleboy** [comment] 2019-12-12 14:44
@SCullman thx for that additional info - could be the cause. I'll reopen.

**Comment by iJungleboy** [comment] 2019-12-12 15:13
fixed, will be in 10.22

**Closed by iJungleboy** 2019-12-12 15:13 UTC

**Comment by SCullman** [comment] 2019-12-13 12:05
Works perfect, thank you.
