### ISSUE TITLE
BUG: Unable to Drag & Drop Multiple Files into Library Field

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#1813] opened 2019-09-18 18:25 UTC
**I'm submitting a ...**
[x] bug report => search github for a similar issue before submitting 

**...about**
[x] edit experience / UI

**Current behavior**
Editing an item with a library of files, drag-and-drop with multiple files doesn't work. It does work however one-by-one.

**Expected behavior**
Dragging in multiple files at once should import them all.

**Minimal reproduction of the problem with instructions**
Create a new data type with a hyperlink field and set it to library. Add a new item and try and drag in multiple files into the section that says, "drop files here". Notice it also doesn't work if you click in the box and try to drag them onto the ADAM icon.

**What is the motivation / use case for changing the behavior?**
This behavior used to work in previous versions.

**Please tell us about your environment:**
Windows 10 Pro

* **2sxc version(s):** 10.05.00
* **Browser:** Chrome 73 & Firefox 69
* **DNN:** 09.03.02
* **Language:** English

**Comment by Accuraty** [comment] 2019-09-18 18:28
I can confirm, having the same problem. Using the Blueimp Gallery app. Works fine when you switch back to the old UI.

**Comment by iJungleboy** [comment] 2019-09-19 05:46
Thanks for this, @PagnoDunadan will look into this asap 👍

**Comment by PagnoDunadan** [comment] 2019-09-19 07:44
Fixed in next version.

**Closed** 2019-09-19 08:41 UTC

**Comment by tpperlman** [comment] 2019-09-20 21:21
I have to piggy back on this issue to note that there may be an additional issue.

I have the library marked as a required field, and even when I drag in files it will not allow me to save, saying, "To save the form, please fix the following errors: Images: required"

**Comment by iJungleboy** [comment] 2019-09-23 06:47
@tpperlman better never piggyback on issues, because of separation-of-concerns :)
