### ISSUE TITLE
v17 Breaking change - Permissions to read entity not working anymore

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3288] opened 2024-02-11 22:09 UTC
### I'm submitting a
[x] bug report 

### ...about
[x] Content Types or data management

### Current Behavior / Expected Behavior
Previously working apps now return 401 when accessing an entity data type within the form.
Here's what I've double checked:

Feature enabled:
![image](https://github.com/2sic/2sxc/assets/26518879/5ba33a4e-9083-4c5c-a351-e6de785e2214)

Role is assigned to users.
Role ID is confirmed in database.

Permission to the data type is defined as bellow:
![image](https://github.com/2sic/2sxc/assets/26518879/852d7456-68af-482c-9d6e-590dd37738cf)

Permission to create and read only (no edit)
![image](https://github.com/2sic/2sxc/assets/26518879/d5b9aeb0-6c41-4c9e-841d-998cff182496)

Another entity type has a field that links to the previous one:
![image](https://github.com/2sic/2sxc/assets/26518879/1e667c8f-2cfe-4ecf-aaf2-97497f935d22)

When I open the form and try to read the items from the first data type, I get:
![image](https://github.com/2sic/2sxc/assets/26518879/f63637dc-fc1f-42da-a7de-a556198ac02f)

### Your environment

* **2sxc version(s):** 17.1.6
* **Browser:** all

**Comment by iJungleboy** [comment] 2024-02-12 06:52
I'm a bit confused, but I also think it's probably not a permission issue.

We did change the mechanics behind the entity-picker, so maybe there is something wrong there.

What user are you using which throws the error? a system-admin (host) or a admin or what?

**Comment by iJungleboy** [comment] 2024-02-12 07:00
...but I did also try with a restricted user and can't reproduce. can you maybe provide more details incl. the hidden infos you had there? Maybe mail it to info...

**Comment by enfJoao** [comment] 2024-02-12 08:35
Normal user opening the form with public forms.

The hidden info is only field names. Nothing relevant.

**Comment by enfJoao** [comment] 2024-02-12 09:16
I've created a simple demo that recreates the issue.

[2sxcApp_Demo401_0.0.17.zip](https://github.com/2sic/2sxc/files/14236654/2sxcApp_Demo401_0.0.17.zip)

May be specific to public forms.

If I click the button with no permissions set, I get a 403 an the form does not work.
If I give group permissions to the form associated data ("Mainformdata"), the form opens and I can edit and save (so public forms work and group permissions also work).
No matter the permissions I set to the nested "Datafeed" data type, it will always return 401 to public users.

![image](https://github.com/2sic/2sxc/assets/26518879/d3a0c437-120a-4ea1-a608-a8a84dd936e2)

![image](https://github.com/2sic/2sxc/assets/26518879/e47f11fa-2120-409a-9b7a-8e993eb255b8)

![image](https://github.com/2sic/2sxc/assets/26518879/6f8fc141-8a6e-469d-bccf-0871b81c7d1f)

![image](https://github.com/2sic/2sxc/assets/26518879/87e2a561-c1fa-4669-8283-9748c9f4582b)

**Comment by iJungleboy** [comment] 2024-02-12 09:47
Thanks, this really helps.

**Comment by iJungleboy** [comment] 2024-02-12 12:35
Should be fixed in v17.01.08

**Closed by iJungleboy** 2024-02-12 12:35 UTC

**Comment by enfJoao** [comment] 2024-02-15 11:12
Could I ask for a release to fix this issue? I have a couple apps stalled due to this error and I really want to avoid restoring this site.

**Comment by iJungleboy** [comment] 2024-02-16 05:31
Sure - that's what friends are for 😉

Here's a pre 17.01.08. I don't expect any problems, but if some do arise, you can always downgrade - no DB changes or anything. 

[ToSic.Sxc.Dnn.17.01.08_Install.zip](https://github.com/2sic/2sxc/files/14306241/ToSic.Sxc.Dnn.17.01.08_Install.zip)

**Comment by enfJoao** [comment] 2024-02-16 10:12
Awesome.

Thanks.
