### ISSUE TITLE
Entities with only numeric fields do not save records

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2046] opened 2020-04-19 12:57 UTC
**I'm submitting a ...** 
[x] bug report 

**...about** 
[x] admin experience UI
[x] Content Types or data management

This one took me a while to pinpoint, but here it goes.

**Minimal reproduction of the problem with instructions**
Create a new entity.
Add two fields to it, both numeric, with any names.
Try to add some content to it. Click save. Nothing will happen, no errors logged. Form is not closed, but you can proceed exiting and discarding.
Add a new string field and repeat. It will now save.

* **2sxc version(s):** 10.28
* **DNN:** [ 9.5 ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

**Comment by PagnoDunadan** [comment] 2020-04-19 13:27
Duplicate of #2024. New 2sxc release will contain the fix.

**Closed** 2020-04-19 13:27 UTC
