### ISSUE TITLE
Versioning text needs TLC / UI seems to not auto-fallback to EN

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/2sxc#1227] opened 2017-07-08 09:23 UTC
Installed 9.3 on 8.0.4
Tested on Surface Pro3

The text clashes here and there in the versioning section.

![schermopname_ 97 1](https://user-images.githubusercontent.com/9091997/27984207-e3d9c380-63cf-11e7-9d16-50a943f33905.png)

**Comment by iJungleboy** [comment] 2017-07-08 09:42
thanks - this is a UI language problem - seems the fallback to EN for labels is failing. thx!

**Comment by christophbuehler** [comment] 2017-07-18 14:46
Hi @Tychodewaard. I need some more information to reproduce this behavior. Please follow these instructions:
- Open the history dialog.
- Right-click anywhere on the dialog. A context menu will appear.
- Click on "View frame source". A new tab will open, showing the source code of the dialog.
- Copy the URL of this tab and post it here.

Thank you!

**Comment by iJungleboy** [comment] 2017-08-09 13:34
As we cannot reproduce and have no more feedback, we'll close this for now.

**Closed by iJungleboy** 2017-08-09 13:34 UTC
