### ISSUE TITLE
Duplicate Modules, can't change template layout

### ISSUE THREAD

**Issue by Bit-Hug-Tub** [2sic/2sxc#2518] opened 2021-09-14 15:56 UTC
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] DNN parts

**Current behavior**   
1. Adding an existing module seems to duplicate the content, where changing something in one module will auto-change it to the second module, at least when both modules are on the same page.
2. If I add a new "Content" module, and then afterwards if I click the pencil edit symbol and then click "Change Template / Layout", nothing appears

**Expected behavior**   
1. After adding an existing module on the same page as the source module, I want both modules to have different content, instead of one mirroring the other.
2. After adding a new "Content" module, I'd like to be able to choose the template / layout.

**Instructions to Reproduce the Problem**

The screenshot below details my issue 2 (add new content module, but can't choose what type it will become later). Clicking the bottom left squares that represent "add module" or "add existing module", and placing it on a page will bring up the 2 issues.
![image](https://user-images.githubusercontent.com/90710622/133289737-6bc79290-d465-49c9-8680-e2aee60a92e5.png)

**Why change the behavior?**  
There is a workaround, where I would create a new page and put whatever module content I want, but we won’t create pages every time we get a request to add a module to the same page.

My marketing team wanted a 2019 and 2020 version of the Student and Outstanding modules to exist on the same awards page. The workaround is just a separate page that has the 2019 info.

**Your environment**  Windows 10

* **2sxc version(s):** 10.20.02  
* **Browser:** Firefox, Chrome, Edge, most updated versions.
* **DNN:** v. 09.03.02 (24)
* **Language:** English

**Anything you would like to add**

**Comment by iJungleboy** [comment] 2021-09-14 19:18
Hi there ;)

So first of all, you seem to be using a fairly old version of 2sxc for which we cannot actively invest time to research an issue. 

BUT: Since we never heard of such an issue, I believe you are having one of a few possible problems:

1. Either the JS which controls edit-buttons is broken (try an upgrade) and/or another JS on the page is breaking it. You would probably see errors in F12 if this is the case. 
2. Alternately you may have a razor-file which explicitly selects predefined data, in which case the behavior would by by design. 

My guess is a JS issue - probably in the DNN (also an old version) or on the page/content which is causing trouble. 

Either way: Since this is not a support-channel (use StackOverflow for that) and you're describing an issue on an old 2sxc - and nobody else has ever reported such a problem, I'll close this issue for now. 

If it turns out to really be a 2sxc bug and also occurs on newer versions of 2sxc, please supply more information like the razor template and JS errors and we'll reopen this.

**Closed by iJungleboy** 2021-09-14 19:18 UTC
