### ISSUE TITLE
Admin UI breaks when placeholders with {{ or }} are used in data

### ISSUE THREAD

**Issue by tobias2sic** [2sic/2sxc#903] opened 2016-08-17 10:59 UTC
I have a content type with a field 'Description'. The description can have placeholders like {{{Test}}}. When this description is loaded in the 'Content / Data management' view, the view does not show all data items. It breaks after the first item having such a placeholder.

Error message in the browser console (see the attached screenshot).

**Comment by tobias2sic** [comment] 2016-08-17 10:59
![2016-08-17_12-51-47](https://cloud.githubusercontent.com/assets/6668437/17734117/79c7412a-647a-11e6-96ef-9d3490a3a348.png)

**Comment by raphael-m** [comment] 2016-08-26 07:08
Duplicate of #738

**Closed** 2016-08-26 09:21 UTC
