### ISSUE TITLE
FIPS issue with Encryption and possibly Image-Resizer

### ISSUE THREAD

**Issue by david-poindexter** [2sic/2sxc#2988] opened 2023-01-26 19:43 UTC
### I'm submitting a ...
[x] bug report
[x] not sure

### ...about
[x] admin experience UI
[x] APIs like REST
[x] other / unknown

### Current Behavior / Expected Behavior
Navigate to `Apps Management` > `System` tab.  The following pop-up is showing:

![image](https://user-images.githubusercontent.com/4568451/214928982-1041ed81-3d11-4dfc-80ac-e93197d33b3f.png)

It appears to be related to the `GetSystemInfo` API call 2sxc is making for that tab.

### Instructions to Reproduce the Problem
This could potentially be an environment/configuration issue with the site, but it appears 2sxc may be using non-FIPS-compliant encryption for the Web API call.

### Your environment**
In checking the `web.config`, we can confirm the following cryptography default provider:

```
    <cryptography defaultProvider="CoreCryptographyProvider">
      <providers>
        <clear />
        <add name="CoreCryptographyProvider" type="DotNetNuke.Services.Cryptography.CoreCryptographyProvider, DotNetNuke" providerPath="~\Providers\CryptographyProviders\CoreCryptographyProvider\" />
        <add name="FipsCompilanceCryptographyProvider" type="DotNetNuke.Services.Cryptography.FipsCompilanceCryptographyProvider, DotNetNuke" providerPath="~\Providers\CryptographyProviders\FipsCompilanceCryptographyProvider\" />
      </providers>
    </cryptography>
```

* **2sxc version(s):** 14.12.3
* **Browser:** all
* **DNN:** 9.8.1
* **Hosting platform:** IIS
* **Language:** English

**Comment by david-poindexter** [comment] 2023-01-27 01:57
By the way, changing the cryptography default provider to `FipsCompilanceCryptographyProvider` does not resolve the issue.

**Comment by iJungleboy** [comment] 2023-01-27 08:50
This is very strange, never heard of this and I can't imagine why it would only affect a single endpoint.

Basically it should affect all endpoints or none. 

Is there a way we could configure a server to reproduce this? I assume there is some global FIPS-enforcing setting or something?

Thanks,

**Comment by david-poindexter** [comment] 2023-01-27 14:01
@iJungleboy I'm am not confident that it only applies to one endpoint.  This is just the first one we noticed after installing 2sxc.

I did notice something else very odd.  When looking at the list of apps in Apps Management, the icons for Content and Primary and broken image links.  When attempting to access them directly via their URL, the stack trace shows for what appears to be the same FIPS error.  Looking on disk though, the images are there at the suspected path.

Interestingly enough, none of the other site images (displayed via skin or HTML module content) seem to result in the same behavior.  My thoughts go towards file/folder permissions but they appear to be correct.

I am stumped at this point, so any ideas are welcomed.

I personally do not have access to review server level configuration, so I wouldn't know how to reproduce.

**Comment by iJungleboy** [comment] 2023-01-27 14:48
So based on brief research this sounds like a registry setting on the server 😲
Never used it myself...
I'll try to see what we can do - maybe we're using some hashing algorithm that fires here. 

According to this article, you can disable FIPS rules in web.config - might help: https://blogs.iis.net/webtopics/parser-error-message-this-implementation-is-not-part-of-the-windows-platform-fips-validated-cryptographic-algorithms-when-net-page-has-debug-true

**Comment by iJungleboy** [comment] 2023-01-27 14:50
also mentioned here https://stackoverflow.com/questions/39374757/can-i-use-wpf-without-disabling-fips-compliance

**Comment by david-poindexter** [comment] 2023-01-27 14:59
@iJungleboy you are obviously much better at searching than I am - LOL.  🎉   I'm not sure if we'll be allowed to bypass FIPS via the `web.config`, but we have a test environment on which we can at least test this out to see if this works or not.  Thank you so much for the quick responses!

**Comment by david-poindexter** [comment] 2023-01-27 15:51
@iJungleboy okay, I may have tracked down one of the culprits.  See https://github.com/2sic/2sxc/blob/41c5033b0737d3809a20e1f117c4de002d4febd0/Src/Sxc/ToSic.Sxc/Services/Secrets/SecureDataService.cs#L39 where `BasicAesCryptography` is being used.  From a cursory search, it looks like this may not be FIPS compliant.

**Comment by iJungleboy** [comment] 2023-01-27 17:38
This is certainly a good insight.

Since it's currently just used with data which is encrypted internally (google API keys) it is probably fairly easy to fix
without impact to other users. 

Any idea which algorithms would be safe for a long time (so we don't use one which is ok today but blacklisted in a few months...)?

**Comment by david-poindexter** [comment] 2023-01-27 17:48
@iJungleboy it looks like there is a [list of algorithms here](https://learn.microsoft.com/en-us/windows/security/threat-protection/fips-140-validation#microsoft-fips-140-validated-cryptographic-modules).

**Comment by iJungleboy** [comment] 2023-01-28 10:55
@david-poindexter I found an insightful article here https://stackoverflow.com/questions/939040/when-will-c-sharp-aes-algorithm-be-fips-compliant

We're using `AesManaged` which seems to not be FIPS compliant, because apparently it would allow for other key sizes. 

Note that `BasicEasCryptography` is an EAV/2sxc class, but it used `AesManaged`. 

I was able to change the code to use `AesCryptoServiceProvider` which _should_ be FIPS compliant. 
This may fix the problem, but I'll need you to verify it. 
It's also possible that there is other code that is still not FIPs.

Pls test 15.01 soon on such a hardened system to verify.

**Comment by david-poindexter** [comment] 2023-01-29 03:42
@iJungleboy thank you so much!

Unfortunately, we will not be able to test anything for v15 in this environment until there is an LTS published and 2sxc v15.x has been approved for use.  There is a strict approval process for application use and it is by version.  Right now we are approved for use 14.12.xx.  (By the way, I'm not sure where I would even be able to find 15.01 since it was in Releases/Tags.  I will double-check to see if we can use a test environment for testing, but I am not hopeful since v15 has not gone through the review/approval process.)

**Comment by iJungleboy** [comment] 2023-01-30 15:53
@david-poindexter I just did a lot more 😉

I can't really verify it, but I'm 99% sure it's rock-solid now. 

Will close as it will be in release 15.01 - but please do test and verify. thx!

**Comment by david-poindexter** [comment] 2023-01-30 17:55
@iJungleboy I really wish you wouldn't close the issue.  I do not believe we have found all the pieces to this puzzle just yet.

1. We tried implementing this (https://learn.microsoft.com/en-us/archive/blogs/shawnfa/disabling-the-fips-algorithm-check) in the `web.config`.  It, unfortunately, did not change the behavior at all.  We still receive the FIPS errors.

![image](https://user-images.githubusercontent.com/4568451/215554209-ba7388d8-de15-41b9-a43a-ea619fb365ce.png)

2. App icons do not load.

![image](https://user-images.githubusercontent.com/4568451/215554023-d3e43f2f-e32f-4dc7-ada7-159ef8fe89d8.png)

Here is the detailed stack trace when attempting to access the images directly (using the same URL w/ params):

![Load-Images-with-Params-Fail-(20230130)](https://user-images.githubusercontent.com/4568451/215554572-aefca366-3a5b-4dfe-a60a-f7e0e65c60b1.jpg)

When we remove the params, the image loads just fine:

![Load-Images-without-Params-Do-NOT-Fail-(20230130)](https://user-images.githubusercontent.com/4568451/215554677-9a1e3450-4f83-4ea1-a7d3-9a5ae084a799.jpg)

This leads us to believe there are also encryption related issues with the image processor.

3. Regarding v15.1, I appreciate that you are rolling the fixes into that release, but this will not help us.  As I mentioned before, we cannot seek approval for the installation of 2sxc v15 until there is an LTS release.  Do you not plan to release these fixes in a v14.x.x LTS?  If not, this is incredibly unfortunate and I (again) fail to see the purpose of LTS at all!  Furthermore, trying to explain this to clients is becoming incredibly difficult.

**Comment by iJungleboy** [comment] 2023-01-31 09:45
@david-poindexter Thanks for the discovery with the image resizer.

The resizer (ImageFlow) It's a third party extension, so I'm not sure how fast we can make anything happen there. I'll try to contact her.

In terms of LTS: FIPS has never been on our radar and now that it is, we do wish to support it. But our LTS policy doesn't cover never-supported features - even if we both agree that FIPS is something we should look into. See https://docs.2sxc.org/abyss/releases/management/policy-lts.html

Note also that there are a few FIPS settings in the web.config according to my research. I don't know the details but I'm pretty sure you can actually disable them.

I'll reopen this for now and try to follow up with ImageFlow.

**Comment by iJungleboy** [comment] 2023-01-31 09:57
Opened Issue on ImageFlow with sufficient Detail to get reasonable feedback.

**Comment by iJungleboy** [comment] 2023-01-31 12:12
Just a side-note, lilith posted this link which is quite revelant (it's a blog post from Microsoft):
https://techcommunity.microsoft.com/t5/microsoft-security-baselines/why-we-amp-8217-re-not-recommending-amp-8220-fips-mode-amp-8221/ba-p/701037

In https://github.com/imazen/imageflow-dotnet-server/issues/71
she also notes that she's probably ok with the changes, but does clearly imply that anybody who need/wants this done in the near future should submit a PR. 

We from the 2sxc team don't have a FIPS need ourselves, so we won't be pushing forward on this since it doesn't affect us and was never a feature in 2sxc. 

So I see a few options:

1. Either you or the customer submit PRs to imageflow
2. You check alternatives - maybe ImageResizer (which has a compatible URL schema but doesn't support WebP etc.) could be used
3. Your customer could sponsor us to get this done - my estimate is that with everything incl. verifying performance etc. it can easily be 2-3 days of work
4. Your customer turns off FIPS

For the public I feel that this issue is not relevant any more, @david-poindexter and @iJungleboy will get updates as we chat here. But from the point of view of 2sxc it won't get any more resources, so for the public I'll close this task as completed.

**Closed by iJungleboy** 2023-01-31 12:12 UTC
Labels: waiting-for-input

**Comment by david-poindexter** [comment] 2023-01-31 21:42
@iJungleboy you are welcome for the image resizer discovery.  Thanks for opening an issue on the `imageflow` repo.  Being totally unfamiliar with that project, I'm not sure if we would be able to submit a PR for it or not.  The odd part is `SHA1Manged` is just being used for hash computation.  If this is the only area of the code base that is causing the FIPS-related issue, I am confused as to why it would two 2-3 days of work to implement a fix.  Without this, we simply wouldn't be able to use `imageflow` capabilities within 2sxc (which is an option, but not ideal of course).  We would be happy to contribute (beyond our current sponsorship) but just not for 2-3 days of effort.  That seems a bit heavy for such a seemingly small change (though I could be totally naive about this).

I am familiar with your LTS policy - I just don't think it is ultimately the "right" approach.  I would much rather see no use of the term "LTS" with releases because it causes HUGE problems optically with clients and has such negative ramifications on projects when a "fix" is not available until a future major version.  Yes, I do understand FIPS was not something that was officially supported before, so we are super appreciative of the desire to support it moving forward.  Unfortunately, placing it in v15 instead of the current LTS causes a huge issue.  The client cannot just upgrade to v15 and v14 simply doesn't work.  So all the plans for this project to use structured content are out the window or significantly delayed until an approval process can be completed for v15 (which may not even be possible until a v15 LTS is released, which is currently unknown, and thus we come full circle back to the fundamental flaw with having an "LTS" to start with).

Sorry for the rant.  I don't want to come across as unappreciative at all.  I just wish there was a way forward that would help mitigate these conundrums that are coming about way too often.

**Comment by david-poindexter** [comment] 2023-01-31 23:14
@iJungleboy I have some GREAT news for you all.  We were able to test v15.01.00 on a non-production server and the FIPS errors related to 2sxc specific features have now gone away.  We'll let you know if we run into any related issues, but this is fantastic.  Fingers crossed that we'll be able to get to a v15 LTS sooner rather than later for the client internal review/approval process for production extension use.

**Comment by iJungleboy** [comment] 2023-02-01 07:56
This is awesome news!
Thanks for verifying it!

We'll try to get the LTS out in 2-3 weeks - just need to finish some quite amazing new features ;)

**Comment by david-poindexter** [comment] 2023-02-01 21:18
@iJungleboy we have run into several other bugs with v15.1, but so far the only area that is still breaking regarding FIPS is related to any images used within the 2sxc core UI.  They are all showing as broken images due to the use of ImageFlow in the core UI.

**Comment by iJungleboy** [comment] 2023-02-02 12:52
As a fallback you could try to use ImageResizer instead - but I'm pretty sure that will have the same FIPS problems.

**Comment by iJungleboy** [comment] 2023-02-02 16:21
You would basically disable the web.config settings for ImageFlow and install the ImageResizer package https://github.com/2sic/dnn-imazen-imageresizer

I believe the release there is not up to date, but it would at least be ok for a test.

**Comment by david-poindexter** [comment] 2023-02-02 17:32
> You would basically disable the web.config settings for ImageFlow and install the ImageResizer package https://github.com/2sic/dnn-imazen-imageresizer
> 
> I believe the release there is not up to date, but it would at least be ok for a test.

Thank you!
