### ISSUE TITLE
Partial App export of the templates does not work 

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#461] opened 2015-11-23 18:20 UTC
Below is the XML file I get when trying to export only templates. Nothing about templates in there.
Note that the final closing '>' is missing on all partial exports.

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<SexyContent FileVersion="07.00.00" MinimumRequiredVersion="07.00.00" ModuleVersion="08.00.05" ExportDate="2015-11-23T18:49:07.6393151+01:00">
  <Header>
    <Language Default="fr-FR" />
    <Dimensions>
      <Dimension DimensionID="3" Name="Français (France)" SystemKey="" ExternalKey="fr-FR" Active="true" />
      <Dimension DimensionID="4" Name="English (United States)" SystemKey="" ExternalKey="en-US" Active="true" />
    </Dimensions>
  </Header>
  <AttributeSets />
  <Entities />
  <PortalFiles />
</SexyContent

**Comment by BravoSierra** [comment] 2015-11-23 18:21
<SexyContent FileVersion="07.00.00" MinimumRequiredVersion="07.00.00" ModuleVersion="08.00.05" ExportDate="2015-11-23T18:49:07.6393151+01:00">
  <Header>
    <Language Default="fr-FR" />
    <Dimensions>
      <Dimension DimensionID="3" Name="Français (France)" SystemKey="" ExternalKey="fr-FR" Active="true" />
      <Dimension DimensionID="4" Name="English (United States)" SystemKey="" ExternalKey="en-US" Active="true" />
    </Dimensions>
  </Header>
  <AttributeSets />
  <Entities />
  <PortalFiles />
</SexyContent

**Comment by raphael-m** [comment] 2015-12-01 15:36
Duplicate of #452

**Closed by raphael-m** 2015-12-01 15:36 UTC
Labels: try-to-reproduce
