### ISSUE TITLE
[Feature request] Add entity list and content fields to snippets

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1596] opened 2018-07-17 11:19 UTC
**I'm submitting a ...**
[x] feature request

**...about**
[x] edit experience / UI

**Current behavior**
If using content mode, in the current view file edit, 2sxc editor shows the fields for the set entity. If you change file, content does not update to the view.

**Expected behavior**
Editor could show the full list of entities and fields for the entire app, even in data mode, and in all files.

**What is the motivation / use case for changing the behavior?**
I use data mode for nearly all my projects. And it is a pain to always go back and forward checking entities names (for App.Data("entity")) and field names (for everything).
A new snipped group called "Entities and fields" could hold all the info needed in one place, grouped and ordered.

**Comment by Accuraty** [comment] 2018-07-17 13:55
This is a really GREAT request. Very useful and needed!! Thank you!!

**Comment by iJungleboy** [comment] 2018-08-09 21:10
I believe this is a duplicate of #905 - just haven't found time for this yet. 
As we're focusing all our efforts ATM on 2sxc 10 with the way faster Angular 6 UI, we won't be able to address this in 2018. So if someone want's to contribute/sponsor...

**Comment by eXistenZe** [comment] 2019-04-27 18:20
Hey.

I'm gonna be that ungrateful guy who uses free software and still asks for new and new features, but could your awesome team find some time to implement this on 2sxc 10? It would make lives so much better :)

**Comment by iJungleboy** [comment] 2019-04-28 14:06
@eXistenZe it just needs a contribution :)
But note that the new UI will remade completely, so better wait till that's ready, otherwise you'll have to do it again.

**Comment by eXistenZe** [comment] 2019-04-28 14:38
I have a native inclination to contribute with ideas... Not very good with
actual coding...

**Comment by iJungleboy** [comment] 2020-06-12 14:02
Needs sponsoring, so added to #2107 and will close unless someone contributes or sponsors this.

**Closed by iJungleboy** 2020-06-12 14:02 UTC
Labels: needs contribution or sponsoring, wait4ng8ui
