### ISSUE TITLE
Error installing a clean 2sxc module into an empty Octane project on MacOS

### ISSUE THREAD

**Issue by kvgros2** [2sic/2sxc#3508] opened 2024-11-14 17:37 UTC
### Current Behavior / Expected Behavior

Error loading 2sxc into a clean install of Oqtane using MacOS and Rider as the IDE.  Have .NET 9.0 (and 8.0) installed.

Installed the most current version of Oqtane (5.2.4).  Built and ran and configured a SQL Server database.  Everything works as expected and application loads, admin account is created, able to log in as admin.

Followed the instructions to install 2sxc and it downloads correctly and I am prompted to restart.   During the restart the debugger disconnects (as expected) and I re-run.   On the next run an exception is thrown on startup.Configure() in the loop here:

            foreach (var startup in startUps)
            {
                startup.Configure(app, env);
            }

The exception is related to being unable

System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Caching, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

Cannot seem to get passed that point and have tried starting from scratch a few times.   Able to get this far with no changes to any of the code or references.  Just following the setup instructions for the current versions.

### Your environment
MacOS (Sequoia)
Rider

* **2sxc version(s):** 18.03
* **Browser:** all 
* **Oqtane:** 5.2.4
* **Hosting platform:** all
* **Language:** any/all

**Comment by iJungleboy** [comment] 2024-11-15 08:13
Thanks.
The caching issue appeared for Oqtane 6, we were not aware that it may also affect Oqtane 5.2.4.

Must be a difference in the Entity-Framework (that's the root cause in Oqtane 6).

we plan to release another 2sxc today or early next week fixing this.

**Comment by iJungleboy** [comment] 2024-11-18 07:59
Just released 18.04, should be fixed.

**Closed by iJungleboy** 2024-11-18 07:59 UTC
