### ISSUE TITLE
Duplicate Scope: Default When Installing New Apps

### ISSUE THREAD

**Issue by jtherrien-accuraty** [2sic/2sxc#2652] opened 2022-02-01 21:19 UTC
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] Content Types or data management

**Current behavior**   
I have tested this with Mobius Forms 5.3.2, Mobius Forms 5.3.1, and CTA 3.1.1 as well as with a custom app I made for 2sxc v12.8.1 on both a production server and local testing site hosted on my Windows 10 computer. When I install one of the hybrid versions of an app it installs successfully, but when I go into the data section it is blank. There is a 2nd "Scope: Default" that appears in the dropdown menu, and selecting that reveals all of the content types you would expect to see. I can successfully add the app to a page and configure it, and the new entity shows up in this 2nd Scope: Default. If you go to the view settings, each of the view's content types is set to a GUID with nothing being available from the dropdown. If I try to make a new view, nothing appears in the dropdown. If I try to paste in a GUID that one of the other views is using it will save without throwing any errors, but if you go back into the settings it will be set to "View doesn't need Data". 

**Expected behavior**   
Have a single "Default" scope that shows the available content types, and can be accessed in the view settings.

**Instructions to Reproduce the Problem**

Install up to 2sxc 12.8.1 LTS, then update to 2sxc 12.10.0, then install one of the 2sic hybrid apps. Open the app settings, and go to the data tab. It should be blank, but switch the Scope dropdown to the other available "Scope: Default" option and everything will appear. 

**Why change the behavior?**  
It is unusable if you want to create new views. 

**Your environment**  
Windows Server 2019, Windows 10

* **2sxc version(s):** 12.10.0  
* **Browser:** Chrome 97.0.4692.99 Firefox 96.0.3 Edge 97.0.1072.76
* **DNN:** 8.0.4 and 9.8.1
* **Language:** English

**Anything you would like to add**
This project was on 2sxc 12.8.1 LTS, but we upgraded it to v12.10.0 this morning in order to use the latest Mobius Forms.

**Comment by jeremy-farrance** [comment] 2022-02-02 02:20
I thought a quick video might make it more clear what is wrong and how this is broken in a very odd way.

https://user-images.githubusercontent.com/653301/152083212-b91cab7b-9919-48c2-8e52-a18b047ca8e4.mp4

**Comment by iJungleboy** [comment] 2022-02-02 09:06
@jeremy-farrance Thanks for this.

We've been trying to clean up scope names, an they still have left-overs from the old days - the default scope was called something like `2SexyContent` and we're trying to really get it to be `Default`.

I may have a bug in 12.10 which is probably resolved in 13.01 since as of all my development now, I don't see any such issues. Could you do a test-upgrade to check if the problem is still in the latest version or only in 12.10?

**Comment by jtherrien-accuraty** [comment] 2022-02-03 22:40
Upgrading to the latest removed the duplicate so it did fix the issue.

**Comment by iJungleboy** [comment] 2022-02-07 06:40
thx for the feedback

**Closed by iJungleboy** 2022-02-07 06:40 UTC

**Comment by jeremy-farrance** [comment] 2022-02-07 13:48
@iJungleboy 

By closing this - you are not going to fix it in one of the LTS versions before v13? 
 
This seems important enough to warrant a 12.08.02, no?

**Comment by iJungleboy** [comment] 2022-02-07 14:38
I believe 12.08 isn't affected, only 12.10 which is post LTS. 
But correct me if I'm wrong. 
Plan is rather to focus on a 13 LTS within a few weeks.
