### ISSUE TITLE
DNN 7.4.1, Edit hyperlink attribute, error

### ISSUE THREAD

**Issue by EzraM** [2sic/2sxc#259] opened 2015-06-01 19:44 UTC
On a clean install of DNN 7.4.1 and 2sxc 7.01.01:
1. Created a new Content-Type
2. Added Hyperlink
3. Clicked 'Hyperlink' (trying to specify that it's an image)

2sxc logs the following error:
```
AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:5ef20154-90d6-44a0-9b2e-b95d77db6513

AssemblyVersion:7.4.1

PortalId:0

UserId:1

TabId:55

RawUrl:/Home/ctl/eavmanagement/mid/415/AppID/11?popUp=true&ManagementMode=NewItem&AttributeSetId=277&keyNumber=313&keyGuid=&AssignmentObjectTypeId=2&ReturnUrl=http%3a%2f%2flocalhost%3a3000%2fHome%2fctl%2feavmanagement%2fmid%2f415%2fAppID%2f11%3fpopUp%3dtrue%26Managem

Referrer:http://localhost:3000/Home/ctl/eavmanagement/mid/415/AppID/11?popUp=true&ManagementMode=ContentTypeFields&AttributeSetId=300

UserAgent:Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko

ExceptionHash:7Gqr7gl3igToEtOHzU+X4Q==

Message:Nullable object must have a value.

StackTrace:
InnerMessage:Nullable object must have a value.

InnerStackTrace:
   at System.Nullable`1.get_Value()
   at ToSic.Eav.ManagementUI.EavManagement.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at ToSic.SexyContent.EAVManagement.Page_Load(Object sender, EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

Great extension, by the way :-)

**Comment by iJungleboy** [comment] 2015-06-02 07:33
Thanks. This is an issue caused by 7.4.1 - we're looking into it. Duplicate #258 so I'll close this for now.

**Closed by iJungleboy** 2015-06-02 07:33 UTC

**Comment by EzraM** [comment] 2015-06-02 14:22
Thank you! 2sxc has made a big lift and shift project run smooth so far. It's much appreciated.

**Comment by iJungleboy** [comment] 2015-06-02 14:28
your welcome - and please! rate us on codeplex and the store - this is very impontant that new users trust the tool and try it :)
