### ISSUE TITLE
Missing/broken localization of Snippets headers

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#913] opened 2016-09-01 12:21 UTC
Minor issue, best shown in a picture:
![image](https://cloud.githubusercontent.com/assets/5693190/18167132/2d98d562-704f-11e6-8f00-193252879607.png)

**Comment by iJungleboy** [comment] 2016-09-04 07:18
Note that on my system, I cannot reproduce this issue. Could you check more into details what causes it? What language are you using in the front-end? does it always happen or just occasionally? thx!

**Comment by iJungleboy** [comment] 2016-09-07 08:31
As of now I'm assuming it was something very specific, not related to 2sxc - so I'll close this. If I'm wrong, please just re-open.

**Comment by SCullman** [comment] 2016-09-07 09:29
I tested on a german site, and I noticed the following in Console:
Failed to load resource: XXXX/desktopmodules/tosic_sexycontent/dist/i18n/source-editor-snippets-de.js

**Comment by SCullman** [comment] 2016-09-07 09:30
It works on the same installation with an English Portal

**Comment by SCullman** [comment] 2016-09-07 09:32
How do I reopen an issue? by creating a new issue?

**Comment by iJungleboy** [comment] 2016-09-07 11:56
thx, will reopen

**Closed** 2016-09-11 19:29 UTC
Labels: affects-admin, not critical
