### ISSUE TITLE
error while exporting app

### ISSUE THREAD

**Issue by dnastone** [2sic/2sxc#746] opened 2016-03-17 09:31 UTC
hello, 
i'm using dnn 7.4.2 and 2sexy 8.3.6 and i wanted to export an app with the option to reimport it with all that content to a other portal. 

but i get this error when i click on export: 

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:3c259843-3a69-48b0-947c-374d71321d62
AssemblyVersion:7.4.2
PortalId:0
UserId:1
TabId:120
RawUrl:/exclusiveparts/mid/614/ctl/appexport/appid/4/dnnprintmode/true?SkinSrc=%5bG%5dSkins%2f_default%2fNo+Skin&ContainerSrc=%5bG%5dContainers%2f_default%2fNo+Container
Referrer:http://www.p-performance.at/exclusiveparts/mid/614/ctl/appexport/appid/4/dnnprintmode/true?SkinSrc=%5bG%5dSkins%2f_default%2fNo+Skin&ContainerSrc=%5bG%5dContainers%2f_default%2fNo+Container
UserAgent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36
ExceptionHash:k0lC4YYV8VW5VGWTlHaSJQ==
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
StackTrace:
InnerMessage:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
InnerStackTrace:
   bei ToSic.SexyContent.ImportExport.XmlExporter.AddFileAndFolderToQueue(Int32 fileNum) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\XmlExporter.cs:Zeile 286.
   bei ToSic.SexyContent.ImportExport.XmlExporter.GetEntityXElement(Entity e) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\XmlExporter.cs:Zeile 253.
   bei ToSic.SexyContent.ImportExport.XmlExporter.get_ExportXDocument() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\XmlExporter.cs:Zeile 183.
   bei ToSic.SexyContent.ImportExport.XmlExporter.GenerateNiceXml() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\XmlExporter.cs:Zeile 67.
   bei ToSic.SexyContent.ImportExport.ZipExport.ExportApp(Boolean includeContentGroups, Boolean resetAppGuid) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\ZipExport.cs:Zeile 64.
   bei ToSic.SexyContent.Administration.Apps.AppExport.btnExportApp_OnClick(Object sender, EventArgs e) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Administration\Apps\AppExport.ascx.cs:Zeile 22.
   bei System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   bei System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server-Name: rs216170

**Comment by iJungleboy** [comment] 2016-03-17 12:02
Two things

1. Pls always prefix code / logs with three backwards apo-characters so it's easier to use :)
2. I'm guessing your file system and dnn are not in sync - could you check that?

**Comment by iJungleboy** [comment] 2016-03-17 12:13
I checked the code and it's really the add-file-to-queue which breaks, apparently the file doesn't exist. Pls re-sync your file-system with DNN. 

I will also enhance 2sxc to ignore these errors in the future, and just skip these files.

**Comment by dnastone** [comment] 2016-03-17 12:25
hello,

i synced the folders and files at the admin section and at the system section.
but i get the error again:

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:36276f9f-7f0a-4820-b9e9-a804156e3833
AssemblyVersion:7.4.2
PortalId:0
UserId:1
TabId:120
RawUrl:/exclusiveparts/mid/614/ctl/appexport/appid/4/dnnprintmode/true?SkinSrc=%5bG%5dSkins%2f_default%2fNo+Skin&ContainerSrc=%5bG%5dContainers%2f_default%2fNo+Container
Referrer:http://www.p-performance.at/exclusiveparts/mid/614/ctl/appexport/appid/4/dnnprintmode/true?SkinSrc=%5bG%5dSkins%2f_default%2fNo+Skin&ContainerSrc=%5bG%5dContainers%2f_default%2fNo+Container
UserAgent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36
ExceptionHash:GRG7Ta25Ore2SwQAPTvbRg==
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
StackTrace:
InnerMessage:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
InnerStackTrace:
   bei ToSic.SexyContent.ImportExport.XmlExporter.AddFileAndFolderToQueue(Int32 fileNum) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\XmlExporter.cs:Zeile 286.
   bei ToSic.SexyContent.ImportExport.XmlExporter.GetEntityXElement(Entity e) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\XmlExporter.cs:Zeile 253.
   bei ToSic.SexyContent.ImportExport.XmlExporter.get_ExportXDocument() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\XmlExporter.cs:Zeile 183.
   bei ToSic.SexyContent.ImportExport.XmlExporter.GenerateNiceXml() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\XmlExporter.cs:Zeile 67.
   bei ToSic.SexyContent.ImportExport.ZipExport.ExportApp(Boolean includeContentGroups, Boolean resetAppGuid) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\ZipExport.cs:Zeile 64.
   bei ToSic.SexyContent.Administration.Apps.AppExport.btnExportApp_OnClick(Object sender, EventArgs e) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Administration\Apps\AppExport.ascx.cs:Zeile 22.
   bei System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   bei System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server-Name: rs216170

**Comment by iJungleboy** [comment] 2016-03-17 12:25
I know this will sound annoying, but I must verify it: did you sync recursively?

**Comment by dnastone** [comment] 2016-03-17 12:27
yes folders & subfolders

**Comment by iJungleboy** [comment] 2016-03-17 12:30
Ok. The next version will contain a fix, but apparently something is still referencing the lost file - probably a hyperlink-field with a file:37503 kind of content, pointing to a non-existing file. If your app only has a few records, you should be able to spot it quickly.

**Comment by dnastone** [comment] 2016-03-17 13:17
i looked into it and found some entries where stand file: number which doesn't work.
i wanted to delete the entrie but i get this error message:

AbsoluteURL:/desktopmodules/2sxc/api/eav/entities/delete
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:7b79652b-2c6e-4dab-83d2-f1bc8cb7c38d
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:NULr19QCRxKnxpEZYnEJow==
Message:An error occurred while executing the request. Please consult the event log for details.
StackTrace:
InnerMessage:Item 615 cannot be deleted. It is used by other items: found 1 child relationships: 614.
InnerStackTrace:
   bei ToSic.Eav.WebApi.EntitiesController.Delete(String contentType, Int32 id, Nullable`1 appId) in C:\Projects\eav-server\ToSic.Eav.WebApi\EntitiesController.cs:Zeile 310.
   bei ToSic.SexyContent.EAVExtensions.EavApiProxies.EntitiesController.Delete(String contentType, Int32 id, Int32 appId) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\WebApi\EavApiProxies\EntitiesController.cs:Zeile 217.
   bei System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClassf.b__9(Object instance, Object[] methodParameters)
   bei System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   bei System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server-Name: rs216170

**Comment by iJungleboy** [comment] 2016-03-17 13:30
apparently you're still referencing these items - so you can't just delete them. This is for your own protection. to resolve the file:issue, just delete the value file:....

To resolve the "still in use" you have to find item 614, that one is pointing to your item and preventing the delete.

**Comment by dnastone** [comment] 2016-03-23 13:16
hello,
today i installed the new version but the export error still happens again

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:1f391640-c243-479d-937f-76f289e7d421
AssemblyVersion:7.4.2
PortalId:0
UserId:1
TabId:120
RawUrl:/exclusiveparts/mid/614/ctl/appexport/appid/4/dnnprintmode/true?SkinSrc=%5bG%5dSkins%2f_default%2fNo+Skin&ContainerSrc=%5bG%5dContainers%2f_default%2fNo+Container
Referrer:http://www.p-performance.at/exclusiveparts/mid/614/ctl/appexport/appid/4/dnnprintmode/true?SkinSrc=%5bG%5dSkins%2f_default%2fNo+Skin&ContainerSrc=%5bG%5dContainers%2f_default%2fNo+Container
UserAgent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
ExceptionHash:Uh9GXIEKoNo8biTG7F5vtw==
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
StackTrace:
InnerMessage:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
InnerStackTrace:
   bei ToSic.SexyContent.ImportExport.XmlExporter.AddFileAndFolderToQueue(Int32 fileNum) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\XmlExporter.cs:Zeile 286.
   bei ToSic.SexyContent.ImportExport.XmlExporter.GetEntityXElement(Entity e) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\XmlExporter.cs:Zeile 253.
   bei ToSic.SexyContent.ImportExport.XmlExporter.get_ExportXDocument() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\XmlExporter.cs:Zeile 183.
   bei ToSic.SexyContent.ImportExport.XmlExporter.GenerateNiceXml() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\XmlExporter.cs:Zeile 67.
   bei ToSic.SexyContent.ImportExport.ZipExport.ExportApp(Boolean includeContentGroups, Boolean resetAppGuid) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\ZipExport.cs:Zeile 64.
   bei ToSic.SexyContent.Administration.Apps.AppExport.btnExportApp_OnClick(Object sender, EventArgs e) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Administration\Apps\AppExport.ascx.cs:Zeile 22.
   bei System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   bei System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server-Name: rs216170

**Comment by iJungleboy** [comment] 2016-03-24 11:18
Sorry, will look into it.

**Comment by dnastone** [comment] 2016-04-05 09:17
hello, when do you think that you would have a new module update? cause i'm not programmer enough to solve this problem at my portal, but i have tpo export and import the whole content to finish my project.
thanks

**Comment by dnastone** [comment] 2016-04-11 14:35
hello.
today i installed the version 7.4.0 and now the export of the content works. but then i wanted to import the content to the other portal and there i get the error message during the import that the folder at the file management already exists and no i get this error message from the module:

AbsoluteURL:
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:62732ced-b95e-4291-90b3-e453bf614f31
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:lsFvaoCj4+nBF2EeCZ9nAQ==
Message:Search: Error while indexing module 621 on tab 118, portal 0
StackTrace:
   bei ToSic.SexyContent.Environment.Dnn7.DnnBusinessController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Environment\Dnn7\DnnBusinessController.cs:Zeile 31.
   bei DotNetNuke.Services.Search.ModuleIndexer.IndexSearchDocuments(Int32 portalId, Int32 scheduleId, DateTime startDateLocal, Action`1 indexer)
InnerMessage:no portal settings received
InnerStackTrace:
   bei ToSic.SexyContent.App..ctor(Int32 zoneId, Int32 appId, PortalSettings ownerPortalSettings, Boolean allowSideEffects) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\App.cs:Zeile 85.
   bei ToSic.SexyContent.ContentBlock.ModuleContentBlock..ctor(ModuleInfo moduleInfo) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentBlock\ModuleContentBlock.cs:Zeile 41.
   bei ToSic.SexyContent.Search.SearchController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Search\SearchController.cs:Zeile 45.
   bei ToSic.SexyContent.Environment.Dnn7.DnnBusinessController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Environment\Dnn7\DnnBusinessController.cs:Zeile 27.
Source:ToSic.SexyContent
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server-Name: rs216170

**Comment by dnastone** [comment] 2016-04-11 14:43
during the import i get this message error at the end:

Could not import the app / package: Der Pfad hat ein ungültiges Format.

thats the message at the event protocoll:

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:d63e848f-7796-4233-8f72-5816f574d26d
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:oTgASyLOqWXhco94R2GHxQ==
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
StackTrace:
   bei ToSic.SexyContent.View.InitModuleActions() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:Zeile 157.
   bei ToSic.SexyContent.View.get_ModuleActions() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:Zeile 108.
InnerMessage:
InnerStackTrace:
Source:ToSic.SexyContent
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server-Name: rs216170

**Comment by dnastone** [comment] 2016-04-11 14:49
something strange at the app management.
when i open it i have four diffrent apps with diffrent names but when i click on the export button it always exports the last app. i attach two sceens where you can see that i click on the first app to export but on the overlay window it shows me the last app.

![screen2](https://cloud.githubusercontent.com/assets/11678580/14431292/4a2e077a-0005-11e6-9435-d69bb19f637a.jpg)
![screen1](https://cloud.githubusercontent.com/assets/11678580/14431291/4a2b3130-0005-11e6-8d1f-afcb87a6b380.jpg)

**Comment by iJungleboy** [comment] 2016-04-11 16:05
Yes, this is a bug in 08.3.* - it actually opens the export of the app you initially started the dialog in. 
It's fixed in 8.4 (still beta). 

Workaround: open the "manage apps" from your app, or go to your app-settings first, and export from there.

**Comment by iJungleboy** [comment] 2016-04-14 08:26
Just to verify - did the import-thing solve itself? I'm not sure if all your issues are solved.

**Comment by dnastone** [comment] 2016-04-14 12:20
i installed the latest version but i get the same error like before:

AbsoluteURL:
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:7bfba768-e494-4518-87f8-614937bc4d5c
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:mKyekCAKq38SO3Mk+IR4UA==
Message:Search: Error while indexing module 621 on tab 118, portal 0
StackTrace:
   bei ToSic.SexyContent.Environment.Dnn7.DnnBusinessController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Environment\Dnn7\DnnBusinessController.cs:Zeile 31.
   bei DotNetNuke.Services.Search.ModuleIndexer.IndexSearchDocuments(Int32 portalId, Int32 scheduleId, DateTime startDateLocal, Action`1 indexer)
InnerMessage:no portal settings received
InnerStackTrace:
   bei ToSic.SexyContent.App..ctor(Int32 zoneId, Int32 appId, PortalSettings ownerPortalSettings, Boolean allowSideEffects) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\App.cs:Zeile 85.
   bei ToSic.SexyContent.ContentBlock.ModuleContentBlock..ctor(ModuleInfo moduleInfo) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentBlock\ModuleContentBlock.cs:Zeile 41.
   bei ToSic.SexyContent.Search.SearchController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Search\SearchController.cs:Zeile 45.
   bei ToSic.SexyContent.Environment.Dnn7.DnnBusinessController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Environment\Dnn7\DnnBusinessController.cs:Zeile 27.
Source:ToSic.SexyContent
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server-Name: rs216170

i can only export one of the fourth app. only the latest one of the list. when i click on the first app to export i get the name und entities from the latest one.

**Comment by iJungleboy** [comment] 2016-04-14 13:05
Please help clarify, because this git-issue is about export/import, there is another one about search. 

Your last answers seems to be a search-related issue, not an export/import - correct?

**Comment by dnastone** [comment] 2016-04-14 13:36
this error message above i get every minute at my event protocoll

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:7e87dc7c-4b91-472a-a896-187afea7082c
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:wweOk3OqHFJHh7iUED+dTw==
Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
StackTrace:
   bei ToSic.SexyContent.View.InitModuleActions() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:Zeile 157.
   bei ToSic.SexyContent.View.get_ModuleActions() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:Zeile 108.
InnerMessage:
InnerStackTrace:
Source:ToSic.SexyContent
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server-Name: rs216170

**and this one**

AbsoluteURL:
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:24d3be75-7ad6-4c06-be6d-82729b87b256
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:fYM9qSsUECqFWDBx1wU3Ow==
Message:Search: Error while indexing module 621 on tab 118, portal 0
StackTrace:
   bei ToSic.SexyContent.Environment.Dnn7.DnnBusinessController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Environment\Dnn7\DnnBusinessController.cs:Zeile 31.
   bei DotNetNuke.Services.Search.ModuleIndexer.IndexSearchDocuments(Int32 portalId, Int32 scheduleId, DateTime startDateLocal, Action`1 indexer)
InnerMessage:no portal settings received
InnerStackTrace:
   bei ToSic.SexyContent.App..ctor(Int32 zoneId, Int32 appId, PortalSettings ownerPortalSettings, Boolean allowSideEffects) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\App.cs:Zeile 85.
   bei ToSic.SexyContent.ContentBlock.ModuleContentBlock..ctor(ModuleInfo moduleInfo) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentBlock\ModuleContentBlock.cs:Zeile 41.
   bei ToSic.SexyContent.Search.SearchController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Search\SearchController.cs:Zeile 45.
   bei ToSic.SexyContent.Environment.Dnn7.DnnBusinessController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Environment\Dnn7\DnnBusinessController.cs:Zeile 27.
Source:ToSic.SexyContent
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server-Name: rs216170

**Comment by dnastone** [comment] 2016-04-14 13:36
i thought this comes from the broken import

**Comment by dnastone** [comment] 2016-04-14 13:42
import export problem:

first i only can export the last app. at my portal i have 4 apps and i can only export the latest one at the list. when i click in the first app at the export button the module show me the latest app with the entities and so on at the overlay window.

when i export the app and want to import the app it fails. 
here are some screens:

![apps_after_import2](https://cloud.githubusercontent.com/assets/11678580/14530017/5c272976-0257-11e6-8a1b-d39fab62ed95.jpg)
![screen1](https://cloud.githubusercontent.com/assets/11678580/14530018/5c27a676-0257-11e6-89c8-0a6234af004f.jpg)
![screen2](https://cloud.githubusercontent.com/assets/11678580/14530019/5c27dea2-0257-11e6-8c41-07508919c900.jpg)
![apps_after_import](https://cloud.githubusercontent.com/assets/11678580/14530020/5c2b9fce-0257-11e6-810f-2bbd8be51a37.jpg)

**Comment by iJungleboy** [comment] 2016-04-14 14:46
I believe these are two, unrelated issues. 

The regular one from search is probably not related to the import - it could be, but the indexer only searches in modules which are on some page - which doesn't seem to be the case when the import fails. 

I'm guessing it's probably most efficient if we looked at the import package to figure out what's not working; better than trying to message back and forth. I think we could at least figure out what the problem is in about 1h, most likely it won't require anything more than that. If you want that, please check http://2sxc.org/en/Contact

If you want to continue trying to corner it yourself, I recommend you try the newest beta, as it does fix some import issues. At least upgrade to 8.3.7, but the newest beta would be 8.4.0f

**Comment by dnastone** [comment] 2016-04-14 14:52
i sent you an email trough your contact form

**Comment by dnastone** [comment] 2016-04-14 20:07
my latest tests i made was with 8.4.0f

**Comment by iJungleboy** [comment] 2016-04-20 19:56
I'm looking at it - it seems that you have an empty folder-node in the xml which seems to cause problems. I'll
1. Improve 2sxc to provide more detailed error information in such a case
2. improve 2sxc to try to ignore such a special case

**Comment by iJungleboy** [comment] 2016-04-20 20:43
It really seems to be this issue. if you want a quick fix, remove
'    <Folder Id="36" RelativePath="" />'
from your App.xml in the zip. 
2sxc 8.4.1 (tomorrow or this weekend) will also ignore this from now on.

**Closed** 2016-04-20 20:47 UTC

**Comment by iJungleboy** [comment] 2016-04-20 22:26
just published release - please test :)

**Comment by dnastone** [comment] 2016-04-21 08:25
hello,
thanks for the update. i installed it but i get a other error during the import:

Could not import the app / package: Fehler beim Ausführen der Befehlsdefinition. Weitere Informationen finden Sie in der internen Ausnahme.

**Comment by iJungleboy** [comment] 2016-04-21 11:42
after reviewing it on your system I believe I found the issue, pls check your mail.

**Comment by dnastone** [comment] 2016-04-26 08:10
hello, with the new version i could delete all text entries that wasn't used from an module and now the import works :)

but at one site i have placed a new 2sexy module and deleted that one from the dnn template.
at this tab the content entries are not shown. is it possible to asign those entries to the new module?
thanks

**Comment by iJungleboy** [comment] 2016-04-26 09:06
It can be done - but would require you to enter the DB. better to un-delete the module in DNN or to create a new  module and just assign all the items (they still exist) to the new module manually. If it's just 5-20 item's your faster that way.

**Comment by dnastone** [comment] 2016-04-27 08:42
hello, today i had to duplicage the same portal for a third time again. i did it the same way like the first portal, but after importing the app (without errors) i get this error message from the app module:

Error: System.Web.HttpCompileException (0x80004005): c:\inetpub\wwwroot\www.p-performance.at\Portals\5\2sxc\p-performance\_BildText.cshtml(1): error CS0305: Die Verwendung von Typ 'System.Collections.Generic.List<T>' (generisch) erfordert 1-Typargumente. bei System.Web.Compilation.AssemblyBuilder.Compile() bei System.Web.Compilation.BuildProvidersCompiler.PerformBuild() bei System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) bei System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) bei System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) bei System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound) bei System.Web.Compilation.BuildManager.GetCompiledType(VirtualPath virtualPath) bei ToSic.SexyContent.Engines.RazorEngine.CreateWebPageInstance() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:Zeile 81. bei ToSic.SexyContent.Engines.RazorEngine.InitWebpage() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:Zeile 110. bei ToSic.SexyContent.Engines.RazorEngine.Init() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:Zeile 27. bei ToSic.SexyContent.Engines.EngineBase.Init(Template template, App app, ModuleInfo hostingModule, IDataSource dataSource, InstancePurposes instancePurposes, SxcInstance sexy) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Engines\EngineBase.cs:Zeile 60. bei ToSic.SexyContent.SxcInstance.GetRenderingEngine(InstancePurposes renderingPurpose) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\SxcInstance.cs:Zeile 226. bei ToSic.SexyContent.SxcInstance.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\SxcInstance.cs:Zeile 182.

**Comment by iJungleboy** [comment] 2016-04-27 09:05
this looks like a razor / .net issue. My guess is that you have different versions on your source / target system. So here he's unhappy about your template / view. Could you paste your code here and compare your .net versions on the two systems?

Pls also check your web.config in the /portals/x/2sxc/ folder, it should be the same on both systems...

**Comment by dnastone** [comment] 2016-04-27 09:09
that's the system and the same cms installation. it has the portalID 5.the only thing that changes is the CMS version. i installed the update from the CMS to 8.0.2
but i thought this cms update depends only to the editor?

**Comment by iJungleboy** [comment] 2016-04-27 09:10
did ou check the web.config?

**Comment by iJungleboy** [comment] 2016-04-27 09:13
Note that if you went from dnn 7 to 8, you automatically also use a different .net. There are very small differences that could hit you when going to a different .net version; things that the older .net version may have accepted but need corrections when going to the newer one. Best paste the first few lines of
p-performance_BildText.cshtml(1)
here...

**Comment by dnastone** [comment] 2016-04-27 09:36
i upcreated from 8.0.1 to 8.0.2 and with the version 8.0.1 it worked

**Comment by iJungleboy** [comment] 2016-04-27 10:17
could you pase the first few lines of cshtml?

**Comment by dnastone** [comment] 2016-04-27 11:28
thats the code from the _bildtext.cshtml

@foreach(var set in List)
	{
	var Inhalt = set.Content;
	<div>@Inhalt.Toolbar</div>
	<div class="row">
		<div class="col-md-5">
			@if (Inhalt.Bild != "")
			{
			<div style="padding-bottom:25px;"><img src="@Inhalt.Picture?w=350" class="img-responsive img-rounded" alt="@Inhalt.PictureTitle" title="@Inhalt.PictureTitle" /></div>
			}
		</div>
		<div class="col-md-7">
			<h2>@Inhalt.Headline</h2>
			<div style="padding-bottom:25px;">@Html.Raw(Inhalt.Text)</div>
		</div>
	</div>
	}

**Comment by dnastone** [comment] 2016-04-27 11:28
`@foreach(var set in List)
	{
	var Inhalt = set.Content;
	<div>@Inhalt.Toolbar</div>
	<div class="row">
		<div class="col-md-5">
			@if (Inhalt.Bild != "")
			{
			<div style="padding-bottom:25px;"><img src="@Inhalt.Picture?w=350" class="img-responsive img-rounded" alt="@Inhalt.PictureTitle" title="@Inhalt.PictureTitle" /></div>
			}
		</div>
		<div class="col-md-7">
			<h2>@Inhalt.Headline</h2>
			<div style="padding-bottom:25px;">@Html.Raw(Inhalt.Text)</div>
		</div>
	</div>
	}`

**Comment by iJungleboy** [comment] 2016-04-27 11:35
ok, this looks all clean. 
Note that I fixed your pasted code with three apos-characters to make it readable.

this looks ok. Did you check that you didn't accidentally delete the web.config in the portals.../2sxc folder? that is very important.

**Comment by dnastone** [comment] 2016-04-27 11:39
great that was the problem. i copied the config file from the other portal and it works. :)

i imported the blueampgallery too and the import works, but i can't see any picture at the app.
