### ISSUE TITLE
Basic Content template broken - 2sxc v13.10.1

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#2731] opened 2022-05-06 05:40 UTC
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Razor templating
[x] Content Types or data management

**Current behavior**   

Brand new test website using DNN v9.10.2 with 2Shine BS5 v5.0.2 theme. Added Basic Content template "Image | Text" to the page. Demo items appear properly. However, the editor control panel for the "Image | Text" does not allow selection of an image - text only.

![Screenshot 2022-05-06 012815](https://user-images.githubusercontent.com/3846223/167072828-ef5ea053-2757-44e3-bb06-4fb23a339f48.jpg)

**Expected behavior**   

Prior to 2sxc v13.00.01, the control panel for Basic Content "Image | Text" allowed for entry of both text and an image.

**Instructions to Reproduce the Problem**

1. Create new web page
2. Apply 2Shine BS5 theme to page
3. Add Basic Content "Image | Text" item to page 
4. Edit newly created content item

**Why change the behavior?**  

It's broken now. Was working before in pre-2SXC 13 LTS releases.

**Your environment**  

Windows 11, SQLExpress server

* **2sxc version(s):** 13.0.1  
* **Browser:** [all ]
* **DNN:** [9.10.2 ] 
* **Language:** [English]

**Anything you would like to add**

**Comment by iJungleboy** [comment] 2022-05-06 06:14
thanks! we'll address this asap! @getBlup pls check ;)

**Comment by getBlup** [comment] 2022-05-06 06:54
@skarpik thanks for submitting this issue, the problem is fixed with release [13.10.01](https://github.com/2sic/2sxc-content-app/releases/tag/v13.10.01).

**Comment by getBlup** [comment] 2022-05-06 07:19
If you only want to change it locally you would have to change three files in the content app: 

1. **bs3/Content/_Text and Image.cshtml**
Line 17: `var buttonConfig = "?prefill:VarShowImage=true&prefill:VarShowText=true";`
3. **bs4/Content/_Text and Image.cshtml**
Line 17: `var buttonConfig = "?prefill:VarShowImage=true&prefill:VarShowText=true";`
5. **bs5/Content/_Text and Image.cshtml**
Line 17: `var buttonConfig = "?prefill:VarShowImage=true&prefill:VarShowText=true";`

**Closed by getBlup** 2022-05-06 07:20 UTC

**Comment by jeremy-farrance** [comment] 2022-05-06 14:27
In what versions of the Content App is this necessary? I just checked a site with 12.5.2 (Content App, not 2sxc) and "toolbarConfig" was not there.

**Comment by iJungleboy** [comment] 2022-05-06 14:58
@jeremy-farrance Some background

In the v13 templates we had already implemented special toolbars which used `prefill` to inform the edit-ui to disable some fields. This worked as expected. 

It seems in one of the last v12 releases we made a mistake when we introduced the zig-zag options to add more content blocks alternating images right/left. In the zig-zag releases the toolbar-specialties got lost, so we re-introduced them in 13.10.00. 

But in 13.10.00 we accidentally made some mistakes in the code-cleanup and placed those toolbar configs on templates which showed images (so they should have also shown the image field...). This was fixed in 13.10.01, but we noticed it was fixed in a way that works, but was more code than necesssary. We cleaned this in the 13.10.02 templates now. 

Hope that helps ;). best check the 13.10.02 to see how it's best done.

**Comment by jeremy-farrance** [comment] 2022-05-06 15:51
Thanks for the details. I appreciate it.

**Comment by skarpik** [comment] 2022-05-06 16:48
I created a website for the purpose of testing the 2sxc 13.10 LTS. As I mentioned, it was DNN v9.10.02 and 2sxc 13.10.01 which includes 2sxc Content 13.10.00. I would like to continue my testing of the 2sxc LTS do I:

- install Content 13.10.02 over top of Content 13.10.00 (I have a feeling that won't work)
- wait until 2sxc LTS 13.10.02 is released (assuming that it incorporates the fix to Content) and rebuild my test website.

I don't think there is a way to delete Content v13.10.00 and do a clean install of Content 13.10.02. Or maybe there is.

I have to admit to being a little unclear on the proper way of upgrading templates when new versions are issued to replace versions with bugs.

**Comment by jeremy-farrance** [comment] 2022-05-06 18:44
There is no upgrade process for Apps at this time. Once the Content App (the thing installed to /Portals/?/2sxc/Content and not the 2sxc Content module which always has the same version as the 2sxc app module as seen in Dnn Settings/Extensions) you are basically stuck on that version. 

Just to recap since it is confusing to some:
 - 2sxc installs as a Dnn module (package)
 - Once installed, in Settings/Extensions under Showing: Module you see 2 items for 2sxc: App and Content. These two items always show the same version (e.g. 13.10.2)
 - The first time you use the Content module, it phones home and installs the latest recommend Content App from the 2sxc App gallery
 - Once that Content App is installed, you are on that version and there is no upgrade option

**Comment by jeremy-farrance** [comment] 2022-05-06 18:52
Oh, and to correctly find out the version of your Content App, you need to go to Apps Management, the Apps tab (e.g. this screen clip is from a site we deploy in Oct 2021, so the Content App is stuck at 12.5.2):

![image](https://user-images.githubusercontent.com/653301/167200051-fa8addad-14e4-47f4-b64f-3ebd72d30b54.png)

**Comment by jeremy-farrance** [comment] 2022-05-06 19:00
And since you touched on it above. There is a way to "reset" the Content App. Read carefully. I've done it successfully, so it works.

Reset complete Content-App to Factory-Defaults
[https://azing.org/2sxc/r/Ll3AalkO](https://azing.org/2sxc/r/Ll3AalkO)
