### ISSUE TITLE
Can't get data in visual query from different portal.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [2sic/2sxc#2287] opened 2020-12-11 19:42 UTC
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management

**Current behavior**

I was trying to get data from another app at another portal but it didn't work. And I think that it's bug and didn't ask about it at stackoverflow, because `EntityTypeFilter` actually gave me correct list of entity types from that application, but output contains only demo items and they don't pass `EntityTypeFilter`, which has same type specified.

**Expected behavior**

App data source says that it gets data from different app by `AppId` and `ZoneId`, so I think it should do that.

**Minimal reproduction of the problem with instructions**

- install Gallery app at lets say portal 1 and portal 2
- add to some page view with multiple albums
- create few albums at portal 1 at that page
- create or edit existing view at Gallery app at portal 2
- add new visual query in your app at portal 2
- inside this visual query add data source `App` with `ZoneId` 1 and your app's id from portal 1
- add `EntityTypeFilter` and configure it to filter type `Album`
- add connections like at this screenshot:
![chrome_lGGiksKRGW](https://user-images.githubusercontent.com/21691213/101946905-4d50c800-3bf8-11eb-87fb-62ca6132db16.png)
- click `Save and Run` and check output
- as result demo items can be found in `Default` ouput and no albums in filtered results
- if you edit `App` block output point from `Default` to `Album` it will give you 2 default albums but no created albums

**What is the motivation / use case for changing the behavior?**

In visual queries `App` block's description it says that it gets data from another app, but it doesn't. At least in this scenario.

**Please tell us about your environment:**

Windows 10
Google Chrome

* **2sxc version(s):** 11.5.0  
* **Browser:** Chrome Version 87.0.4280.88 (Official Build) (64-bit)
* **DNN:** 9.6.1
* **Language:** English

**Comment by iJungleboy** [comment] 2020-12-13 08:13
I think you got all right except the zone id - that's not the portal id. The reason I'm almost 100% sure this is the cause is that zoneid 1 is usually a system zone containing some internal data. 

Best check the zone id when going to your portal and opening zone-management (where you see all the apps listed) - the title should tell you the zone id. The first ZoneId is usually 2.

I'll close this, assuming it fixes your issue. If not, just add a comment and I'll reopen.

**Closed by iJungleboy** 2020-12-13 08:13 UTC

**Comment by Constantine-Ketskalo** [comment] 2020-12-15 11:01
Thanks for pointing out about zoneId. I checked it and you are right. I didn't specify zoneId correctly. But, unfortunately it didn't help. It doesn't contain necessary data.

**Comment by iJungleboy** [comment] 2020-12-15 12:49
want to elaborate? what data is missing? Everything should be there.
