### ISSUE TITLE
Template editor: Show snippets for other / all content-types

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#905] opened 2016-08-22 06:20 UTC
Sometimes a template has no content-type assigned because it gets the data with razor. The template editor does not show snippets for any content type then. Idea: Display the snippets for all available content-types.

**Comment by iJungleboy** [comment] 2016-08-31 15:30
To do this, we need

1. A web service, which returns all "public" content-types and their fields (so no system-types etc.)
2. Ideally also a snippet for App.Data["_Content-Type_"]
3. The JS to add these to the dropdown, incl. toolbar thing and similar

**Comment by iJungleboy** [comment] 2019-06-12 11:34
Duplicate of #1596, so will close.

**Closed by iJungleboy** 2019-06-12 11:34 UTC
Labels: enhancement
