### ISSUE TITLE
[Feature Request] Add Property to allow a View to Detect a Demo Item

### ISSUE THREAD

**Issue by Accuraty** [2sic/2sxc#1792] opened 2019-07-06 15:17 UTC
Originally discussed here
https://stackoverflow.com/questions/56720774/how-can-i-detect-the-state-of-content-at-view-startup/56846845

[x] feature request

[x] Razor templating
[x] JS development
[x] Content Types or data management
[x] APIs like REST

**Current behavior**
In View code there is no direct way to detect that the (Default) Content is a Demo Item vs. actual data. 

**Expected behavior**
The Entity should have a Boolean property that identified is as a Demo Item, maybe something as simple as Content.IsDemo?

**What is the motivation / use case for changing the behavior?**
You can work around this by deciding to give your demo item a unique value in one of its fields and test for that. For example, PageID=99999 or just use the Guid of Entity you assign as the demo, then test for that. However, that is not self-documenting and prone, over time, to users breaking things.

**Please tell us about your environment:**
Windows Server 2016, IIS 9+, SQL 2016

2sxc version(s): 10.1.x or 10.2-pre
Browser: all
DNN: all, 9.x 
Language: any/all

**Comment by eXistenZe** [comment] 2019-07-07 07:26
As a workaround, you could create an app setting with the entity to be used as demo.

In your code, just check if the demo item is valid. If not, create an alternative with whatever you want (data or just some error message).

I'm finding app settings to be a great feature over many many other more complex features.

**Comment by Accuraty** [comment] 2019-07-07 18:33
We are doing something similar, currently and it works, but users make changes to things they do not understand and then it breaks and it often takes days for any sign of the issues and confusion to get back to us. We need a built in way to simply detect if the Demo Item is in play or not.

**Comment by iJungleboy** [comment] 2019-08-10 08:53
I would like to discuss a few aspects to see if we get the best way to do it. I want to discuss it because I would often prefer to "fix" bad behavior than add more options/features (KISS), but don't want to break anything existing. 

# Goals

1. The behavior should be simple and straightforward, so that both developers and editors get what they expect. 
1. Existing installations should not break
1. Existing installations should not suddenly show something different or nothing, if what was previously shown was intended
1. The editor should see the same output as the end-user, unless item-permissions or unpublished data specifically don't want something visible. But in this case, it should behave as the editor would expect it to.

# Background

## Demo vs. Default

The preview/demo/default item can have different purposes 

1. It can be used as a **preview**, which is not expected to be published, just so the editor will see what the thing would look like when he's adding modules to the page. This is the most common use case in normal content-templates, where the editor will usually overwrite everything. 

1. It can be used as the **default content** for when adding things where often the default is what you need and you don't expect the editor to modify it in most cases. This is common for content in branding elements (which often look the same, but optionally allow some configuration) or re-used elements like maps, where the default address is rarely changed even if you add the map multiple times. 

1. It can be used as the **configuration to use when not specified** which is what happens in _presentation_ items. These are rarely overridden by editors (editing only the content doesn't activate the presentation), and therefor never set. So they will always use the default configured in the template, and updating the template configuration will also update all instances which didn't actively override the defaults.

## The Types of Demo/Default Items

We must remember that there are up to 4 "demo" or "default" items

1. **content** which is used for single-item templates and as the first / default entry in a list. As of now, the behavior will _not_ render the template if the content is missing, to ensure that new views (often created by newbies) don't cause confusing errors because there is no data.
1. **presentation** which if set contains defaults for the presentation. So if a presentation-type is defined and a demo/default item as well, this is always used unless manually replaced by the editor. The presentation default can be updated at template level and will automatically affect all instances which didn't manually replace it
1. **list-content** this default is for the header
1. **list-presentation** this behaves like the _presentation_ as it is a global default and rarely replaced by the editor, but always can be replaced.

## Scenarios As Of Today

Now we have various scenarios and this is how the behave today + the problems they may have
1. initial insert of a view without adding any data yet - ATM this only renders the view if 
    1. there is no content-type defined, so the view doesn't expect data
    1. there is a content-type defined and a demo-item was specified, so the view expects data and will also get the data
    1. the view was configured to use a query (instead of instance specific data), in which case no such replacement happens
1. initial insert of a not-yet-functioning view by developers (experienced and novices) where the view isn't ready yet
1. an editor adds a single, initial item but sets it to unpublished. In this case, the public would still get an "empty" slot, so the system replaces it with the demo. This special case is often unexpected and causes trouble. Note that simply not replacing it would often cause other problems, because the view-code would fail since the developer usually doesn't ever check for this case
1. an editor sets a single item in a _list_ to draft/unpublished (without an original), so this "slot" is also reverted to demo item. This is the same unexpected problem like above.
1. an editor actively empties a list (or deletes the single item), because the list should be empty. In this case the system actively adds the demo again (because it looks like the initial module-insert), which can be unexpected. 
1. an editor actively adds the demo-item - in this case the editor really wants it there, so it's not there as a demo, but as real content.

## Challenges currently hard to handle

1. Sometimes you want an empty-item or empty-list to be populated with a demo, sometimes not. And this may depend on what the editor was doing - so the initial empty list may need a demo, but not when the editor actively tried to remove it. 
1. Sometimes you want a null-item to be populated with a demo, sometimes not. Again this may depend on what the editor was doing. 
1. As of now, all draft-items which shouldn't be public result in _null_ items at those positions, and are auto-replaced with the demo. This is usually not desired, but is how the system behaves ATM. I believe most developers & editors would expect draft-items to simply disappear for public users.

# Ideas and Possible Solutions

1. Change basic behavior that null-items (I believe this only happens when public users would see items which are not published) are removed and not substituted by the draft. Note that this wouldn't affect "empty" lists, since they are empty, and don't have null-items.  
The challenge here is to decide what to do, then the list then becomes empty after all null-items were removed, as the view may not know what to do in this case.
1. A property on each item like "IsDemo" which would tell the view that this is the demo-item. 
    * This would allow the view code to make some decisions
    * This would not help differentiate whether the demo was added because the list was empty because it's the initial list, or if it's empty because the editor wants it to be
1. An additional stream to _Default_ called _Original_,  _Raw_ or _DefaultUnmodified_ which contains the unmodified data, allowing the developer to choose if he would prefer to handle edge cases himself. 

Personally I kind of think that the additional stream (option 3) would be the safest way to go, but that we should also consider changing the behavior (option 1) which replaces drafts with the demo-item. What do you think?

**Comment by Accuraty** [comment] 2019-08-10 22:41
Wow, that is a lot. I read it all, made a few notes and will come back to it again tomorrow or soon. Thank you for this write up! One comment, under Ideas and Possible Solutions, 2) you are almost implying there are use cases where a single Entity (Content-Type) could (should or would) be locked to the view and add or replace should be not available? Can you give an example of a case where "it's empty because the editor wants it to be?"

**Comment by iJungleboy** [comment] 2019-08-12 06:36
@Accuraty for Idea/Solution #2 there are quite a few cases like this: someone creates a template and adds it to a page (no data exists yet), then edits the data and afterwards goes back to the view configuration to set this item as the default. Let's say it's a map of the company address. In this case, one instance has the "real" data assigned, and hitting "edit" will edit this item. In others, it's showing the default, so hitting edit would open a "new" dialog. 
There are other ways which result in the same thing: some show the entity 56720 because it's really assigned to the instance, others show the same entity because it's the default/preview.

**Comment by iJungleboy** [comment] 2019-09-18 16:42
I think I have a solution...
I've now added a property to dynamic objects called `IsDemoItem`. It's a bit long, but this is also to prevent existing properties of other people to conflict with it. It will only be true on entities which come from the ModuleDataSource and have been auto-added because of not-yet added data. 

I made it a property, so that code accessing this can still work in previous versions of 2sxc. So if you have 2sxc 10.06 (to be released), you can write

```
@if(item.IsDemoItem) {
  // what should happen if it's the demo 
} else { 
  // what should happen when it's "real" data
}
```

to ensure the code could also run previous versions of 2sxc, but simply ignore this functionality (like in our content-templates and demo-apps) we would use

```
@if(item.IsDemoItem ?? false) { 
  // what should happen for demos, and won't happen in 2sxc < 10.06
} else {
  // what should happen otherwise, and will always happen in 2sxc < 10.06
}

**Closed by iJungleboy** 2019-09-18 16:42 UTC

**Comment by Constantine-Ketskalo** [comment] 2022-11-01 11:42
Seems like it was in version 10.x but currently it's already 14.x version the latest and it seems that this property is absent. @iJungleboy , did you remove it?

**Comment by iJungleboy** [comment] 2022-11-02 08:28
@Constantine-Ketskalo It's still there. I just quickly verified it:

![image](https://user-images.githubusercontent.com/5321186/199438295-658aa186-b447-4111-abdd-dd5a0a67f18c.png)

**Comment by iJungleboy** [comment] 2022-11-02 08:29
documented here: https://docs.2sxc.org/api/dot-net/ToSic.Sxc.Data.DynamicEntity.html#ToSic_Sxc_Data_DynamicEntity_IsDemoItem

**Comment by Constantine-Ketskalo** [comment] 2022-11-04 12:42
@iJungleboy interesting. Then looks like it doesn't always work. For instance there's a view with list enabled (it's used for list and detailes implementation) and I don't want this message in the empty list that there is no demo item provided. The only way I know to hide it is to provide a demo item. But when I provide a demo item it's desplayed among regular items as well. So I thought of using this property `IsDemoItem` but in this particular case it doesn't work and it's false for all items, including a demo one. Probably that's because I didn't access it from `Content`, but instead I've selected all items of a target entity type directly from `App.Data["EntityType"]`.
So what I did eventually is I've hidden that demo item by unpublishing it on one page and another one needed slightly different logic, so there are header settings that contain property of type details entity and the one that is demo is selected there. So I'm comparing entityIds from there.

**Comment by iJungleboy** [comment] 2022-11-04 13:06
Since you're getting the data from `App.Data` and not from `Content` you can configure the view to have no "own" data. 

The "own" data is only relevant if people can add items directly on the view, so I think that is what you need. If the view doesn't have own data, you also can't (and don't need) to specify a demo-item.
