### ISSUE TITLE
Dropdown from query shows value instead of label

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1793] opened 2019-07-15 07:58 UTC
**I'm submitting a ...**
[x] bug report

**...about** 
[x] Content Types or data management

**Current behavior**
Following this issue:
https://github.com/2sic/2sxc/issues/1755
The "not found" bug was fixed, but the dropdown from query still shows the value instead of the label. This is still a major issue to me since I depend on this feature for many of my apps.

**Expected behavior**
After making a selection on the dropdown, show the label.

* **2sxc version(s):** 10.02

**Comment by iJungleboy** [comment] 2019-09-13 09:43
thx! @PagnoDunadan will look at this.

**Comment by PagnoDunadan** [comment] 2019-09-23 13:38
I cannot reproduce the issue. I've created string dropdown from query, set the query, stream, value and label and for me label is shown every time.

Could you please provide steps to reproduce the issue?

**Comment by eXistenZe** [comment] 2019-09-23 13:44
Did you try in a multi language app/site?

**Comment by eXistenZe** [comment] 2019-09-23 13:51
Here are the pics with the exact steps you described.
https://drive.google.com/drive/folders/1aquniizCchV6p2SYL8YXT58nxrzobYox?usp=sharing

**Comment by iJungleboy** [comment] 2019-09-23 13:55
@eXistenZe excellent screenshots, thanks. Just fyi: in the admin-list, it will still show just the ID, but of course in the edit-dialog you should see the labels.

**Comment by eXistenZe** [comment] 2019-09-23 14:15
Here goes another feature request: I don't know if you ever used software like SPSS, but they have this toggle in the main list (the admin view, in this case) where you can alternate between values and labels (for all vars). Could be interesting,
Check Here: http://www.youtube.com/watch?v=CHpC2h0IVPc&t=1m10s

**Comment by PagnoDunadan** [comment] 2019-09-23 14:22
Unfortunately I still cannot reproduce the issue. I've changed language to Português (Portugal), created two content types, one with string dropdown from query, other with data, created a query, wired it up and it shows me labels. Here are the screenshots. Please tell me if I didn't set something correctly.

Query:
![2019-09-23 16_13_54-Window](https://user-images.githubusercontent.com/7113033/65433612-a5e24c80-de1d-11e9-8ac7-b10c155706e8.png)

String dropdown from query settings:
![2019-09-23 16_14_31-Window](https://user-images.githubusercontent.com/7113033/65433645-b2ff3b80-de1d-11e9-8449-3764ccef3325.png)

Data view:
![2019-09-23 16_16_26-Window](https://user-images.githubusercontent.com/7113033/65433689-c0b4c100-de1d-11e9-95ca-1aa70c44386b.png)

Form view:
![2019-09-23 16_16_05-Window](https://user-images.githubusercontent.com/7113033/65433705-c90cfc00-de1d-11e9-9d66-77d1152c4c0b.png)

![2019-09-23 16_16_16-Window](https://user-images.githubusercontent.com/7113033/65433715-cf02dd00-de1d-11e9-9d73-48872c23b726.png)

**Comment by eXistenZe** [comment] 2019-09-23 14:48
Ok... Something definitly not working as intended with my end.
I'm trying to create a new demo app to send you, but I cannot configure the dropdown from query. It shows the config for normal strings, and not the query config part.

Added info: using DNN 9.4 and 2sxc 10.5.

![a1](https://user-images.githubusercontent.com/26518879/65436119-8812e880-de19-11e9-8f61-00b4047b8d1e.jpg)

![a2](https://user-images.githubusercontent.com/26518879/65436127-8c3f0600-de19-11e9-853b-52c62ffea646.jpg)

**Comment by eXistenZe** [comment] 2019-09-23 14:56
The above issue is solved reverting to the old UI (weird as it does not affect already configured dropdown-from-query fields.

The value/label issue remains however.

Here's an app for you to test if you feel it can help: https://drive.google.com/file/d/1pmV2gNPyGPaPtkKzkPzNN39HaAA7csTm/view?usp=sharing

**Comment by PagnoDunadan** [comment] 2019-09-23 14:56
That could be a 10.05. issue we had: https://github.com/2sic/2sxc/issues/1814. It is now fixed but 10.06. isn't out yet. Can you get all settings if you save it like that and open dialog again?

**Comment by PagnoDunadan** [comment] 2019-09-23 14:57
Thank you. I will check it out.

**Comment by eXistenZe** [comment] 2019-09-23 15:03
> 
> 
> That could be a 10.05. issue we had: #1814. It is now fixed but 10.06. isn't out yet. Can you get all settings if you save it like that and open dialog again?

Yes. That also solves it.

Here's what happens in my demo app:
![b1](https://user-images.githubusercontent.com/26518879/65437399-9feb6c00-de1b-11e9-8d42-7b104764f41a.jpg)

![b2](https://user-images.githubusercontent.com/26518879/65437403-a1b52f80-de1b-11e9-97e2-e510b3ac96c8.jpg)

**Comment by iJungleboy** [comment] 2019-09-23 15:53
@PagnoDunadan not sure if I understood everything - is this fixed?

**Comment by eXistenZe** [comment] 2019-09-23 15:56
No no. This was just another issue that arised when creating a demo.

**Comment by eXistenZe** [comment] 2019-09-24 16:35
Thanks. If you need anything else just ask.

**Comment by PagnoDunadan** [comment] 2019-09-25 07:25
Fixed in next release. I'm sorry I couldn't fit it in 10.06. I had to test this properly to not have some weird bug like this appear in entities again.

**Comment by eXistenZe** [comment] 2019-09-25 07:26
Thanks. That will save me a ton of time.

**Closed by PagnoDunadan** 2019-09-25 07:25 UTC
Labels: next
