### ISSUE TITLE
Error when exporting app.

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2860] opened 2022-09-27 09:35 UTC
**I'm submitting a ...** 
[x] bug report 

**...about** 
[x] admin experience UI
**Current behavior**  
When exporting an app I get:

`{"Message":"Bad Request","ExceptionMessage":"Could not find a part of the path 'C:\\Inetpub\\vhosts\\x.pt\\x.app\\desktopmodules\\tosic_sexycontent\\_\\4b38\\Apps\\CookieConsentForDnn\\2sexy\\App_Data\\app.xml'.","ExceptionType":"System.IO.DirectoryNotFoundException","StackTrace":"   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)\r\n   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)\r\n   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)\r\n   at ToSic.Eav.Apps.ImportExport.ZipExport.ExportApp(Boolean includeContentGroups, Boolean resetAppGuid) in C:\\Projects\\2sxc\\eav-server\\ToSic.Eav.Apps\\ImportExport\\ZipExport.cs:line 165\r\n   at ToSic.Sxc.WebApi.ImportExport.ExportApp.Export(Int32 zoneId, Int32 appId, Boolean includeContentGroups, Boolean resetAppGuid) in C:\\Projects\\2sxc\\2sxc\\Src\\Sxc\\ToSic.Sxc.WebApi\\ImportExport\\ExportApp.cs:line 117\r\n   at ToSic.Sxc.WebApi.Admin.AppControllerReal`1.Export(Int32 zoneId, Int32 appId, Boolean includeContentGroups, Boolean resetAppGuid) in C:\\Projects\\2sxc\\2sxc\\Src\\Sxc\\ToSic.Sxc.WebApi\\Admin\\AppControllerReal.cs:line 88\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()"}`

**Your environment** 

* **2sxc version(s):** 14.8

**Comment by iJungleboy** [comment] 2022-09-27 09:45
We did make a change and I have a guess...

could you update your DNN file-DB? in the admin section of the files "Sync..." all subfolders? 

My guess is that the `app.xml` isn't there any more, but DNN says it is.

**Comment by eXistenZe** [comment] 2022-09-27 09:48
Done.

Now it says:

{"Message":"Bad Request","ExceptionMessage":"The directory is not empty.\r\n","ExceptionType":"System.IO.IOException","StackTrace":"   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)\r\n   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)\r\n   at ToSic.Eav.Apps.ImportExport.ZipExport.ExportApp(Boolean includeContentGroups, Boolean resetAppGuid) in C:\\Projects\\2sxc\\eav-server\\ToSic.Eav.Apps\\ImportExport\\ZipExport.cs:line 169\r\n   at ToSic.Sxc.WebApi.ImportExport.ExportApp.Export(Int32 zoneId, Int32 appId, Boolean includeContentGroups, Boolean resetAppGuid) in C:\\Projects\\2sxc\\2sxc\\Src\\Sxc\\ToSic.Sxc.WebApi\\ImportExport\\ExportApp.cs:line 117\r\n   at ToSic.Sxc.WebApi.Admin.AppControllerReal`1.Export(Int32 zoneId, Int32 appId, Boolean includeContentGroups, Boolean resetAppGuid) in C:\\Projects\\2sxc\\2sxc\\Src\\Sxc\\ToSic.Sxc.WebApi\\Admin\\AppControllerReal.cs:line 88\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()"}

**Comment by iJungleboy** [comment] 2022-09-27 11:39
Sounds like restricted permissions on the server, probably similar to https://github.com/2sic/2sxc/issues/2857 

This could also be the cause of the initial issue you had. I'll close this for now, as it's probably not relevant to others, but feel free to add findings.

**Comment by eXistenZe** [comment] 2022-09-27 13:18
Cleared the "_ " dir, reset permissions, same error. No VS on the machine.
This only happened today after the 14.8 update.

**Comment by iJungleboy** [comment] 2022-09-28 14:38
@tvatavuk any guess on this?

**Comment by tvatavuk** [comment] 2022-09-28 15:36
The exception `The directory is not empty.` is unexpected, and this is second issue related to it. 

Issues are reported after commits where `SharpLipZip` was replaced with standard internal `System.IO.Compression` .net functionality so changes in that commit are suspect (in addition to unknown external process on web server that is blocking delete operation).

Exception should be result of [single line of code](https://github.com/2sic/eav-server/blob/2c04302dad1a1f06718a0301ac794b6cf53cf3a7/ToSic.Eav.Apps/ImportExport/ZipExport.cs#L167), where [standard **delete** .net method](https://learn.microsoft.com/en-us/dotnet/api/system.io.directoryinfo.delete?view=netstandard-2.0#system-io-directoryinfo-delete(system-boolean)) takes a care to delete folder and all its content (files and subfolders).
```cs
tempDirectory.Delete(true);
```
Deleting of temp folder is not critical functionality. It is there to keep folder `/_/` clean and empty.
Still exception on delete breaks critical **ExportApp** functionality.

As quick work around my suggestion it to wrap delete method with try-catch (with sink exception or just log internally).
```cs
try 
{	        
     tempDirectory.Delete(true);
}
catch () { /*sink exception*/ }
```

As next step I will investigate if `System.IO.Compression` could lock delete operation for some reason like late disposal.

**Comment by eXistenZe** [comment] 2022-09-28 15:55
Just a quick info: my "_ " dir had about 8 folders in it, so it was keeping old files from exported apps.

**Comment by eXistenZe** [comment] 2022-10-19 13:12
After upgrading my DNN installs to latest versions I am now unable to export any app.
3 different servers, one is my pc, so no permission issues.

**Comment by eXistenZe** [comment] 2022-10-19 13:14
Please reopen the issue.
I have quite a few projets in stand by due to this issue.

**Comment by tvatavuk** [comment] 2022-10-19 13:21
In latest 2sxc [v14.10.00](https://github.com/2sic/2sxc/releases/tag/v14.10.00) is fix for exception while deleting folder.

https://github.com/2sic/eav-server/blob/25492f67e579d81ce3f0549bd37b2f1d8d57167a/ToSic.Eav.Apps/ImportExport/ZipExport.cs#L193-L193

Please can You try on your side?

**Comment by tvatavuk** [comment] 2022-10-19 13:24
> Just a quick info: my "_ " dir had about 8 folders in it, so it was keeping old files from exported apps.

You can delete these 8 folders to keep it clean. 
Usually, that are just tmp files used to create export app zip, and that are not deleted because of exception in your environment (that I could not reproduce in dev env, but exiting fix should help for your case)

**Comment by eXistenZe** [comment] 2022-10-19 13:37
All my installs are now on 14.10.

Some more (a lot) of testing.
Within the same install, some apps export, others do not.
I have a site with a 2sxc blog module. It exports without issues. My custom app does not.
I deleted all folders within "_", cleared cache, restarted server, resynced files. Issue remains.

**Comment by tvatavuk** [comment] 2022-10-19 15:07
I see related problem. 

Here is simple workaround. 
- first click [Save state] 
- then click on [Export App]

![image](https://user-images.githubusercontent.com/2724850/196729139-a2ef05be-cf08-447a-8c52-48fc1bddfba3.png)

It should work.

It will be fixed in next release.

**Comment by eXistenZe** [comment] 2022-10-19 15:16
Awesome.

Thank you very much good sir.

**Closed** 2022-11-01 10:33 UTC
