### ISSUE TITLE
Razor/C#, for a Hyperlink field, Expecting Relative URL, But Getting Absolute

### ISSUE THREAD

**Issue by Accuraty** [2sic/2sxc#1658] opened 2018-12-13 00:17 UTC
I'm submitting a bug report Razor templating.

**Current behavior**
I have a field named, "CertPage", the Data Type if Hyperlink using the default Input Type. The Default Dialog is Page Picker, Image/ADAM/File Manager all false, and Buttons set to "page." In the field, it looks normal, I see "page:155", the correct TabID.

When I output it in Razor/C# like this:

`<a href="@cert.CertPage">`
 
I currently get the full URL

`<a href="http://www.mysite.com/cssp">`
 
Previously and according to the docs I can easily find, the **expected behavior** is that it would output a relative URL:

`<a href="/cssp">`

I can think of a number of solutions. One simple is to just do this instead:

`<a href="@(new Uri(cert.CertPage).PathAndQuery)">`
 
But I would prefer this was working as expected. Am I missing something? Is there a simple trick I am missing to get relative?

If it might be related, here is how I am getting at my data

```
@{
    var certRows = AsDynamic(App.Data["Certifications"])
        .OrderBy(c => c.CertSortOrder);
}
<html stuff>
@foreach(var cert in certRows) {
```
 

Windows Server 2016, .Net 4.7.x, IIS 8+
DNN 8.00.04, 2sxc 9.33.0
Any browser or language.

**Comment by iJungleboy** [comment] 2018-12-13 10:37
Internally the link resolution uses the DNN NavigateUrl command or something similar. So if this behavior changes, there must be something in DNN which changed - but it could be a simple as a primary-domain setting or something. 

So I would ask you to first verify, that it is a change (that previously it didn't include the domain), and then try to check on an installation that is different, what has changed in terms of DNN version or domain configuration. 

Since I presume this is not a change in 2sxc, I'll close this for now, but feel free to post your updates as I'll continue to answer it.

**Closed by iJungleboy** 2018-12-13 10:37 UTC

**Comment by iJungleboy** [comment] 2018-12-13 10:41
Another note: this could also be caused by some simple change like from http to https or something.

**Comment by Accuraty** [comment] 2018-12-13 15:32
Understood and agree. If I find the detail that reveals the behavior I will be sure to come back and share. I do think you are on the right track. This was a live project with an SSL, HTTPS-always-on, cloned... so this is happening on a staging/copy of the site and just HTTP again, no SSL.
