### ISSUE TITLE
Wrong language displayed after Edit, until F5

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#558] opened 2016-01-11 17:28 UTC
We get used to this and consider it as a minor issue, but users find it strange: best described below by our user:

there is some strange behavior on our website: We are on the german page, we edit content, and in the editor we switch to the English tab, edit the English text and then click on save. The text on the german webpage is then shown in English for some time…(until the page is refreshed), which is irritating.

**Comment by iJungleboy** [comment] 2016-01-13 06:46
Thanks. I believe this is a duplicate of #511

**Closed by iJungleboy** 2016-01-13 06:46 UTC
