### ISSUE TITLE
Adding New Item To List Not Showing But Instead Replacing Existing Item.

### ISSUE THREAD

**Issue by michaelcunningham1974** [2sic/2sxc#1784] opened 2019-06-26 19:31 UTC
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
Have a content module with a simple list. When I add a new item it replaces an existing record. If I do it again the same thing happens. If I then go to the admin and look at data all of the items exist. 

If I use the old UI it works as expected.

**Expected behavior**
This module worked as expected until upgrade to 10.1

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Fix previosly working module.

**Please tell us about your environment:**
Windows 10, DNN 9, 2SXC 10.1

* **2sxc version(s):** 10.1  
* **Browser:** [all
* **DNN:  9.X.X ] 
* **Language:** English

**Anything you would like to add**

**Comment by iJungleboy** [comment] 2019-06-27 09:37
Could you add some screenshots for clarification? Just so we're sure we're looking at the right issue.

**Comment by michaelcunningham1974** [comment] 2019-06-27 18:28
Sure I've uploaded a quick video.

[http://www.mdrealtor.org/Portals/0/video/2xsc_saving_issue.mp4](url)

**Comment by iJungleboy** [comment] 2019-06-28 07:42
Thanks for the video. I see that this doesn't look right. Some questions

1. is the view configured as list (I assume it is)
2. Could you paste the view code here - I'm not sure if the issue is in the dialog, or in the custom toolbar you're showing on top.

**Comment by michaelcunningham1974** [comment] 2019-06-28 14:25
Yes view is configured as list.
No demo item.
No presentation options
No header options

Pretty much a stock content list.

Menu is generated by:

@Edit.Toolbar(Content, actions:"new,instance-list",settings: new { show = "always" })

Github is mangling the src, file is attached.
[_code.txt](https://github.com/2sic/2sxc/files/3339622/_code.txt)

Thanks for all your help.

**Comment by Accuraty** [comment] 2019-06-28 15:09
Have you tried switching the Edit.Toolbar() to the newer Edit.TagToolbar()? Code sample can be injected from the snippets. 
 
Another experiment might be to temporarily get the ",replace" action out of there and see if that restores the expected behavior. Better, just inject the default toolbar and see if you get the same result.
 
Also, in the first line of you code, I've never seen "instance-list" before as an action, what is that? Why is it there?

One more thing, inside the foreach loop, add ",new" to the actions then use that button (+) to add a new Content item in place and see if that works as expected or does a Replace also.

**Comment by michaelcunningham1974** [comment] 2019-06-28 15:44
Ok tried using

`<div @Edit.TagToolbar(Content, settings: new { show = "always" })></div>`

Same issue.

Switching to default menu  on items also had no effect. 

Adding a "new" button to list  items had no effect.

Using old UI still works fine.

We use the instance-list to allow staff easy sorting of items in a list. It's drag and drop feature works well for us.

Thanks

**Comment by iJungleboy** [comment] 2019-07-01 09:39
I believe the issue is really with the new UI, or the backend of the new UI (we rebuilt it for performance reasons). We'll look into this.

**Comment by iJungleboy** [comment] 2019-07-01 21:14
I was able to reproduce the issue - it was quite complex but will be fixed in 10.02

**Closed** 2019-07-01 21:16 UTC
