### ISSUE TITLE
Dropdown from query always shows "item not found" in row create/edit after selecting the item

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1755] opened 2019-05-30 16:40 UTC
**I'm submitting a ...**
[x] bug report 

**...about**  
[x] Content Types or data management

**Current behavior**
I tested this in new apps and on previously working ones.
You create a query, test it, works.
Create a new table-entity. Create a new field, set it dropdown from query, select the query, stream, value field and label field. Everything works.
Try to create or edit an item in the table. If shows the label in the dropdown field, it sets the field, but after selecting from the dropdown, it now shows "item not found".

I think it's 9.40+ specific. Perhaps 10.

**Expected behavior**
After selection, show the label.

* **2sxc version(s):** 9.40

**Comment by iJungleboy** [comment] 2019-05-30 16:54
My understanding is that it's not nice, but doesn't break anything. is this correct?

This is a bug in the form. Do you know if it still applies to 2sxc 10, or if the problem is gone there?

**Comment by eXistenZe** [comment] 2019-05-30 17:20
Yes, updated to v10 today. Still there.

It's a nasty issue since it does not allow me to see what selection was made by label (when editing an item for example). The field is numeric so I need the label to read it.

But it does not break anything

**Comment by eXistenZe** [comment] 2019-05-31 08:44
Yes, updated to v10 today. Still there.

It's a nasty issue since it does not allow me to see what selection was
made by label (when editing an item for example). The field is numeric so I
need the label to read it.

But it does not break anything.

**Comment by eXistenZe** [comment] 2019-05-31 21:15
It now shows the value instead of "item not found", but I guess you already know that.
Only missing the last step to the label.

**Comment by iJungleboy** [comment] 2019-06-03 05:53
Sorry, didn't get that last comment "only missing the last step to the label" - could you explain?

**Comment by eXistenZe** [comment] 2019-06-03 08:00
The intended behavior is to show the label and not the value, right?

**Comment by iJungleboy** [comment] 2019-06-03 09:17
Yes, that's the goal. But if there is no label, we should show the value.

**Comment by iJungleboy** [comment] 2019-06-04 09:09
fixed in 10.02

**Closed by iJungleboy** 2019-06-04 09:09 UTC
