### ISSUE TITLE
Query will load all records

### ISSUE THREAD

**Issue by dotnetgeek** [2sic/2sxc#290] opened 2015-07-21 20:23 UTC
Hi,

I've an installation which have a lot of pages (4000) and 3 to 4 content modules per page. We ran into some performance problems in edit mode.

What I've seen is that a query will load more than 60T rows for the module e.g. while opening the a editor. 

From what I see there is a  where part missing because in some other cases I see that there is an addtion like "(606 = [Filter4].[PublishedEntityId])"

Thanks for looking into that,
Daniel

Here the query that woll load all data:

exec sp_executesql N'SELECT 
[UnionAll1].[EntityID] AS [C1], 
[UnionAll1].[AttributeSetID] AS [C2], 
[UnionAll1].[AttributeSetID1] AS [C3], 
[UnionAll1].[ChangeID] AS [C4], 
[UnionAll1].[C2] AS [C5], 
[UnionAll1].[EntityID1] AS [C6], 
[UnionAll1].[EntityGUID] AS [C7], 
[UnionAll1].[AttributeSetID2] AS [C8], 
[UnionAll1].[KeyGuid] AS [C9], 
[UnionAll1].[KeyNumber] AS [C10], 
[UnionAll1].[KeyString] AS [C11], 
[UnionAll1].[AssignmentObjectTypeID] AS [C12], 
[UnionAll1].[IsPublished] AS [C13], 
[UnionAll1].[PublishedEntityId] AS [C14], 
[UnionAll1].[Timestamp] AS [C15], 
[UnionAll1].[C1] AS [C16], 
[UnionAll1].[AttributeID] AS [C17], 
[UnionAll1].[AttributeID1] AS [C18], 
[UnionAll1].[C3] AS [C19], 
[UnionAll1].[ChildEntityID] AS [C20], 
[UnionAll1].[C4] AS [C21], 
[UnionAll1].[C5] AS [C22], 
[UnionAll1].[C6] AS [C23], 
[UnionAll1].[C8] AS [C24], 
[UnionAll1].[C9] AS [C25], 
[UnionAll1].[C10] AS [C26], 
[UnionAll1].[C11] AS [C27], 
[UnionAll1].[C12] AS [C28], 
[UnionAll1].[C13] AS [C29], 
[UnionAll1].[C14] AS [C30], 
[UnionAll1].[C15] AS [C31], 
[UnionAll1].[C16] AS [C32]
FROM  (SELECT 
	CASE WHEN ([Join4].[AttributeID1] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1], 
	[Project1].[EntityID] AS [EntityID], 
	[Project1].[AttributeSetID1] AS [AttributeSetID], 
	[Project1].[AttributeSetID2] AS [AttributeSetID1], 
	[Project1].[ChangeID] AS [ChangeID], 
	[Project1].[C1] AS [C2], 
	[Project1].[EntityID] AS [EntityID1], 
	[Project1].[EntityGUID] AS [EntityGUID], 
	[Project1].[AttributeSetID] AS [AttributeSetID2], 
	[Project1].[KeyGuid] AS [KeyGuid], 
	[Project1].[KeyNumber] AS [KeyNumber], 
	[Project1].[KeyString] AS [KeyString], 
	[Project1].[AssignmentObjectTypeID] AS [AssignmentObjectTypeID], 
	[Project1].[IsPublished] AS [IsPublished], 
	[Project1].[PublishedEntityId] AS [PublishedEntityId], 
	[Project1].[Timestamp] AS [Timestamp], 
	[Join4].[AttributeID1] AS [AttributeID], 
	[Join4].[AttributeID1] AS [AttributeID1], 
	CASE WHEN ([Join4].[AttributeID1] IS NULL) THEN CAST(NULL AS int) WHEN ([Join4].[AttributeID2] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C3], 
	[Join4].[ChildEntityID] AS [ChildEntityID], 
	[Join4].[SortOrder] AS [SortOrder], 
	CAST(NULL AS int) AS [C4], 
	CAST(NULL AS int) AS [C5], 
	CAST(NULL AS int) AS [C6], 
	CAST(NULL AS int) AS [C7], 
	CAST(NULL AS int) AS [C8], 
	CAST(NULL AS int) AS [C9], 
	CAST(NULL AS varchar(1)) AS [C10], 
	CAST(NULL AS int) AS [C11], 
	CAST(NULL AS int) AS [C12], 
	CAST(NULL AS int) AS [C13], 
	CAST(NULL AS int) AS [C14], 
	CAST(NULL AS bit) AS [C15], 
	CAST(NULL AS varchar(1)) AS [C16]
	FROM   (SELECT 
		[Filter1].[EntityID] AS [EntityID], 
		[Filter1].[EntityGUID] AS [EntityGUID], 
		[Filter1].[AttributeSetID1] AS [AttributeSetID], 
		[Filter1].[AssignmentObjectTypeID] AS [AssignmentObjectTypeID], 
		[Filter1].[KeyNumber] AS [KeyNumber], 
		[Filter1].[KeyGuid] AS [KeyGuid], 
		[Filter1].[KeyString] AS [KeyString], 
		[Filter1].[IsPublished] AS [IsPublished], 
		[Filter1].[PublishedEntityId] AS [PublishedEntityId], 
		[Filter1].[AttributeSetID2] AS [AttributeSetID1], 
		[Filter1].[AttributeSetID3] AS [AttributeSetID2], 
		[Extent4].[ChangeID] AS [ChangeID], 
		[Extent4].[Timestamp] AS [Timestamp], 
		1 AS [C1]
		FROM   (SELECT [Extent1].[EntityID] AS [EntityID], [Extent1].[EntityGUID] AS [EntityGUID], [Extent1].[AttributeSetID] AS [AttributeSetID1], [Extent1].[AssignmentObjectTypeID] AS [AssignmentObjectTypeID], [Extent1].[KeyNumber] AS [KeyNumber], [Extent1].[KeyGuid] AS [KeyGuid], [Extent1].[KeyString] AS [KeyString], [Extent1].[IsPublished] AS [IsPublished], [Extent1].[PublishedEntityId] AS [PublishedEntityId], [Extent1].[ChangeLogModified] AS [ChangeLogModified], [Extent2].[AttributeSetID] AS [AttributeSetID2], [Extent2].[AppID] AS [AppID1], [Extent3].[AttributeSetID] AS [AttributeSetID3]
			FROM   [dbo].[ToSIC_EAV_Entities] AS [Extent1]
			INNER JOIN [dbo].[ToSIC_EAV_AttributeSets] AS [Extent2] ON [Extent1].[AttributeSetID] = [Extent2].[AttributeSetID]
			LEFT OUTER JOIN [dbo].[ToSIC_EAV_AttributeSets] AS [Extent3] ON [Extent1].[AttributeSetID] = [Extent3].[AttributeSetID]
			WHERE ([Extent1].[ChangeLogDeleted] IS NULL) AND ([Extent3].[ChangeLogDeleted] IS NULL) ) AS [Filter1]
		LEFT OUTER JOIN [dbo].[ToSIC_EAV_ChangeLog] AS [Extent4] ON [Filter1].[ChangeLogModified] = [Extent4].[ChangeID]
		WHERE ([Filter1].[AppID1] = @p__linq__0) AND (@p__linq__1 <> cast(1 as bit)) ) AS [Project1]
	OUTER APPLY  (SELECT [Distinct1].[AttributeID] AS [AttributeID1], [Extent6].[AttributeID] AS [AttributeID2], [Extent6].[ChildEntityID] AS [ChildEntityID], [Extent6].[SortOrder] AS [SortOrder]
		FROM   (SELECT DISTINCT 
			[Extent5].[AttributeID] AS [AttributeID]
			FROM [dbo].[ToSIC_EAV_EntityRelationships] AS [Extent5]
			WHERE [Project1].[EntityID] = [Extent5].[ParentEntityID] ) AS [Distinct1]
		LEFT OUTER JOIN [dbo].[ToSIC_EAV_EntityRelationships] AS [Extent6] ON ([Project1].[EntityID] = [Extent6].[ParentEntityID]) AND ([Distinct1].[AttributeID] = [Extent6].[AttributeID]) ) AS [Join4]
UNION ALL
	SELECT 
	2 AS [C1], 
	[Project4].[EntityID] AS [EntityID], 
	[Project4].[AttributeSetID1] AS [AttributeSetID], 
	[Project4].[AttributeSetID2] AS [AttributeSetID1], 
	[Project4].[ChangeID] AS [ChangeID], 
	[Project4].[C1] AS [C2], 
	[Project4].[EntityID] AS [EntityID1], 
	[Project4].[EntityGUID] AS [EntityGUID], 
	[Project4].[AttributeSetID] AS [AttributeSetID2], 
	[Project4].[KeyGuid] AS [KeyGuid], 
	[Project4].[KeyNumber] AS [KeyNumber], 
	[Project4].[KeyString] AS [KeyString], 
	[Project4].[AssignmentObjectTypeID] AS [AssignmentObjectTypeID], 
	[Project4].[IsPublished] AS [IsPublished], 
	[Project4].[PublishedEntityId] AS [PublishedEntityId], 
	[Project4].[Timestamp] AS [Timestamp], 
	CAST(NULL AS int) AS [C3], 
	CAST(NULL AS int) AS [C4], 
	CAST(NULL AS int) AS [C5], 
	CAST(NULL AS int) AS [C6], 
	CAST(NULL AS int) AS [C7], 
	[Join10].[AttributeID3] AS [AttributeID], 
	[Join10].[AttributeID3] AS [AttributeID1], 
	CASE WHEN ([Join10].[ValueID1] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C8], 
	[Join10].[ChangeLogCreated] AS [ChangeLogCreated], 
	[Join10].[ValueID1] AS [ValueID], 
	[Join10].[ValueID1] AS [ValueID1], 
	[Join10].[Value] AS [Value], 
	[Join10].[ChangeLogCreated] AS [ChangeLogCreated1], 
	CASE WHEN ([Join10].[ValueID1] IS NULL) THEN CAST(NULL AS int) WHEN ([Join10].[ValueID2] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C9], 
	[Join10].[DimensionID1] AS [DimensionID], 
	[Join10].[DimensionID1] AS [DimensionID1], 
	[Join10].[ReadOnly] AS [ReadOnly], 
	CASE WHEN ([Join10].[ValueID1] IS NULL) THEN CAST(NULL AS varchar(1)) WHEN ([Join10].[ValueID2] IS NULL) THEN CAST(NULL AS varchar(1)) ELSE LOWER([Join10].[ExternalKey]) END AS [C10]
	FROM   (SELECT 
		[Filter4].[EntityID] AS [EntityID], 
		[Filter4].[EntityGUID] AS [EntityGUID], 
		[Filter4].[AttributeSetID4] AS [AttributeSetID], 
		[Filter4].[AssignmentObjectTypeID] AS [AssignmentObjectTypeID], 
		[Filter4].[KeyNumber] AS [KeyNumber], 
		[Filter4].[KeyGuid] AS [KeyGuid], 
		[Filter4].[KeyString] AS [KeyString], 
		[Filter4].[IsPublished] AS [IsPublished], 
		[Filter4].[PublishedEntityId] AS [PublishedEntityId], 
		[Filter4].[AttributeSetID5] AS [AttributeSetID1], 
		[Filter4].[AttributeSetID6] AS [AttributeSetID2], 
		[Extent10].[ChangeID] AS [ChangeID], 
		[Extent10].[Timestamp] AS [Timestamp], 
		1 AS [C1]
		FROM   (SELECT [Extent7].[EntityID] AS [EntityID], [Extent7].[EntityGUID] AS [EntityGUID], [Extent7].[AttributeSetID] AS [AttributeSetID4], [Extent7].[AssignmentObjectTypeID] AS [AssignmentObjectTypeID], [Extent7].[KeyNumber] AS [KeyNumber], [Extent7].[KeyGuid] AS [KeyGuid], [Extent7].[KeyString] AS [KeyString], [Extent7].[IsPublished] AS [IsPublished], [Extent7].[PublishedEntityId] AS [PublishedEntityId], [Extent7].[ChangeLogModified] AS [ChangeLogModified], [Extent8].[AttributeSetID] AS [AttributeSetID5], [Extent8].[AppID] AS [AppID2], [Extent9].[AttributeSetID] AS [AttributeSetID6]
			FROM   [dbo].[ToSIC_EAV_Entities] AS [Extent7]
			INNER JOIN [dbo].[ToSIC_EAV_AttributeSets] AS [Extent8] ON [Extent7].[AttributeSetID] = [Extent8].[AttributeSetID]
			LEFT OUTER JOIN [dbo].[ToSIC_EAV_AttributeSets] AS [Extent9] ON [Extent7].[AttributeSetID] = [Extent9].[AttributeSetID]
			WHERE ([Extent7].[ChangeLogDeleted] IS NULL) AND ([Extent9].[ChangeLogDeleted] IS NULL) ) AS [Filter4]
		LEFT OUTER JOIN [dbo].[ToSIC_EAV_ChangeLog] AS [Extent10] ON [Filter4].[ChangeLogModified] = [Extent10].[ChangeID]
		WHERE ([Filter4].[AppID2] = @p__linq__0) AND (@p__linq__1 <> cast(1 as bit)) ) AS [Project4]
	CROSS APPLY  (SELECT [Distinct2].[AttributeID] AS [AttributeID3], [Join9].[ValueID1], [Join9].[EntityID], [Join9].[AttributeID4], [Join9].[Value], [Join9].[ChangeLogCreated], [Join9].[ChangeLogDeleted], [Join9].[ValueID2], [Join9].[DimensionID1], [Join9].[ReadOnly], [Join9].[ExternalKey]
		FROM   (SELECT DISTINCT 
			[Extent11].[AttributeID] AS [AttributeID]
			FROM [dbo].[ToSIC_EAV_Values] AS [Extent11]
			WHERE ([Project4].[EntityID] = [Extent11].[EntityID]) AND ([Extent11].[ChangeLogDeleted] IS NULL) ) AS [Distinct2]
		LEFT OUTER JOIN  (SELECT [Extent12].[ValueID] AS [ValueID1], [Extent12].[EntityID] AS [EntityID], [Extent12].[AttributeID] AS [AttributeID4], [Extent12].[Value] AS [Value], [Extent12].[ChangeLogCreated] AS [ChangeLogCreated], [Extent12].[ChangeLogDeleted] AS [ChangeLogDeleted], [Join8].[ValueID2], [Join8].[DimensionID1], [Join8].[ReadOnly], [Join8].[ExternalKey]
			FROM  [dbo].[ToSIC_EAV_Values] AS [Extent12]
			LEFT OUTER JOIN  (SELECT [Extent13].[ValueID] AS [ValueID2], [Extent13].[DimensionID] AS [DimensionID1], [Extent13].[ReadOnly] AS [ReadOnly], [Extent14].[ExternalKey] AS [ExternalKey]
				FROM  [dbo].[ToSIC_EAV_ValuesDimensions] AS [Extent13]
				INNER JOIN [dbo].[ToSIC_EAV_Dimensions] AS [Extent14] ON [Extent13].[DimensionID] = [Extent14].[DimensionID] ) AS [Join8] ON [Extent12].[ValueID] = [Join8].[ValueID2] ) AS [Join9] ON ([Distinct2].[AttributeID] = [Join9].[AttributeID4]) AND ([Project4].[EntityID] = [Join9].[EntityID]) AND ([Join9].[ChangeLogDeleted] IS NULL) ) AS [Join10]) AS [UnionAll1]
ORDER BY [UnionAll1].[EntityID] ASC, [UnionAll1].[AttributeSetID] ASC, [UnionAll1].[AttributeSetID1] ASC, [UnionAll1].[ChangeID] ASC, [UnionAll1].[C1] ASC, [UnionAll1].[AttributeID1] ASC, [UnionAll1].[C3] ASC, [UnionAll1].[SortOrder] ASC, [UnionAll1].[C5] ASC, [UnionAll1].[C6] ASC, [UnionAll1].[C7] ASC, [UnionAll1].[C9] ASC, [UnionAll1].[C12] ASC',N'@p__linq__0 int,@p__linq__1 bit',@p__linq__0=2,@p__linq__1=0

**Comment by dotnetgeek** [comment] 2015-07-21 20:40
I'm not sure but it looks like that the query will be build here:

ToSic.Eav.EavContextRead line 389 (GetDataForCache).

**Comment by iJungleboy** [comment] 2015-07-28 14:34
thanks, we'll look into it. Can you tell me when the performance issue arrises? is it when loading a page in read-mode, in edit-mode or when opening or closing the edit-dialog?

**Comment by iJungleboy** [comment] 2015-08-07 07:20
Just fyi: it seems that the code which creates the edit-dialog has a mistake - it accesses the DB for the fields-configuration, when in reality all that is already in the cache. Could this be the cause of your issue?

**Comment by iJungleboy** [comment] 2015-10-06 22:09
Could you review this with the new 7.3 beta and tell us if it's better? I believe we did a lot in terms of performance...

**Comment by dotnetgeek** [comment] 2015-10-07 19:58
Yes, I will do this in the next days and let you know if the performance is better now. 

Thanks for tacking a look into the issue.

**Comment by dotnetgeek** [comment] 2015-10-16 18:46
Hi,

I try to install the Version 7.3.2 (https://github.com/2sic/2sxc/releases) and after the Module installation I see the message:

Der Typ "ToSic.Eav.WebApi.WebApi" in der Assembly "ToSic.Eav, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null" konnte nicht geladen werden.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.TypeLoadException: Der Typ "ToSic.Eav.WebApi.WebApi" in der Assembly "ToSic.Eav, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null" konnte nicht geladen werden.

Seems something is wrong with the package? 

I copy the assembly manually but nothing changes.

Have not enough time to check it now but will do it later.

**Comment by iJungleboy** [comment] 2015-10-20 19:12
This last error is because of some refactoring - the class moved to another dll. But we actually compensate for that - so your case seems to be one we missed. Do you get the error in the query-designer on in a page? could you maybe export the app which causes the issue so we can reconstruct where we forgot to replace the dll-name?

**Comment by dotnetgeek** [comment] 2015-10-20 19:22
I get the error for every request I do  - also for pages that dosn'nt contain this module (or an created app with that module).

**Comment by iJungleboy** [comment] 2016-01-17 17:09
Haven't heard about this since - probably closed. Will close now.

**Closed by iJungleboy** 2016-01-17 17:09 UTC
