### ISSUE TITLE
Bug in Basic Content template in 2sxc v13.11.00

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#2742] opened 2022-05-12 04:42 UTC
**I'm submitting a ...**   
[x] bug report 

**...about**   
[x] other / unknown

**Current behavior**   

In the Text | Image Basic Content template, the Image Caption is being ignored in favour of the content Title.

Basic Content control panel:

![2sxc 13 11 LTS - 1](https://user-images.githubusercontent.com/3846223/167992273-2a314cbb-0780-4b81-bf32-a781702ebb3f.jpg)

Web page before clicking on the image (I was expecting the image caption to show on the image):

![2sxc 13 11 LTS - 2](https://user-images.githubusercontent.com/3846223/167992423-5409dbe9-fec6-4b93-bcb3-6be5b358d474.jpg)

Expanded Image (should have had the caption "Beautiful Eddie" not "Siberian Cats"):

![2sxc 13 11 LTS - 3](https://user-images.githubusercontent.com/3846223/167992521-1e2408ab-3154-485f-ab59-4ad8ddfe2163.jpg)

**Expected behavior**   

Should behave like 2sxc v13.04.00 - see https://basilthetortoise.com/ as an example of correct behaviour.

**Instructions to Reproduce the Problem**

1. Create DNN 9.10.2 website
2. Add 2Shine BS5 theme (v5.0.2)
3. Install 2sxc13.11
4. Create page with Basic Content - Text ! Image

**Why change the behavior?** 

Breaks behaviour expected from previous 2sxc versions.

**Your environment**  

Windows 11, local IIS server, SQL Express

* **2sxc version(s):** 13.11 (works properly in v13.04.00)
* **Browser:** [all ]
* **DNN:** [9.10.2 ] 
* **Language:** [English ] - other languages not tested

**Anything you would like to add**

**Comment by iJungleboy** [comment] 2022-05-12 06:10
@skarpik thanks - the field should actually be removed, as the image caption is now stored on the image itself. 
@getBlup pls fix (remove field) and republish content-templates. also check if other templates still have this

**Comment by getBlup** [comment] 2022-05-12 09:35
@skarpik Thanks for submitting the bug report. The issue is fixed in the new release **13.10.03**. I removed the Image Caption field. With the new features you can set an image caption on the image itself. You can do this with the method shown on the image below. 

![2022-05-12_11-23-03](https://user-images.githubusercontent.com/67196160/168038810-c3b9e89d-f689-4799-8af2-fbdf3471f50f.png)

**Closed by getBlup** 2022-05-12 09:35 UTC

**Comment by skarpik** [comment] 2022-05-12 10:46
Thanks for the explanation.
