### ISSUE TITLE
During Edit.TagToolbar customization when moving edit button to a different group and adding a custom button everything breaks and whole page becomes unclickable.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [2sic/2sxc#2561] opened 2021-10-19 20:21 UTC
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**   
I was trying to make tagtoolbar first menu group contain 2 buttons: default edit button for certain entity object and custom button. However even though they work perfectly when used separately if I use both and click edit button - everything breaks. And I mean console has this error:
`ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: '3/9/edit'
Error: Cannot match any routes. URL Segment: '3/9/edit'`
and also whole page becomes unclickable so I have to reload the page to make anything work.

Here is the code I used:
`@Edit.TagToolbar(entityObj, toolbar: new[] { "-edit", "+group=mainGroup", "+edit&group=mainGroup", "+custom&icon=icon-sxc-cancel&group=mainGroup&color=red?call=customJsFunction&param1=" + entityObj.EntityId + "&param2=" + entityObj.Title })`

**Expected behavior**   
After applying code sample from above edit button should work.

**Instructions to Reproduce the Problem**

1. create some entity type and add at least one entity object there.
2. edit your cshtml file by adding to any div tag you like this code: `@Edit.TagToolbar(entityObj, toolbar: new[] { "-edit", "+group=mainGroup", "+edit&group=mainGroup", "+custom&icon=icon-sxc-cancel&group=mainGroup&color=red?call=customJsFunction&param1=" + entityObj.EntityId + "&param2=" + entityObj.Title })`
3. either add variable `entityObj` before this code and assign to it your entity object or edit variable name to pass there your entity object
4. save code changes and open the page in browser
5. click edit button and see error message in dev tools console and see the page that became not interactable (clicking anything doesn't work)

**Why change the behavior?**  
Because broken edit button for entity is crutial. It's basic CRUD functionality for module that is must have.

**Your environment**  
Windows 10
Visual Studio 2019

* **2sxc version(s):** 11.22.1  
* **Browser:** Chrome 94.0.4606.81
* **DNN:** 9.10.00
* **Language:** English

**Anything you would like to add**

**Comment by Constantine-Ketskalo** [comment] 2021-11-01 15:17
The only solution I found is to customize both edit and second custom button, and copy-paste js code for edit button from a working one on the page. But it doesn't seem to be the best solution, looks more like a crutch to me. I'm not sure on 100% but I think it was working on one of older versions of 2sxc. Could it be something in the code of one of updates for 2sxc module?

**Comment by Constantine-Ketskalo** [comment] 2021-11-01 23:18
Update: I've checked versions of 2sxc module used before and now and here's what I have:

- at first version 11.5.0 was used for the code sample I gave above.
- then it was updated to version 11.11.2
- then it was updated to version 11.22.1

Hope it helps.

**Comment by iJungleboy** [comment] 2021-11-04 11:10
Note: we just had a similar problem but then realized that the `entityObj` was null - so there was no ID. Could this be your mistake? Make sure it's a dynamic entity.

**Comment by Constantine-Ketskalo** [comment] 2021-11-06 23:24
> Note: we just had a similar problem but then realized that the `entityObj` was null - so there was no ID. Could this be your mistake? Make sure it's a dynamic entity.

No, that's definitely not the case. I've just double-checked it just in case.

**Comment by Constantine-Ketskalo** [comment] 2021-11-08 16:37
I'm getting list of entities using some code like this:

`IEnumerable<dynamic> listOfEntities = AsList(Data["VisualQueryOuputName"]);`

Then I go through this `listOfEntities` in a loop:

    @for (int i = 0; i < listOfEntities.Count(); i++)
    {
        dynamic singleEntity = listOfEntities.ElementAt(i);
        // some more code
    }

and every item gets some data displayed and also it's own tagtoolbar. Data is displayed correctly but tagtoolbar is broken as described above.

**Comment by iJungleboy** [comment] 2021-11-08 16:39
Just out of curiosity - we never use a `@for` loop - why don't you use a `@foreach` - it would be simpler?

If you use the foreach, does it still cause trouble, or does it work then?

**Comment by Constantine-Ketskalo** [comment] 2021-11-09 13:34
Yes, `@foreach` would be simpler, but I need index there, so I used `@for`. I've just tested `@foreach` loop, but it doesn't help.

**Comment by Constantine-Ketskalo** [comment] 2021-11-11 14:52
This is the code from a page source (via Ctrl+U):
`<tr class="dnnGridItem" align="left"  sxc-toolbar='{"toolbar":["-item-history","+item-history","-edit","+group=mainGroup","+edit&group=mainGroup","+custom&icon=icon-sxc-cancel&group=mainGroup&color=red?call=deleteItem&id=2977&name=Item Title"],"settings":null}'>`

This is the code from a dev tools "Elements" tab (RMB => inspect):
`<tr class="dnnGridItem" align="left" sxc-toolbar="{"toolbar":["-item-history","+item-history","-edit","+group=mainGroup","+edit&group=mainGroup","+custom&icon=icon-sxc-cancel&group=mainGroup&color=red?call=deleteItem&id=2977&name=Item Title"],"settings":null}" sxc-toolbar-hover="" data-tagtoolbar="1566-1566-0">`

P.S. I've edited it a little bit to avoid breaking NDA (`deleteItem` custom js function name and `Item Title` argument). But original has the same upper and lower case letters placing and same  space.

**Comment by iJungleboy** [comment] 2021-11-11 18:26
@Constantine-Ketskalo I believe your samples are from different code. The original

```
@Edit.TagToolbar(entityObj, toolbar: new[] { "-edit", "+group=mainGroup", "+edit&group=mainGroup", "+custom&icon=icon-sxc-cancel&group=mainGroup&color=red?call=customJsFunction&param1=" + entityObj.EntityId + "&param2=" + entityObj.Title })
```
can never produce what the last comment has:

```
<tr class="dnnGridItem" align="left" sxc-toolbar='{"toolbar":["-item-history","+item-history","-edit","+group=mainGroup","+edit&group=mainGroup","+custom&icon=icon-sxc-cancel&group=mainGroup&color=red?call=customJsFunction&id=2977&name=Item Title"],"settings":null}'>
```

What especially confuses me is the "-item-history", "+item-history". I assume the code has changed with time. Could you add another comment with the latest razor and latest output?

**Comment by Constantine-Ketskalo** [comment] 2021-11-12 00:34
You are right. The code is different. Probably that's because I was editing it in attempts to make it work and evantually I just deleted part of it and left miminum of the code that is enough to reproduce current issue. But that's great that you mensioned that because it has another issue as well. Probably related to current one.

Here is a razor code:
`<tr class="@(i % 2 == 0 ? "dnnGridItem" : "dnnGridAltItem")" align="left" @Edit.TagToolbar(itemObject, toolbar: new[] { "-item-history", "+item-history", "-edit", "+group=mainGroup", "+edit&group=mainGroup", "+custom&icon=icon-sxc-cancel&group=mainGroup&color=red?call=customJsFunction&id=" + itemObject.EntityId + "&name=" + itemObject.Name })>`

Here is page code (from dev tools):
`<tr class="dnnGridItem" align="left" sxc-toolbar="{"toolbar":["-item-history","+item-history","-edit","+group=mainGroup","+edit&group=mainGroup","+custom&icon=icon-sxc-cancel&group=mainGroup&color=red?call=customJsFunction&id=2977&name=Item Title"],"settings":null}" sxc-toolbar-hover="" data-tagtoolbar="1566-1566-0">`

So another issue with it is that I was trying to move history button to a different group of buttons, but result was that in a new version of 2sxc module an empty button appears there.
I beleive that all this code was working on older versions of a 2sxc module. I wouldn't commit code without checking it and it wouldn't be accepted without testing. Could this second issue have the same reason as a first one?

So as a summary of what I was trying to do here is to make a first group of menu contain edit and custom buttons and move the history button to second group.

**Comment by iJungleboy** [comment] 2021-11-17 18:05
I can reproduce. Still working on the cause, but it appears that...

1. The `Edit.Toolbar(...)` doesn't add the details for the item in the toolbar (server-side)
2. The dialog then opens, but since it errors, it will not properly initialize, so the click-to-close fails

...working on it

**Comment by iJungleboy** [comment] 2021-11-18 07:29
So here's the cause: 

the `toolbar` parameter can be different things - the old APIs gave it a complex tree-style object to configure the toolbar, and the new v10 API gives it an array of strings. 

It appears than under certain circumstances, the Razor compiler will treat the `new[] { "-item-history", "+item-history", "-edit", "+group=mainGroup", "+edit&group=mainGroup", "+custom&icon=icon-sxc-cancel&group=mainGroup&color=red?call=customJsFunction&id=" + itemObject.EntityId + "&name=" + itemObject.Name }` as an object[] instead of a string[], in which case ATM it assumes it's the old API, and doesn't process the parameters. 

I've updated the code to better detect this. as a workaround you can spend some time ensuring it's an `IEnumerable<string>` instead of an `IEnumerable<object>` and you could already fix this now, but a real fix will be in the next release.

**Closed** 2021-11-18 07:56 UTC

**Comment by Constantine-Ketskalo** [comment] 2021-11-18 17:44
Thanks a lot, @iJungleboy ! )
