### ISSUE TITLE
2sxc Does not report Error on Failed File Uploads

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2825] opened 2022-07-22 15:46 UTC
**I'm submitting a ...**
[x] bug report 

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**   
When a normal DNN user is logged, in a Role (e.g. Content Manager) and has Edit permissions (at the Page or Module level), and they try to drag n drop upload a ZIP file in it fails with NO error reported (no console error and no error in DNN Admin Logs).
 
If you immediately try a JPG instead, it just works.
 
As the person configuring the 2sxc App, without knowing the real problem/solution (need to add *.zip files to DNN's Settings/Security/More/More, **Default End User Extension Whitelist**), the problem seems like a Permissions issue.
 
This becomes a major issue when your use-case is: a logged in user with View (not Edit) permissions needing to do the same type of drag n drop upload to the content-type field. Since the .Zip doesn't work, and there is no error, you end up trying dozens of permissions additions/combinations, changing/testing other possibly related settings, turning Patron features on/off, and nothing seems to work and no errors. This can waste (has wasted) lots of time, cause frustration, and will probably result in false or confusing bug reports about permission problems.

**Expected behavior** 
The standard content-type record Edit UI (Angular) needs to be able to detect and report (bubble up) the correct error to the user.

**Instructions to Reproduce the Problem**
This is easy to reproduce. Tried it on a 2sxc v13.12.x site as well as v14.7.4.
 
Just use the Content App (or make an App with a content-type that has a field named ZipUpload of data type Hyperlink). Log in as a user in a Role (not Admin or Host) that you've already given Edit permissions to. Confirm *.zip is not already added to the Default End User Ext Whitelist. 

**Why change the behavior?**  
Get something easy and logical done in 1 to 2 minutes instead of 30 to 60 minutes and failing. :)

**Your environment**  

* **2sxc version(s):** 14.07.04 and same on v13.12.x and probably older versions
* **Browser:** all
* **DNN:** all (only tried on 9.10.02)
* **Language:** any/all

**Anything you would like to add**
Hoping you agree this is worth fixing in both v14 AND the v13 LTS.

**Comment by tvatavuk** [comment] 2022-08-08 09:19
Hi @jeremy-farrance, thx for reporting this issue 👌.
I can confirm that I reproduced this issue in DNN 9.6.1 (and DNN 9.10.2) with latest 2sxc v14.07.04 LTS.
Yes, the issue is that user notification is missing in UI on ADAM file upload exceptions.
It is expected to be fixed in future 2sxc versions.

**Comment by skarpik** [comment] 2022-08-08 20:16
Hello @tvatavuk - Version v14.07.04 LTS works perfectly for the file upload. However, v13.12.01 LTS does not work. I was trying to upload a 342 kb jpeg. The message that I got back is:

**Success: false, Error: "file too large - more than 2097152Kb↵file too large - more than 2097152Kb",…**

Please see the screen shot:
![Screenshot 2022-08-08 161244](https://user-images.githubusercontent.com/3846223/183506034-d256c8ed-b768-4dfb-a2f5-74061a398f2f.jpg)

I will also add the file that I tried to upload. There is nothing extraordinary about it:
![Smith-KM](https://user-images.githubusercontent.com/3846223/183506226-b740245d-e282-4641-a05b-656234fd6380.jpg)

Here are my details:

CMS - 2sxc v.13.12.01
Platform - Dnn v.09.10.02

Please let me know if you need any more information or if it would be helpful for me to run other tests.

**Comment by tvatavuk** [comment] 2022-08-09 09:47
Hi @skarpik and thx for more details.
Using your test example I was trying to reproduce your specific issue again in clean new install of DNN 9.10.2 + 2sxc 13.12.01 LTS but still no success :-(.
![image](https://user-images.githubusercontent.com/2724850/183613911-bffc91d5-414e-40a5-829b-2afe36593c7d.png)

Based on details you provided I can pin point to [exact line of code](https://github.com/2sic/2sxc/blob/b586a2a002ff1d604eb73b733a487c04403ab1fc/Src/Sxc/ToSic.Sxc.WebApi/Adam/AdamTransUpload.cs#L84) where this exception happens and this code is the same for v13.12.01 LTS and v14.07.04 LTS.

File upload stream for some reason return wrong byte length in your environment (> 2GB) and that is unexpected for many reasons. First you are uploading jpg image of 342 kb that is much less than 2GB. Also streams of more than 2GB should not be possible with **buffered stream** that are used in 2sxc as common default. There are also other reasons. Still more users reported the same issue, so there is something off that we are missing and that we need to find and solve. 

Because I still do not see issue with in 2sxc code, is it possible there is something specific or non-standard in your computer enviroment, like antivirus or firewall or some other network layer that could affect/block/change HTTP POST that to intrcept data to `/api/2sxc/app/auto/data/...` webapi endpoint?

**Comment by tvatavuk** [comment] 2022-08-09 10:03
Hi @skarpik, one more very wild guess.
Please can You try to temporary disable Imageflow (and ImageResizer ) http modules in your web.config in DNN?
Just find in `web.config/configuration/system.webServer/modules` your **imageflow** module registration (and or **imageresizer** module) and comment it, save web.config and test file upload again.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
...
  <system.webServer>
...
    <modules>
...
      <!-- <add name="ImageflowModule" type="ToSic.Imageflow.Dnn.ImageflowModule, ToSic.Imageflow.Dnn" /> -->
    </modules>
```

**Closed** 2022-08-10 13:45 UTC

**Comment by skarpik** [comment] 2022-08-10 22:21
I commented out ImageFlow and I got the same error. I have been doing the tests on a local DNN installation. 

I could put it on a server on DNN4Less.com and test it there. Is that worth the trouble? That should eliminate any issues with firewall issues (BTW - I'm running the Microsoft supplied firewall for Windows 11). 

I doubt that it is a FW problem. My website is on my computer. My client (the browser) is on my computer. The firewall should even see what is happening as my requests never leave my computer.

I will try installing DNN and 2sxc 13 LTS on a Windows 10 machine. Maybe that might show something interesting. It is very odd that it is working OK for you and not for me. Are you running Windows 10 or Windows 11?

Please confirm your set up:

DNN v9.10.2
2sxc v13.12.1 LTS
2shine v5.04

I want to make sure that I'm running exactly what you are (although I can't imagine that the theme will have any impact).

I also might try accessing the website on my workstation from a Linux box that I have on my network. Should not make any difference but by this time I'm desperate to try anything.

**Comment by tvatavuk** [comment] 2022-08-11 07:42
My dev env is Windows 11 Enterprise 21H2 using default Windows Defender (configured for development). 

For this issue, my test installations have default: DNN v9.10.2; 2sxc v13.12.01 LTS. Also installed latest 2shine.BS5_5.0.4_Install.zip with only visible side effect that the test site look nicer (as expected 😉). 

In chrome tested that ADAM uploads test image (using window file selector) without any issues from local drive, mapped drive, network share (so still can not reproduce this issue).

If you are willing I can send You my test installation zip's with file system backup and database backup (sql server 2019) so you can try to test it on your side (with goal to see is it issue related to your dev environment or something else). 

After this I also have one more idea You to try on your side in 5 mins.

**Comment by skarpik** [comment] 2022-08-11 16:40
On my Windows 10 computer, I set up a new install of DNN and 2SXC v13LTS and if worked. I don't know whether I am happy or sad. There is one more thing that I need to test. For all the DNN sites that I have under development or in production, I have installed Evotiva Backup. I'm going to create a new installation and then add Evotiva Backup. I am also going to set up the version that I created on Windows 10 to my Windows 11 box. I've tested to see whether removing Telerik makes any difference (I always remove Telerik) - it doesn't. Somewhere there is something that is messing things up.

Feel free to send me whatever you think might be helpful. You can send files via WeTransfer.com or whatever you like to steve.karpik@live.ca. Thanks.

**Comment by tvatavuk** [comment] 2022-08-11 22:14
To debug issues in dev env caused by windows security (defender, etc) I sometimes prefer to exclude project folders and files, dev services (sql server, iis) and tools (vs, code) from real time scanning, protection, blocking etc. effectively trading level of security for time that is lost in wondering what is wrong with my code (when real issue is not my code). Still W11 suprise me from time to time with unexpected security that sometimes blocks copying files from network share to my local documents, etc. All this security is usually great and needed but it takes a time to keep with all updates in that field. Problem is when this time is cut from my dev time. 
Good luck with debugging this issue.

**Comment by skarpik** [comment] 2022-08-15 18:30
@tvatavuk - please check your email. I believe I have found the culprit.

**Comment by tvatavuk** [comment] 2022-08-15 19:34
Thx! That is awesome :-). Tomorrow in the morning I will follow up on it.

**Comment by tvatavuk** [comment] 2022-08-16 06:17
Hi @skarpik, 
thx for great insights related to "file too large - more than 2097152Kb". I can confirm that in case that **web.config** configuration had `system.web/httpRuntime/@maxRequestLength` **>= 2097152** there was int overflow in our file size check.

![image](https://user-images.githubusercontent.com/2724850/184810445-714dddd4-1e7d-47bc-8dd9-528a21a6bc95.png)

This is fixed now.

![image](https://user-images.githubusercontent.com/2724850/184810590-83e6baf6-bcf4-4eab-b484-e4c2ecda33ea.png)

For v13.12.01 LTS (and v14.07.04 LTS) and this special case with maxRequestLength="2097152", as workaround, it is best to set value maxRequestLength="2097151" as max.
