### ISSUE TITLE
error rendering google maps - bootstrap template

### ISSUE THREAD

**Issue by dnastone** [2sic/2sxc#1271] opened 2017-08-28 06:42 UTC
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

with the latest version i get this rendering error with the bootstrap template location.
this happen after choosing the template when i create new data and click on save.
the demo data get's loaded correctly.

Error: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Die Laufzeitbindung kann für einen NULL-Verweis nicht ausgeführt werden. bei CallSite.Target(Closure , CallSite , Object ) bei ASP._Page_Portals_0_2sxc_Bootstrap__Location___Address_with_Map_50_50_cshtml.Execute() in d:\ftp\325040\argo.dnn.at\web\Portals\0\2sxc\Bootstrap\_Location - Address with Map 50-50.cshtml:Zeile 80. bei System.Web.WebPages.WebPageBase.ExecutePageHierarchy() bei System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) bei ToSic.SexyContent.Engines.RazorEngine.Render(TextWriter writer) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:Zeile 64. bei ToSic.SexyContent.Engines.RazorEngine.RenderTemplate() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:Zeile 74. bei ToSic.SexyContent.Engines.EngineBase.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Engines\EngineBase.cs:Zeile 87. bei ToSic.SexyContent.SxcInstance.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\SxcInstance.cs:Zeile 204.

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Razor templating
[x] JS development
[x] Content Types or data management
[x] APIs like REST
[x] DNN parts
[x] other / unknown

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 9.X.X  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [all | 7.4.2 | 8.X.X | 9.X.X ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

**Comment by iJungleboy** [comment] 2017-08-28 11:35
Which 2sxc version did you use? we had an issue which was just fixed, which made some numbers to be stored or loaded using a comma on DE systems. If you imported the app with a DE-portal, it would have demo-data using the wrong value. to test, please upgrade 2sxc and create a new portal, there install the app again - if it works there, it's the comma problem. 

To fix it in the existing system, just go through the admin-ui to the entity which contains this address and set the pin again, it will store a new number, now correctly (assuming one of the latest 2sxc).

**Comment by iJungleboy** [comment] 2017-08-28 11:36
Note: related to #1263

**Comment by dnastone** [comment] 2017-08-28 11:37
i used the version yu published today. i tested it with that version if the google maps error are gone.

**Comment by iJungleboy** [comment] 2017-08-28 11:42
The important question is if the maps-module was imported or edited in a slightly earlier version - that's when the data in the DB would have gotten the comma - which would have been ignored at runtime (resulting in a null-number, leading to this issue)

**Comment by dnastone** [comment] 2017-08-28 11:53
i created a new app on a test tab and choose the location app and then created an entry.
the error happen again

**Comment by iJungleboy** [comment] 2017-08-28 11:54
Ok, this sounds wrong. Could you give us more details incl. UI language, error-message and if you could, see what value is stored in the ...Values table for that field?

**Comment by dnastone** [comment] 2017-08-28 12:02
here are the screens from the data:

![screen1](https://user-images.githubusercontent.com/11678580/29772531-7bb1a0b4-8bf9-11e7-9034-d294f610b20c.jpg)
![screen2](https://user-images.githubusercontent.com/11678580/29772532-7bb49148-8bf9-11e7-8640-a1cb1f44b74b.jpg)

**Comment by iJungleboy** [comment] 2017-08-28 12:22
This looks like the bug I fixed in 9.4.3. You just said the version from today, I assume that was 9.4.3. Could you just re-check that editing in that version still loses the numbers?

**Comment by dnastone** [comment] 2017-08-28 12:58
maybe the error comes from the empty fields of long + lattitude?`
![screen3](https://user-images.githubusercontent.com/11678580/29774321-63954280-8c01-11e7-8586-92dd8edcec2b.jpg)

**Comment by iJungleboy** [comment] 2017-08-28 13:20
yes, this is correct. that was what the bug we fixed in the latest release.

**Comment by dnastone** [comment] 2017-08-28 13:21
i reinstalled the version 9.4.3 pre 2 but nothing changes.

**Comment by dnastone** [comment] 2017-08-29 07:45
hello, i tested it on my local machine too. and the error happend there too:
here are two screens:

![29-08-_2017_09-43-59](https://user-images.githubusercontent.com/11678580/29810094-d1abe61e-8c9e-11e7-96cd-1883a8f70fb8.jpg)

![29-08-_2017_09-44-29](https://user-images.githubusercontent.com/11678580/29810095-d1b60ffe-8c9e-11e7-8cc5-0314bae3f970.jpg)

**Comment by iJungleboy** [comment] 2017-08-29 08:40
I can reproduce it!
Sorry - will try to fix asap!

**Closed** 2017-08-29 09:41 UTC
Labels: show-stopper

**Comment by dnastone** [comment] 2017-08-30 08:53
with the new version pre 4 the google maps works again. :)
thanks!

**Comment by mangiove** [comment] 2018-10-05 10:03
Hello, it seems it is happening again at the moment.
I'm running the last version of DNN and 2sxc.
Lat and long value are not saved automatically cause of the dot in the value.
If I replace dot with comma before saving it is going fine.

**Comment by iJungleboy** [comment] 2018-10-10 12:44
Since this has been solved for over a year, could you verify that it's a 2sxc bug and not something surprising which just interfered?

**Comment by mangiove** [comment] 2018-10-16 07:36
Hello,
setting it in a new environment works fine...
I noticed that in the old environment lat and long filed were setted as string and that is not working, setting an int field everything is ok!
Can I ask if there is a fast way to set new fields to store that data and tranfer in it the old fields values? That is cause it is not possible to simply change the field type from string to int..
Thanks!

**Comment by iJungleboy** [comment] 2018-10-16 07:38
This is best done with export - then modify in excel - and then re-import. Check out https://2sxc.org/en/Learn/Import-Export
