### ISSUE TITLE
Content Type Fields: Moving fields to change order jumps in some cases

### ISSUE THREAD

**Issue by reaxx999** [2sic/2sxc#689] opened 2016-02-25 13:00 UTC
I have a 2sxc 8.1.3, and I am trying to change the order of content type fields. In some cases some fields are jumping, so it moves too far and the order is wrong. 

Basically, in my specific case and specific content type, I am not able to bring the fields in the right order, (neither with tricks from moving to other item up/down or somiething)

Please help :)

**Comment by iJungleboy** [comment] 2016-02-25 15:15
Duplicate of #431

**Closed by iJungleboy** 2016-02-25 15:15 UTC
