### ISSUE TITLE
Multiple cultures in date-time data type

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3187] opened 2023-09-25 10:05 UTC
### I'm submitting a

[x] bug report 
[x] not sure

### ...about
[x] Content Types or data management
[x] other / unknown

### Current Behavior / Expected Behavior
Date-time data type uses different cultures / formats in the form and list view.
I have a DNN install with english language in a portuguese culture server, so this could be a sign of that.

### Instructions to Reproduce the Problem
Create a field with date-time data type (doesn't matter if it has time associated or not).
Open the form and fill a date.
![image](https://github.com/2sic/2sxc/assets/26518879/feede180-e792-407d-b3ee-4f1afb7709b9)

Close the form and check the list view in the admin panel.
![image](https://github.com/2sic/2sxc/assets/26518879/4d21e939-094e-48f9-a47d-d473b44fd8a6)

### Your environment

* **2sxc version(s):** 16.5.0
* **Browser:** Firefox XX
* **DNN:** all | 9.11.02
* **Language:** English - Portuguese Culture

**Comment by iJungleboy** [comment] 2023-09-26 05:24
Hi @enfJoao 

From what I can see the data shown is correct. It's just shown in the international neutral/standard format and not in a culture specific way. This is by design. 

The list view uses the ISO standard, which is important to ensure proper sorting. 
We don't plan on localizing this, as it would increase complexity by quite a lot.

I also assume nobody would want to invest the time to make this happen, so I'll close this for now. 
If someone wants to sponsor this, we can reopen it.

**Closed by iJungleboy** 2023-09-26 05:24 UTC
