### ISSUE TITLE
Multilingual editing : blue line above the current language wrong initial positionning

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#446] opened 2015-11-17 17:39 UTC
When editing a content in a multilingual context, a little blue line above the language name tells the users what language she is editing. This works well once they've changed the language, but the initial positioning is over the top left language no matter what language you are in.
i.e. My primary language is french and I'm working in the English zone, then French will be overlined when I enter editint the content of an App. After a language change everything get back as it should

**Comment by BravoSierra** [comment] 2015-11-17 17:41
![capture](https://cloud.githubusercontent.com/assets/5261858/11219461/d4cc25d8-8d5a-11e5-9bbf-170a0179c90f.JPG)

**Comment by raphael-m** [comment] 2016-02-23 15:04
Can't reproduce this anymore, I assume this has been fixed with other changes.

**Closed by raphael-m** 2016-02-23 15:04 UTC
