### ISSUE TITLE
Changing language tab does not automatically save the content of the current language

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#540] opened 2015-12-22 18:11 UTC
With a new Content module, if the user edits the content in the first language, and then click the tab of another language without saving the first one, the content of the first language is not automatically saved, and therefore is lost.

This seems to be new since v8. Before, the current content was automatically saved before you would switch to another language.

The consequence is not only that the content of the first language is lost, but also that it is not possible any more to edit the content in the first language (no more textbox).

How to reproduce:

1. Create a new bilingual content module.
2. edit some content in the first language
3. Click the secondary language tab, (without Saving the current primary language)
4. Observe that the content of the first language has not been saved
5. You cannot edit the first language anymore (e.g. no Textbox)

**Comment by iJungleboy** [comment] 2015-12-23 07:56
Ok, sounds like something needing a fix. Thx. Can we put this in the normal backlog or do you need it prioritized / sponsored?

**Comment by BravoSierra** [comment] 2016-01-07 16:23
Please add to the normal backlog, thanks

**Comment by raphael-m** [comment] 2016-02-23 15:14
Switching languages no longer saves the content automatically, this is by design.
I'm not able to reproduce the other issues, in my tests the content of the first language is still editable when switching back to the default language. I assume this has been fixed with other changes.

**Closed by raphael-m** 2016-02-23 15:14 UTC
