### ISSUE TITLE
Insert Very Rich Content

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#1829] opened 2019-09-25 20:58 UTC
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 
[x] not sure

**...about**   
[x] edit experience / UI

**Current behavior**
No idea how to insert _very rich content_

**Expected behavior**
When I hoover the rich content area, the app/content placeholder appears:  
![image](https://user-images.githubusercontent.com/5693190/65639440-6caa0800-dfe8-11e9-8284-7717cecbd2f5.png)

**Minimal reproduction of the problem with instructions**

- Install DNN9.4
- Install 2sxc 10.06
- Install latest News app
- Add a news, and Insert an area for rich text
- Save and view that news article

**Anything you would like to add**
I guess I miss something obvious. I also tested with blog.

**Comment by iJungleboy** [comment] 2019-09-26 06:19
@SCullman are you not sure how to use it (like in the blog) as an editor, or are you trying to add very-rich-content to a wysiwyg on a content type of yours?

**Comment by SCullman** [comment] 2019-09-26 06:38
I think I'm doing everything right. So I think I found a a bug.

**Comment by iJungleboy** [comment] 2019-09-27 09:16
Didn't find time to look at it yet, but if it is as you say, then it's a major bug, thx!

**Comment by raphael-m** [comment] 2019-09-27 14:52
I can reproduce this problem:
* It seems like `@ToSic.SexyContent.ContentBlocks.Render.All` does not output the div tag with attributes which would trigger a toolbar when hovering.
* Even when using the "old" method with `@Edit.ContextAttributes` and a `foreach` loop, the toolbar does not appear.

**Comment by iJungleboy** [comment] 2019-10-01 13:20
I think I found the cause - it's the new UI. The placeholder added isn't quite what it should be - with the old UI it still seems to work.

**Comment by iJungleboy** [comment] 2019-10-01 21:46
There seem to be 2 bugs. One is the new UI, the other is an ID-Lookup. So you'll see two commits to fix this.

**Comment by iJungleboy** [comment] 2019-10-02 08:07
fixed in next release.

**Closed by iJungleboy** 2019-10-02 08:07 UTC
Labels: bug:major
