### ISSUE TITLE
Administrator cannot 'Edit Template'

### ISSUE THREAD

**Issue by hbuchel** [2sic/2sxc#216] opened 2015-04-29 18:11 UTC
I'm using 6.2.0 with DNN07.03.02

I have users that have the administrator role that cannot edit any of the 2SXC templates through the 'Edit Template' window. This is their process:

1. Hover over pencil icon when in edit mode in DNN
2. Choose 'Edit Template' from the menu that pops up.
3. The code from the template is viewable, but is grayed out and disabled so the user cannot click into the textarea to edit anything.

They have the administrator role, and I also created a role called "2SexyContent Designers" like the documentation mentioned, and I added that user to that role. I also manually added the 2SexyContent Designers role to the 2SXC module they are trying to edit, and they still cannot edit it.

Any idea why they cannot edit the templates from this option or is there a step I missed?

**Comment by iJungleboy** [comment] 2015-04-30 06:05
Could it be that this only happens with Razor templates?

**Comment by iJungleboy** [comment] 2015-05-19 15:39
No feedback received. Assume it was a razor template - which by design is only host-editable because of security reasons. Closing this.

**Closed by iJungleboy** 2015-05-19 15:39 UTC
