### ISSUE TITLE
Edit UI Showing Wrong Date by Two Days

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2982] opened 2023-01-16 20:20 UTC
### I'm submitting a ...
[x] bug report 

### ...about
[x] edit experience / UI

### Current Behavior
If you have a date already stored in a field, when displayed it is 2 days less. E.g. 12/31/2022 shows as 12/29/2022.
 
Also, if you delete the contents of the date field in the edit UI, move out of the field, then go back to the field and try to enter a date, upon leaving the field it changes, subtracts 2 days. E.g. enter 1/4/2023 and upon tabbing out of the field the display changes to 1/2/2023.
 
It is important to note that when stored (saved) the date is correct, its just displaying wrong and changing in the edit UI when the field loses focus.

### Expected Behavior
Dates should not change.

### Instructions to Reproduce the Problem

I have included a video so you can see the issue in action:
https://user-images.githubusercontent.com/653301/212758569-d7517160-0f88-4d9e-860d-016efac1b0c0.mp4

### Your environment**
* **2sxc version(s):** 14.12.3 
* **Browser:** all (tried in Chrome 109 and Edge 109, same)
* **DNN: only tried in 9.10.02
* **Hosting platform:** IIS on Windows Server 2019 
* **Language:**  tried on English only

### Comments

This is happening on all Content Types with dates whether or not they have a time 
It happening to CTs with and without any formulas. 
The example in the video has no formulas, but does show a formula error (which is weird, no?)
There are no console errors and no errors being logged anywhere that I can find.
This is happening on two projects that were both recently upgraded to 14.12.3 LTS and in both cases the client has reported the issue.

**Comment by DujeVatavuk** [comment] 2023-01-17 16:26
Can you please specify timezones and cultures/regional formats for server and browser.

**Comment by jeremy-farrance** [comment] 2023-01-17 19:25
Everything is default US English,  none of our projects touch or change cultures/languages, so 'en-us' or default.

Browser is also installed default, no changes, Preferred language in Chrome settings shows "English (United States)."

Server time zone is US Central, UTC -6
Local workstation time zone is US Central, UTC -6
  
DNN is set to Central Time (US & Canada), UTC -6
https://i.imgur.com/TS8ALtZ.png

If you need me to check anything else, please be specific, above is all I can think of at the moment based on what you requested.

**Comment by iJungleboy** [comment] 2023-01-26 15:56
Seems to have been an issue with time zones which are UTC minus something.
should be fixed in 15.01

**Comment by jeremy-farrance** [comment] 2023-01-26 16:01
This is still urgent, the clients are aware of the problem and one of them has chosen to stop doing data entry until we fix it. I need 2 of the sites affected by this to stay on LTS. Can it be fixed in v14.12.3+ ?
 
If not, is there a way to patch v14.12.3 manually?

**Comment by jeremy-farrance** [comment] 2023-01-26 20:25
Please re-open, see above comment.

**Comment by iJungleboy** [comment] 2023-01-27 08:51
Let's do the following:

* 2sxc 15.01 should be out in a day or two, please test to verify if the problem is fixed
* If it is fixed, we'll then evaluate if we can backport this simple change, maybe make a special patch-release of the UI JS only

**Comment by jeremy-farrance** [comment] 2023-02-02 00:45
Daniel, as I have brought up in the past, I am still concerned about your LTS Policy. I thought this was a clear case where an LTS fix for v14.12.x made sense [according to you own LTS Policy](https://docs.2sxc.org/abyss/releases/management/policy-lts.html).

You made the following 3 releases in Nov 2022, all labelled LTS:

- 14.12 LTS (14.12.01) on Nov 11, 2022
- 14.12.02 LTS on Nov 17, 2022
- 12.12.03 LTS on Nov 29, 2022
 
We are **still within 3 months** of all 3 of those LTS release dates.
 
The only debate I see is whether or not this bug qualifies as "2.2 Critical bug fixes." In our case this affected 2 clients and one of them stopped using the software until we could fix it. To us and our client this was critical and they chose to completely stop use of the app we built for them until its fixed. 
 
Please understand that I don't actually expect you to change your policy, but I would like to humble suggest that you stop using the LTS label on releases. I feel that it creates (industry standard) expectations which I don't think you are currently following.

**Comment by jeremy-farrance** [comment] 2023-02-02 01:12
Okay, cloned the project and installed 15.01, yes, the issue with the dates being off by 1 or 2 days in the Edit UI **is fixed.**  Woot!!
 
But I quickly found 2 new issues (non-critical I think) that I will investigate further and create new Issues for (soon)...

Views now show an error at the top:

- Normal logged in users see: "Error Showing Content - please login as admin for details."
- Host users now see: "Error: Condition 'feature.PublicEditForm' is not met. The feature 'PublicEditForm' is not enabled - see https://r.2sxc.org/features."
 
Item History no longer works:

![image](https://user-images.githubusercontent.com/653301/216206404-ace101df-5b9f-4940-8441-03365ae813d1.png)

**Comment by iJungleboy** [comment] 2023-02-02 06:42
@jeremy-farrance Regarding LTS

We do need a way to mark stable releases, as 2sxc releases much more often that people like to upgrade ;). So it needs a marker to designate releases which we tested more - since most agencies will prefer to install only these. LTS seems the best designator for this.

For the 14.12.01/02/03 LTSs: Only the last one is the valid one. We don't have a versioning system to sub-patch a sub-version. So if an LTS needs a fix, we need to create a new version for clarity.

Yes, we're still within those 3 months of 14.12.03.

Is the date bug major: I believe it is certainly fairly big. Will we patch it?
I believe it's important enough to probably do it. At the end of the day it's volunteer work. 
The main difficulty is re-releasing an old version and testing it takes about 4 hours of work. 
For any kind of guarantee someone to contribute it.
That's the idea behind open source - we're not the only ones responsible 😉

So will I personally get it fixed?
Not sure yet, because I'll be on vacation next week and releasing an LTS before that is just not wise.
And after that I hope to release 15 LTS as there's another feature related to FIPS that's also a show-stopper for someone, so getting this LTS is very important too.

**Comment by iJungleboy** [comment] 2023-02-02 06:44
@jeremy-farrance 

**Regarding the second issue: The Feature-not-enabled**

This is because the fingerprint of the system changes with a major upgrade. All you need to do is re-activate the registration.

**#3 CJson column**

This looks bad. Basically this implies that some upgrade SQL didn't run, because we had to rename some columns in the DB which should be installed on v15.00 - of course also on 15.01. I assume you did a direct upgrade from 14.12.x to 15.01.

@tvatavuk could you look into this ASAP?

**Comment by jeremy-farrance** [comment] 2023-02-02 15:26
Okay, the (SQL) quick fix worked, History is working again. 
 
A suggestion regarding the Patron registration re-activation, this is confusing (still, to me). If a major version upgrade will always invalidate the reg, I would like to recommend that you improve the error message (for hosts) and include a link to make the re-active as obvious as possible. 
 
Thank you again for 2sxc, all the great work you and your team do, and the quick, informative responses!

**Comment by david-poindexter** [comment] 2023-02-02 16:33
> @jeremy-farrance Regarding LTS
> 
> We do need a way to mark stable releases, as 2sxc releases much more often that people like to upgrade ;). So it needs a marker to designate releases which we tested more - since most agencies will prefer to install only these. LTS seems the best designator for this.
> 
> For the 14.12.01/02/03 LTSs: Only the last one is the valid one. We don't have a versioning system to sub-patch a sub-version. So if an LTS needs a fix, we need to create a new version for clarity.
> 
> Yes, we're still within those 3 months of 14.12.03.
> 
> Is the date bug major: I believe it is certainly fairly big. Will we patch it? I believe it's important enough to probably do it. At the end of the day it's volunteer work. The main difficulty is re-releasing an old version and testing it takes about 4 hours of work. For any kind of guarantee someone to contribute it. That's the idea behind open source - we're not the only ones responsible 😉
> 
> So will I personally get it fixed? Not sure yet, because I'll be on vacation next week and releasing an LTS before that is just not wise. And after that I hope to release 15 LTS as there's another feature related to FIPS that's also a show-stopper for someone, so getting this LTS is very important too.

@iJungleboy I very much appreciate the realities of what you are saying here.  Might I suggest simply using the term "Stable" since that is what you seem to actually mean?  Long Term Support (LTS) implies...well, long-term support.  Many clients take this term VERY seriously, and it means something VERY different than what I believe you all are trying to provide.  It would really help us and other agencies using 2sxc if we just mitigate this concern altogether and I sincerely believe staying away from the LTS designation will help with the optics and expectations for all involved.  Thank you for your consideration!

**Comment by david-poindexter** [comment] 2023-02-02 22:12
@iJungleboy hehe - maybe just remove the designation altogether and call out `Stable & Tested` in the release notes?  :)

**Comment by iJungleboy** [comment] 2023-02-03 07:06
@david-poindexter that's not enough. many teams explicitly only use the LTS releases, so it must be very clear - not just some note somewhere...

**Comment by david-poindexter** [comment] 2023-02-03 07:38
> @david-poindexter that's not enough. many teams explicitly only use the LTS releases, so it must be very clear - not just some note somewhere...

Okay, hopefully you'll come up with something that works for all then.  I really appreciate you understanding that "LTS" is causing serious struggles for many of us with clients.

**Comment by iJungleboy** [comment] 2023-02-21 00:07
Just fyi: pls help test the latest 15.03 - if everything works well, we plan to release an "LTS" within days - hopefully fixing your issue here without needing a back-port.

**Closed by iJungleboy** 2023-02-21 00:07 UTC
Labels: affects:LTS
