### ISSUE TITLE
Oqtane - Error compiling AppCode.dll

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3505] opened 2024-11-14 10:46 UTC
### I'm submitting a
[x] bug report

### ...about
[x] other / unknown

### Current Behavior / Expected Behavior
Importing apps from DNN to test in Oqtane. Some work with no issues, other report this:

`Error: System.Exception: Error: Can't compile 'AppCode.dll' in AppCode. Details are logged into insights. Bad IL format. The format of the file ' .... \App_Data\2sxc.bin\App-00006-AppCode-5c98a772de834cf2f6cbaba95a058d43347c40224e3ac673b0d60a04183c20b8.dll' is invalid. at ToSic.Sxc.Razor.RazorCompiler.FindViewAsync(ActionContext actionContext, String partialName, IApp app, HotBuildSpec spec) at ToSic.Sxc.Razor.RazorCompiler.CompileView(String partialName, Action`1 configure, IApp app, HotBuildSpec spec) at ToSic.Sxc.Razor.RazorRenderer.RenderToStringAsync[TModel](String templatePath, TModel model, Action`1 configure, IApp app, HotBuildSpec hotBuildSpec) at ToSic.Sxc.Razor.RazorEngine.RenderTask(RenderSpecs specs)`

This is the content of the folder:
![image](https://github.com/user-attachments/assets/828c9435-6c37-4cf8-a618-958a4ad927e2)

### Instructions to Reproduce the Problem
Load any view (from specific apps with no significant differences).

### Your environment
* **2sxc version(s):** 18.02.00
* **Oqtane:** 5.2.4
* **Hosting platform:** IIS

**Comment by iJungleboy** [comment] 2024-11-14 15:02
@tvatavuk any ideas?

Is there a chance that two compilers try to create the file at the same time, and refuse to overwrite a 0-byte file or something?

**Comment by enfJoao** [comment] 2024-11-14 15:08
Deleted the files in the folder, restarted the server, same output. One app generates the files, the other generates the errors.
![image](https://github.com/user-attachments/assets/db79d11d-665d-43da-8808-c7212450438d)

![image](https://github.com/user-attachments/assets/287de023-bb82-4e8a-b73d-40bdb39d54f1)

**Comment by enfJoao** [comment] 2024-11-25 08:54
Any news on this fix?

I've been trying 2sxc on Oqtane for a couple months now, and evertime I got stalled by one or another error.

**Comment by iJungleboy** [comment] 2024-11-26 08:55
I believe @tvatavuk will look into this this week.

**Comment by jaruiz1961-ual** [comment] 2024-11-26 13:13
I have had the same problem with oqtane 6.0 for .NET 9.0
Cheers

**Comment by enfJoao** [comment] 2024-11-27 16:05
Win 11 pro 24H2
Release version
Windows defender only, but the issue happens with it on or off.
Local M.2 (One partition for win, one for IIS sites).

There is only one app in the page.
This app is configured the exact same way that a couple others are. The others work fine.
The only difference is that this problematic one is a lot bigger in entity types and data.
This same app runs on DNN on the same server.
If I delete the dlls, the app will run once. As soon as I reload, the error will pop.

I cannot share the app since there is sensitive data on in.

**Comment by tvatavuk** [comment] 2024-11-29 15:29
@enfJoao Thank you for providing the additional information — it was very helpful in narrowing down the test cases as I worked to reproduce the issue in my development environment. I conducted tests with several large applications (1k+, 10k+ and 50k+ entities), and everything appeared to work as expected, so unfortunately, I was not successful in reproducing the issue on my setup. 

![image](https://github.com/user-attachments/assets/ecbf5386-d8d8-4487-9a3c-d581094d8e89)

However, based on details in your report, I have added some code to prevent the locking of `App_Code*.dll` during compilation in the Oqtane version. On my side, this change has already shown noticeable improvements in performance, which is a positive outcome. This fix is expected to be included in the next release. 

If you're willing (and/or @jaruiz1961-ual), it would be great if you could test this on your Oqtane setup. I can provide you with today's build from the development branch: `ToSic.Sxc.Oqtane.Install.18.4.0-fix3505.nupkg`. Let me know if you'd like to try it!

**Comment by enfJoao** [comment] 2024-11-29 15:32
@tvatavuk sure.

**Comment by tvatavuk** [comment] 2024-11-29 15:43
> @tvatavuk sure.

Here is link on my OneDrive [ToSic.Sxc.Oqtane.Install.18.4.0-fix3505.nupkg](https://sistemi-my.sharepoint.com/:u:/g/personal/tonci_sistemi_onmicrosoft_com/EQanxdYg-bNKiAiX5jJ4f6YBGWpLjf10_nel5RE6Lukt4Q?e=ID1gl1)

**Comment by enfJoao** [comment] 2024-11-29 20:09
I'm having issues installing modules, but I think I got it (ToSic.Sxc.Oqtane.Install.18.4.0-fix3505.log seems to point that way).
https://github.com/oqtane/oqtane.framework/issues/4884

New error:
Error: System.Exception: Error: Can't compile 'AppCode.dll' in AppCode. Details are logged into insights. Image is too small. at ToSic.Sxc.Razor.RazorCompiler.FindViewAsync(ActionContext actionContext, String partialName, IApp app, HotBuildSpec spec) at ToSic.Sxc.Razor.RazorCompiler.CompileView(String partialName, Action`1 configure, IApp app, HotBuildSpec spec) at ToSic.Sxc.Razor.RazorRenderer.RenderToStringAsync[TModel](String templatePath, TModel model, Action`1 configure, IApp app, HotBuildSpec hotBuildSpec) at ToSic.Sxc.Razor.RazorEngine.RenderTask(RenderSpecs specs)

Also creates an empty dll.
Deleting the dll does not fix it (it just recreates the empty file again).
I'm trying to strip the app down to bare minimum to see if I can share it.

**Comment by enfJoao** [comment] 2024-11-29 20:21
Ok... This was a lot faster than I expected.
As soon as I deleted the AppCode folder, the issue is gone.
To trigger this issue in any Oqtane 2sxc I just have to create an AppCode folder (even if empty) and add the line @using AppCode (even if no actual .cs is called).

**Comment by tvatavuk** [comment] 2024-12-02 22:50
> I'm having issues installing modules, but I think I got it (ToSic.Sxc.Oqtane.Install.18.4.0-fix3505.log seems to point that way). [oqtane/oqtane.framework#4884](https://github.com/oqtane/oqtane.framework/issues/4884)

The issue you are encountering with module installation might be related to a OS limitation on IIS10 when running on desktop versions of Windows 10/11. This limitation stems from the capped number of concurrent network connections, which can cause uploads to freeze if the JavaScript responsible for splitting large uploads into smaller batches exceeds the connection limit. This problem does not occur on Windows Server, where the connection cap is higher.

Workaround
To bypass the upload issue, you can manually place the NuGet package into the `/Packages` folder of your Oqtane installation and then restart the application. This will trigger the module nuget installation process without requiring the web-based upload.

**Comment by tvatavuk** [comment] 2024-12-03 00:35
@enfJoao, could you please share your stripped-down app that demonstrates the issue? I'm still unable to reproduce it on my end.

You mentioned:

> Ok... This was a lot faster than I expected. As soon as I deleted the AppCode folder, the issue is gone. To trigger this issue in any Oqtane 2sxc I just have to create an AppCode folder (even if empty) and add the line `@using AppCode` to the template (even if no actual .cs is called).

Based on this, it seems that the presence of an `AppCode` folder and the usage of `@using AppCode` in the template—even without any actual `.cs` files—triggers the issue. I did try to replicate this scenario to see if I can reproduce the problem. Here's what I've done:

- Performed a clean install of **[Oqtane.Framework.5.2.4.Install.zip](https://github.com/oqtane/oqtane.framework/releases/download/v5.2.4/Oqtane.Framework.5.2.4.Install.zip)**
- Installed **[ToSic.Sxc.Oqtane.Install.18.2.0.nupkg](https://github.com/2sic/2sxc/releases/download/v18.02.00/ToSic.Sxc.Oqtane.Install.18.2.0.nupkg)**
- Installed all default 2sxc content and app templates
- Installed an almost empty **[2sxcApp_i3505_0.0.18.zip](https://github.com/user-attachments/files/17985399/2sxcApp_i3505_0.0.18.zip)**

Everything is working as expected, and I can't reproduce the issue you're experiencing.

![image](https://github.com/user-attachments/assets/1c858040-d8d3-47df-a783-fdb6d3ed728b)
![image](https://github.com/user-attachments/assets/1edf7942-1d1d-4058-8d30-8e3667a76deb)
![image](https://github.com/user-attachments/assets/391482a2-3510-430a-934a-fd10c363359d)

Any additional details or a sample app would be greatly appreciated to help diagnose and resolve this issue.

**Comment by tvatavuk** [comment] 2024-12-03 13:33
Thank you for the detailed feedback—it has been very helpful in narrowing down the issue.

- I was able to reproduce the problem, and as suspected, the `AppCode.dll` being generated with a file size of 0 is indeed unexpected.
- This behavior is not helpful for developers using 2sxc in identifying and resolving issues.
- The expected behavior should align more closely with DNN's handling of uncompiled C# code. Specifically:
  - If the code in `AppCode` contains errors, it should result in a meaningful error message indicating the issue, rather than generating a corrupted or empty `AppCode.dll`.
  - No `AppCode.dll` should be created at all in cases where the compilation fails.

![image](https://github.com/user-attachments/assets/ba33d2e3-fecb-4e45-b0fb-d46204241f1c)
![image](https://github.com/user-attachments/assets/5d16b256-ba02-45cd-bb1a-0a8f88dbe3ab)
![image](https://github.com/user-attachments/assets/c6724fb6-bef2-4ded-9295-785394c00f56)

Thank you again for the comprehensive test scenarios—it’s instrumental in replicating and resolving such issues!

**Comment by tvatavuk** [comment] 2024-12-03 14:09
Issue is fixed.
It is expected to be part of the next 2sxc release.

**Comment by jaruiz1961-ual** [comment] 2024-12-03 20:47
Here it is the error in azure
https://ja-oqtane9.azurewebsites.net/accordion
If you want an account to install or uninstall and test it, let me know ...  jaruiz@ual.es

**Comment by jaruiz1961-ual** [comment] 2024-12-03 20:59
![image](https://github.com/user-attachments/assets/0385bde6-9ee6-43a0-ad8d-5ba0e5c47276)

**Comment by iJungleboy** [comment] 2024-12-04 05:26
we should have a release out by this weekend

**Closed by iJungleboy** 2024-12-04 05:26 UTC
