### ISSUE TITLE
400 Error when trying to "Replace with Existing" inside a Very Rich Text Content Item

### ISSUE THREAD

**Issue by 6TELOIV** [2sic/2sxc#3299] opened 2024-02-20 20:35 UTC
### I'm submitting a
[x] bug report

### ...about
[x] edit experience / UI
[x] Razor templating
[x] Content Types or data management
[x] other / unknown

### Current Behavior / Expected Behavior
Apps' content inside content blocks from Very Rich Text fields should be able to be replaced with existing content items. Currently, it gives a 400 error:

![image (11)](https://github.com/2sic/2sxc/assets/6667660/9545fdef-d3d0-4abd-9ee6-2483808e708d)

I have also included the Insights log where the error occurs below. It's from the web-api log: [Logs.htm.txt](https://github.com/2sic/2sxc/files/14350906/Logs.htm.txt)
### Instructions to Reproduce the Problem
1. Set up an app to use very rich text following the normal steps.
   - In this case, we are using `Custom.Hybrid.Razor14` with `Kit.Render.All` to render the Very Rich Text field/apps, but the issue manifests with `Custom.Hybrid.RazorTyped` as well.
2. Add the app a page, and add an App/Content block through the WYSIWYG editor and save it
3. Add any app with the "Replace with Existing" toolbar option to that block using the QuickE editor that shows up in the blank App/Content block
4. Click "Replace with Existing" and observe the error

### Your environment

* **2sxc version(s):** 16.07.00
* **Browser:** all
* **DNN:** 9.13.02
* **Hosting platform:** azure
* **Language:** English

**Comment by 6TELOIV** [comment] 2024-02-26 18:12
Not sure if it helps, I'm talking about clicking this button inside inner-content apps:
![image](https://github.com/2sic/2sxc/assets/6667660/0eefe9a0-2d89-405c-b066-b3d0d4118301)

**Comment by iJungleboy** [comment] 2024-02-27 06:48
This is an issue.

Basically every button has a context, providing information about the App it's on.

Apps inside Apps don't quite do this correctly, and it would take quite a bit of work to finish this, which is why we haven't found time to do it yet.

**Comment by 6TELOIV** [comment] 2024-02-27 16:27
Makes sense, and I figured about as much. I've also noticed some other oddities with them (moving items up and down in a list with toolbar buttons doesn't work, opening the list manager doesn't work). Wish I had more time to dive in and try to figure it out myself, haha!

**Comment by jeremy-farrance** [comment] 2024-03-06 23:38
Glad I found this, was about to post the same. I can confirm it is still a problem in the latest, v17.03.00 (on DNN v9.13.02).
 
If it helps; in our case we were in inner-content in the Accordion App (4.3.1) and adding Basic Content from the Content App (16.0.0).
 
We also noticed additional, probably related issues. If they are not related, please let me know and I can create new/separate issues. Also, there might be additional issues, I stopped after getting details and verifying the following 3:

- Toolbar buttons for Move Up and Move Down do not work
- Toolbar button for Remote Item (screenclip below) does not work (but adding an empty block does work)
- Toolbar button for Sort/Manage List immediately throw a bad request 400 error with, "Detail: Object reference not set..." (console error below)

![image](https://github.com/2sic/2sxc/assets/653301/fd766ff2-a288-4064-9cf6-ddd4210f6510)

![image](https://github.com/2sic/2sxc/assets/653301/6c9ac9cd-9689-4c3f-ae20-9a3547dcf9bf)

**Comment by jeremy-farrance** [comment] 2024-03-06 23:39
Question: this project is scheduled to go live Apr 2nd. Ever since we upgraded to v16.01 and then v16.07 LTS we have not been able to manage any inner-content beyond edit/save. We have the Accordion App in use on this site fairly extensively (the View has 43 instances across 30+ pages). Is there any chance this will be fixed in March? 
![image](https://github.com/2sic/2sxc/assets/653301/04433ecb-c545-43a3-b086-0ec66679e5e2)

**Comment by iJungleboy** [comment] 2024-03-07 06:23
TBH I believe this never worked before - if it did, I would appreciate knowing which fairly recent version - because then we would only have to re-fix. ATM I think we need to actually implement this.

I know we had started on this once about 2 years ago, but I thought we never completed it. 
Could be that we did though, and in that case we only need to re-apply it. 

Any chance you could find a sponsor? I think we would need ca. 1-1.5 days to make this work.

**Comment by jeremy-farrance** [comment] 2024-03-09 22:27
Okay, so I just installed a clean, new DNN instance using v9.13.03, then installed 2sxc v14.07.04 LTS.

Then tried to install an app; Accordion _4.3.1_ would NOT install, no errors, just "installed/success" then it wasn't there. Checked under the hood, the expected folder /Portals/0/2sxc/Accordion (or /Accordion4?) was not there.

But, Accordion **4.3.0** installed fine (not sure why 4.3.1 wouldn't install and did not show an error)

So, as expected, these things were working. See screen shot below. I was able to add Accordion sections with inner content and able to move them up/down, remove, add existing, and replace. I still have this instance available locally if there is anything specific you want me to test further that might help.

![image](https://github.com/2sic/2sxc/assets/653301/7a0638d5-9d05-4fe5-9699-f4063f3ba5f3)

**Comment by jeremy-farrance** [comment] 2024-03-11 15:26
Okay, so first I upgraded my testing site from 2sxc 14.07.04 to 17.01.07. Then installed CodeDom 3.6. Tested and as expected, _toolbar things were NOT working._ 
 
Downloaded and Installed v17.04.01 and ... FIXED. This is great, I hope you do the release soon, thank you!!

**Comment by iJungleboy** [comment] 2024-03-12 06:29
@jeremy-farrance & @6TELOIV pls also test other normal toolbar-to-dialog features, to verify that nothing new broke.

**Comment by iJungleboy** [comment] 2024-03-14 10:55
@jeremy-farrance I'm not too concerned with inner content working, since you and I tested it.

I'm more concerned if it could have some side-effects to anything else, live normal edit (not in inner content), etc. or replace-item (not inner content).

I have a good feeling, but would appreciate some testing. ;)

**Comment by jeremy-farrance** [comment] 2024-03-14 14:02
Okay, I switched and inserted a few different content types in the Content App and tested through all the buttons. Everything worked as expected. I did notice, in the standard/default toolbar, that in the 3rd group, the edit View Settings button was missing (only edit template, edit items of the data type, and edit fields of this content type were there. I think I am used to edit View settings being in there, but maybe not? Or maybe its not because I am in the Content module and not App? But anyhow, played around for a bit and all seems great and works as expected!

**Comment by iJungleboy** [comment] 2024-03-14 14:15
awesome, thanks!

Feel free to use this release, we plan to make another release end of next week ca. March 20.

**Closed by iJungleboy** 2024-03-14 14:15 UTC
Labels: waiting-for-input

**Comment by 6TELOIV** [comment] 2024-03-14 21:43
Thank you! As I mentioned in #3317 I won't be able to test for a little while, but I'll keep it on my to-do list!

**Comment by 6TELOIV** [comment] 2024-05-08 19:36
I have confirmed the fix; it works! Thank you so much for working on this one, it's a game changer for our content editors ♥

**Comment by iJungleboy** [comment] 2024-05-10 05:29
@6TELOIV thx for confirming 😉
