### ISSUE TITLE
image discoloration (image resizer .net)

### ISSUE THREAD

**Issue by ech01** [2sic/2sxc#908] opened 2016-08-24 15:51 UTC
It seems that the image resizer changes the color of the images. 

I notice mostly on graphics/logos etc. You can try with the attached image. Just add the resizer parameters in your template
![test-image](https://cloud.githubusercontent.com/assets/3790873/17937709/a9532bb6-69e8-11e6-8f53-11a6b4cac2c3.jpg)

**Comment by iJungleboy** [comment] 2016-08-25 06:53
Just a question, because your picture colors looks very unusual. Could it be that you are using a CMYK image instead of RGB? That can cause problems on so many levels, incl. how the client renders it, that in the end it could also have other reasons - not really caused by image resizer.

Here's how the SAME image is shown in by chrome vs. my outlook message which showed the notification (so no image-resizer here):

![image](https://cloud.githubusercontent.com/assets/5321186/17959547/564c5636-6aa1-11e6-938f-02608dae4e41.png)

**Comment by iJungleboy** [comment] 2016-08-25 10:56
I'm very convinced it's a color palette issue. Opening the same image in different browsers already renders different colors. So I think this may be accelerated by the image resizer, but to 99% it's an issue that must be corrected on the original picture. -- check my screenshot:

![image](https://cloud.githubusercontent.com/assets/5321186/17966725/581d2a22-6ac3-11e6-8791-df5a57d67cad.png)


I'll close this for now.

**Closed by iJungleboy** 2016-08-25 10:56 UTC

**Comment by ech01** [comment] 2016-08-25 14:21
Thanks. I did not create the image, but a lot of the images on our site only discolor when using image resizer. I will see if I can get the source file and resave.

**Comment by ech01** [comment] 2016-08-25 14:25
I really appreciate the effort you made in troubleshooting this. I hope that is the issue.
