### ISSUE TITLE
Using the image file manager (not Adam) returns an undefined image. 

### ISSUE THREAD

**Issue by haydentomas** [2sic/2sxc#2902] opened 2022-10-19 12:01 UTC
[x] bug report =>

Using the image file manager (not Adam) returns an undefined image. 

[x] admin experience UI

If you try to use the file manager to access /portals/0 and choose an image you get an undefined so an image cannot be selected

[I have attached a video ](https://user-images.githubusercontent.com/108055327/196684702-3870107a-0986-47bc-b2d2-e57b6cc76d37.mp4)

* **2sxc version(s):** 14.10.0
* **Browser:** All
* **DNN:** 9.10.2
* **Language:** [any/all | English | German | other ]

**Comment by iJungleboy** [comment] 2022-10-24 07:43
@haydentomas Is this issue new? We don't use this mode a lot, so it could have bee broken for longer. 

@tvatavuk can you look into this? My guess is the backnend doesn't give the right url, and this may have been broken for longer but we just never noticed?

**Comment by jeremy-farrance** [comment] 2022-10-29 16:13
We, as well as our clients, use the image/file manager this way frequently, so I hope this is helpful. 

First, on a site running DNN v9.10.02 with 2sxc v14.10.0 I verified haydentomas' issue as reported. 
 
Then I found a site running DNN 9.10.02 with 2sxc v13.10.1 and verified that things were working as expected.
 
Then I tested it after each of the following 2sxc upgrades. Testing was done using the Content App (v11.03) and the Image content-type:
 
v13.10.1 - working as expected
v13.12.01 LTS - still working
v14.07.04 LTS - working
v14.08.00 - working
v14.09.00 - not working; "file:undefined"
v14.10.00 - "file:undefined"

In case you spot a clue, here is a clip while its still working, v14.08.00
![image](https://user-images.githubusercontent.com/653301/198841188-4bcb1333-3a56-45e5-add9-c5028dd225a8.png)
 
And here is what it looks like when not working on v14.09.00
![image](https://user-images.githubusercontent.com/653301/198841546-94cdfdf5-6f37-4146-8e6e-83bdd9591d03.png)

**Comment by tvatavuk** [comment] 2022-10-31 12:30
> @tvatavuk can you look into this? My guess is the backnend doesn't give the right url, and this may have been broken for longer but we just never noticed?

I do not see issue in backend. With Image Manager, endpoint returns data that looks correct, with fileid etc. We have to look for issue at UI.

**Comment by iJungleboy** [comment] 2022-11-02 12:54
@jeremy-farrance I'm not sure if this is actually a 2sxc issue. 

Are you certain that the DNN DB and file system is in sync?

Can you check F12 and see what the list of images returns (is there a number for the "file:55" node in the json?

**Comment by jeremy-farrance** [comment] 2022-11-02 13:44
If you are unable to duplicate the issue, let me know and I will assist in figuring out what details might be different between our setup/environment. Best I can offer is to simplify the scenario, maybe on a fresh install, and get to the point where you can duplicate the issue?

All I did, the only change when it stopped working, was install 2sxc v14.09, DNN remained the same, no other settings or anything changed. I made a video just now after returning to the site/page, did a full Settings/Servers/Restart Application, then reloaded the page and started the video...
https://accuraty-my.sharepoint.com/:v:/p/jfarrance/EQK3Lz8JiS9Bi9FpozgZDpwBF_-uc564y3w3aeCJZ5a1Uw?e=CyeNFn

I am not familiar with how to debug this since we are a few levels deep in Angular stuff and as you can see, whatever JS is executing is not bubbling up its output/errors to the command line. I understand that you tested the end-point and its returning the expected "value." But "undefined" (usually a JS thing) is what is ending up in the UI element.

**Comment by tvatavuk** [comment] 2022-11-02 16:37
@jeremy-farrance thx fore great insights. 
I reproduced the issue on backend. It is side effect of migration from Newtonsoft.Json to System.Text.Json.
Created quick fix to preserve compatibility but need to look more into it latter.

**Comment by iJungleboy** [comment] 2022-11-02 17:18
@tvatavuk you should be enjoying your vacation ;) - I can't see that the fix changes anything... - telco on teams?

**Comment by tvatavuk** [comment] 2022-11-02 18:10
> @tvatavuk you should be enjoying your vacation ;) - I can't see that the fix changes anything... - telco on teams?

@iJungleboy thx 😊. 
My Internet connection on cruise can't handle telco. Even browsing or email is sometimes too much. 
Exact issue is related to STJ json serialization of AdamItemDto that is non generic base class without Id and ParrentId properties, so both are missing in Json response. This is known limitation of STJ. Workaround is to serialize to object. I did try to be more specific in response type like AdamItemDto<int,int> but there is some complexity that I could not solve easy, so I fallback to object, untill I find more time for proper solution.

**Comment by iJungleboy** [comment] 2022-11-02 18:34
@tvatavuk no problem. the `object` didn't seem to change anything. 
I'm working on it, so no worries - enjoy your vacation

**Comment by iJungleboy** [comment] 2022-11-02 19:01
is fixed in v14.11

**Closed by iJungleboy** 2022-11-02 19:01 UTC
